### ISSUE TITLE
[Feature Request] Use Algolia in the website 

### ISSUE THREAD

**Issue by azzamsa** [saadeghi/daisyui#1007]
Hi.

Many projects now use Docosarus which has  [Algolia](https://www.algolia.com/doc/guides/getting-started/how-algolia-works/)  support out-of-the-box.
The current search feature is very limited. Hiding many useful features and components.

One of the use cases is searching "hamburger":

![image](https://user-images.githubusercontent.com/17734314/183551389-e3f369cb-06d6-4244-9706-a39233d5ce9a.png)

![image](https://user-images.githubusercontent.com/17734314/183551371-8c6b3726-2728-422c-b701-78e314a40ac3.png)

Some example site that uses Algolia:
- https://tailwindcss.com/
- https://vueuse.org/

**Comment by saadeghi** [comment]
Actually, I don't want every part of the page to be searchable.  
I only want results for specific keywords.  
You mentioned "hamburger button" but I don't think it should come as a result because daisyUI does not have `hamburger button` as a component. It's just an example for using `swap`. The hamburger icon is not part of daisyUI and it can be replaced by any other SVG.  
Also, any keyword can be included or excluded from search with or without using a third party engine. So If I was using Algolia, I would customize the result the same way. It's intentional.

Let me know if you have any questions
