### ISSUE TITLE
Unable to select active button color in radio button group

### ISSUE THREAD

**Issue by Blackglade** [saadeghi/daisyui#1011]
Currently, when I specify html like this:
```
<div class="btn-group">
  <input type="radio" name="options" data-title="1" class="btn btn-ghost" defaultChecked={true} />
  <input type="radio" name="options" data-title="2" class="btn btn-ghost" />
  <input type="radio" name="options" data-title="3" class="btn btn-ghost" />
  <input type="radio" name="options" data-title="4" class="btn btn-ghost" />
</div>
```

This works perfectly fine until I want to change the radio button color that is checked by default to a different color (secondary/accent). Specifying btn-secondary does not change the color of the default checked one. I even tried using the `checked:` modifier to no avail. Any advice on what I am doing wrong or if this functionality is simply unavailable?

**Comment by saadeghi** [comment]
This is a CSS specificity problem. because child elements of `btn-group` get the style, the custom utility class will be overridden.  
One solution is to use `!` prefix for the custom utility class like this `checked:!bg-blue-300`  
https://play.tailwindcss.com/oEUDgJgpef

Let me know if you have any questions
