### ISSUE TITLE
Can't customize focus colors for select and other inputs

### ISSUE THREAD

**Issue by justingolden21** [saadeghi/daisyui#1071]
I have buttons that work fine using the four focus colors listed here: https://daisyui.com/docs/colors/

But my selects, inputs, and other elements when focused have a super super light outline that is barely visible. I can't see any way, in daisyui, tailwind, or vanilla css to solve this. I can only override it and it still appears.

**Comment by justingolden21** [comment]
Additionally, when applying `:focus` in the inspector, this style doesn't appear, even though all other focus styles appear. Very bizarre

**Comment by justingolden21** [comment]
```
	button:focus,
	select:focus,
	input:focus,
	label:focus {
		@apply outline-base-700;
	}
	```
is my temp solution but I have to copy paste this across everywhere it's relevant because it is not possible from the config. Only buttons use the focus variables defined in the theme file.

**Comment by biaocy** [comment]
Some new spec comes out, and the browser changed the pseudo-class name to `:focus-visible`

So we need to do this instead:
```css
:focus-visible {
   @apply <your style name>
}
```

**Comment by KQT3** [comment]
In order to change border/outline color when focus I used these classes 
```jsx
focus-visible:border-0
focus-visible:ring-0
focus-visible:ring-offset-2
focus-visible:ring-offset-orange-300
```

**Comment by ferdinand-varta** [comment]
Hi @saadeghi, this seems to be broken again... With new daisyUI 5 the outlines are completely black (or the color of the base-content) and i dont see an easy/clean way to overrule them. 
But for example `input-secondary` will change the outline to the secondary-color, maybe an option to pass any color would be possible (input-*)?

**Comment by jeffrockson** [comment]
I've tried everything I can think of with Tailwind's layering to modify the outline everywhere without needing to add my own utility class to every single form field. I can't get Tailwind to change anything about the focus styles without !important.

**Comment by saadeghi** [comment]
@jeffrockson @ferdinand-varta @jambobarnes @Teinble Can you share [Tailwind Play link](https://daisyui.com/tailwindplay/) please?

**Comment by thomaszlow** [comment]
Hi @saadeghi here is an example where you can see that you have no chance to overwrite the ring or outline color of the card. 
https://play.tailwindcss.com/or622BmJP3

**Comment by saadeghi** [comment]
In your example, there's no outline by default, so setting `outline-primary` does nothing. and when radio is checked and it gets an outline, the default color won't apply because `&:has(>:checked)` style is being used (the card that has a checked input)

To make it work, use this: `[&:has(>:checked)]:outline-primary` this will apply primary outline only when checkbox is checked.
For ring, you need to add `ring` class name. Tailwind CSS `ring-primary` class only sets the color and wont do anything if `ring` class doesn't exist.

https://play.tailwindcss.com/BjqPlo95CY

Let me know if you have a question.

**Comment by ferdinand-varta** [comment]
Hi @saadeghi (@jeffrockson @jambobarnes @Teinble), i'll provide another tailwind play with the basic problem i had in mind. Maybe im stupid and there is an easy solution :)

https://play.tailwindcss.com/FuSLiYkRjK

The focus outlines of all daisyUI components will get a base-content outline. How could we change this in one place instead of adding a custom class to every element? btn-primary or input-primary for example will change the outline but what about the standard color of the outline?

**Comment by saadeghi** [comment]
I'm not sure if I understood your goal correctly, but in case you want to set the color of outline in all variants of a form element into a specific hardcoded color, you can do something like this:  
https://play.tailwindcss.com/QvzkNoDw7R?file=css
```css
.btn, .input, .select{
  &:focus{
    @apply outline-blue-300;
  }
}
```

Let me know if you have a question.

**Comment by ferdinand-varta** [comment]
This was essentially my question but the solution will also overwrite the primary variants. So it would be a lot of manual config to just change the base variants and not the ones that have primary/secondary/warning... applied.

**Comment by saadeghi** [comment]
@ferdinand-varta I see. In that case, using `focus:outline-blue-300` utility class for each item is the easiest way:  
https://play.tailwindcss.com/RlTdmitecH

Also if you want full control of customizing anything, you can `exclude` a specific component like
```js
@plugin "daisyui" {
  exclude: input;
}
```
and then copy the [source code](https://raw.githubusercontent.com/saadeghi/daisyui/refs/heads/master/packages/daisyui/src/components/input.css) into your CSS file and customize anything.

Let me know if you have a question.

**Comment by jeffrockson** [comment]
I got it to work without **!important**. I didn't understand the @utility preprocessor because I'm new to Tailwind and was looking at its own @layer. I found the Daisy docs not providing enough description of how to make changes, so everything I was doing with TW was getting in turn overwritten by Daisy defaults. I recommend improving the docs around this matter.

In the end this achieves the desired result for me:

```
@utility input {
  &:focus {
    @apply outline-1 outline-base-content/50 outline-offset-0;
  }
}
```

**Comment by saadeghi** [comment]
At the moment, we don't have much control over the layers using Tailwind CSS plugin API and Tailwind CSS adds everything into utilities layer. even the components go to utilities layer an the `components` layer is unused.

Please upvote this issue on Tailwind CSS repo: https://github.com/tailwindlabs/tailwindcss/issues/15045  
Hopefully there will be an improvement on this so we can properly manage the styles in layers and make the customization more predictable.

**Comment by MahdiTa97** [comment]
I tried this:
```css
.btn,
.input,
.select {
  &:focus {
    @apply outline-transparent;
  }
  &:focus-within {
    @apply outline-transparent;
  }
}
```
