### ISSUE TITLE
Discord 

### ISSUE THREAD

**Issue by UmbrellaCrow612** [saadeghi/daisyui#1075]
Does or will daisy ui have a discord community channel ?

**Comment by saadeghi** [comment]
Currently there's no [official] discord server. I think [GitHub Discussions](https://github.com/saadeghi/daisyui/discussions) is a better place to talk about ideas or ask questions because everything will be indexed on search engines and it would be easier to search. Questions on GitHub Discussions, usually will be answered less than 24 hours.
