### ISSUE TITLE
Ranger Slider broken on Safari if preceded by an audio tag

### ISSUE THREAD

**Issue by guidotripaldi** [saadeghi/daisyui#1105]
On Safari, both desktop and mobile, the left side of the slider is squared instead of rounded if a preceeding audio tag (not necessarily immediately preceding) has its controls visible (ex. 1). Instead it looks normal when the audio tag has no controls (ex. 2), or when viewed on Firefox/Chrome.

### Example 1

This code
```html
    <audio  controls src=""></audio>
       ...
    <input type="range" min="0" max="100" class="range w-40 max-w-xs">
```
![image](https://user-images.githubusercontent.com/12702951/188879999-4667f5a5-edbe-40c3-91f6-8cdbc22c33c3.png)

###  Example 2
```html
    <audio src=""></audio>
       ...
    <input type="range" min="0" max="100" class="range w-40 max-w-xs">
```

![image](https://user-images.githubusercontent.com/12702951/188880401-8e0cdf5b-7370-43bf-acaa-e0af168d93af.png)

**Comment by saadeghi** [comment]
This is really a weird bug from Safari. I mean one element affecting another element's style...  

**This is what's happening here:**  
daisyUI's range slider gives the `-webkit-slider-runnable-track` a large box shadow on the left, because as far as I know that's the only way of having a cross browser, styleable range slider where the left part of the track is distinguishable from the right part. And the whole input has `overflow-hidden` so the large box shadow will be cropped to the border radius of our input. That is indeed a hacky way, but there's no better option to style the native range slider the way we want.

**So What's the issue?**
For some reason, Safari, does not crop the overflow of box shadow to the border radius of `slider-runnable-track` when there is a `<audio controls src=""></audio>` before it 😐

**Solution?**
I can't do anything about it on my side because the bug is from Safari.  
I don't even know how to open an issue on Webkit issue tracker because the way I'm styling the range slider is a hacky way and I'm sure no one on Safari dev team would care about this edge case.

**Workaround**
I found a weird workaround for this weird bug 🤡  
I don't even have an explanation on why this works, but here it is:
```html
<audio class="relative z-10" controls src=""></audio>
<input type="range" min="0" max="100" class="range w-40 max-w-xs">
``` 
for some reason, making the `<audio>`'s position relative and giving it a `z-index`, fixes the issue.
