### ISSUE TITLE
Can't click dropdown items in Safari

### ISSUE THREAD

**Issue by flurie** [saadeghi/daisyui#116]
It appears that elements in dropdown menus cannot be clicked in Safari v14.1.2.

You can try this out in this example. In Chrome, clicking an item in the dropdown fires the onclick, but in Safari it does not.

https://codepen.io/flurie/pen/xxdJKYz

**Comment by saadeghi** [comment]
@flurie  You need to add a `tabindex="0"` to the `dropdown-content` too:  
https://codepen.io/saadeghi/pen/xxdJxmb  

>**Reason:**  
Safari has a different behavior about focus. If we want a clickable item inside the dropdown, we need to make the `dropdown-content` focusable so the menu item can be clicked while the dropdown still has the focus. otherwise, when we click the menu item, safari first removes the focus of the parent (dropdown) so the dropdown will get closed before the click event even start.
