### ISSUE TITLE
Support .daisy- prefix

### ISSUE THREAD

**Issue by ericclemmons** [saadeghi/daisyui#117]
On existing sites, `.btn`, `.card`, etc. are extremely common.

Can https://daisyui.com/docs/config include an option for `prefix` for incrementally adopting daisyUI?

```js
module.exports = {

    // add DaisyUI plugin
    plugins: [
      require('daisyui'),
    ],

    // config (optional)
    daisyui: {
      styled: true,
      themes: true,
      base: true,
      utils: true,
      logs: true,
      rtl: false,
      // 👇  ex. `daisy` will turn `.card` into `.daisy-card`
	  prefix: null, 
    },

  }
```

**Comment by saadeghi** [comment]
@ericclemmons  I'm afraid I can't add it as an option (like you mentioned) unless:
- I do major changes and rewrite all components as css-in-js
- or I add some PostCSS dependencies (which I prefer not if possible)

However, you can use [Tailwind's `prefix` option](https://tailwindcss.com/docs/configuration#prefix)  
And if yo want the prefix only for daisyUI classes (not all Tailwind classes), I recommend having 2 Tailwind builds. One with `prefix` and daisyui as a plugin. the other one just for Tailwind utilities.
This way, only daisyUI classes will have prefix (`.card`  => `.daisy-card`), all tailwind classes will stay the same and you can have your custom `.card`, etc... styles.

Example repo here: https://github.com/saadeghi/daisyui-prefix-example

please let me know if you have any questions.

**Comment by danielehrhardt** [comment]
The Prefix does not work on my side. 
![image](https://user-images.githubusercontent.com/19570043/142938047-383d1428-c70c-4000-8625-5e6451ecc72e.png)
![image](https://user-images.githubusercontent.com/19570043/142938072-0e7ecc1c-f809-4d87-8b6f-d408afdc7637.png)

The Styles are applied also with prefix. 

Using Tailwind in a Angular 13 Projekt. Does not work with jit or without.

**Comment by danielehrhardt** [comment]
> @ericclemmons I'm afraid I can't add it as an option (like you mentioned) unless:
> 
> * I do major changes and rewrite all components as css-in-js
> * or I add some PostCSS dependencies (which I prefer not if possible)
> 
> However, you can use [Tailwind's `prefix` option](https://tailwindcss.com/docs/configuration#prefix) And if yo want the prefix only for daisyUI classes (not all Tailwind classes), I recommend having 2 Tailwind builds. One with `prefix` and daisyui as a plugin. the other one just for Tailwind utilities. This way, only daisyUI classes will have prefix (`.card` => `.daisy-card`), all tailwind classes will stay the same and you can have your custom `.card`, etc... styles.
> 
> Example repo here: https://github.com/saadeghi/daisyui-prefix-example
> 
> please let me know if you have any questions.

Really hard to work with that Solution in Development.

**Comment by saadeghi** [comment]
@danielehrhardt `prefix` is not one of daisyUI config options. it's for Tailwind config. look at this example repo: https://github.com/saadeghi/daisyui-prefix-example/blob/8de5168c63052b75b081aff51a947ac6492292a0/tailwind-daisy.config.js#L2

**Comment by danielehrhardt** [comment]
> 

Yes saw it on your comment. Sorry. Was to late. Check out my latest comment.

**Comment by saadeghi** [comment]
I know having 2 css doesn't look good but daisyUI is a plugin for Tailwind CSS after all.  
If there's a `prefix`, it will apply to both Tailwind classes and daisyUI classes. unless you separate it in 2 files.

The problem is, we can't add a PostCSS file to Tailwind as a plugin. As you can see [here](https://github.com/saadeghi/daisyui/tree/master/src/components) these are component source files and they use `@apply` to get Tailwind's utility classes, during the [build](https://github.com/saadeghi/daisyui/blob/bdba211fbafcc36f62bd119be24959adb7edb18f/package.json#L77) time, they all get processed using multiple Tailwind builds (because they need new utility classes, new color values, etc...) and they turn into JS objects so I can inject everything as `utility`, `base`, and `component` to Tailwind. It's not easy to rewrite this flow just because a prefix option and It's not wise to do so when Tailwind already has that config, plus there are other PostCSS plugins for that.

**Comment by saadeghi** [comment]
New `prefix` config added to daisyUI `2.4.0`  
https://daisyui.com/docs/config/
