### ISSUE TITLE
RGBA colors doesn't work inside `mytheme`

### ISSUE THREAD

**Issue by ZvezdocheTag** [saadeghi/daisyui#118]
I have been trying to implement my custom color config inside `daisyui`, but found that rgba colors doesn't work,
it haven't been supported yet, or maybe some additional configuration required?

Example:
```js
  daisyui: {
    themes: [
      {
        mytheme: {
          // doesn't work
          primary: 'rgba(238, 45, 69, 1)',
          // work
          'primary-focus': '#00f',   
          'primary-content': '#fff',
  ...
  ```
  
  "daisyui": "^1.10.0",

**Comment by saadeghi** [comment]
For now, only hex colors are supported inside config.  

The reason is that I don't use the exact color values from config, I [convert](https://unpkg.com/browse/daisyui@1.11.0/colors/colorNames.js) the human readable color names (`primary`, `secondary`) to CSS variables (`--p`, `--s`) and I get the `H`,`S`,`L` values (like `259` `94.4%` `51.2%`) from the solid hex color (like `#570df8`) this way I can use  each value separately and I can add/remove `Alpha` value conditionally.  

I might add support for RGB and other formats too but it requires additional dependencies to first detect the format of color and then convert each format using a proper function to finally extract the `H`,`S`,`L` values.  

If all your color values are RGB, I suggest using an external tool to convert them all to Hex, so you can use them in daisyUI config.  
A few VSCode plugins to convert color format: 
- https://marketplace.visualstudio.com/items?itemName=bbugh.change-color-format
- https://marketplace.visualstudio.com/items?itemName=medzhidov.hex-rgba-converter
- https://marketplace.visualstudio.com/items?itemName=dakshmiglani.hex-to-rgba

**Comment by ZvezdocheTag** [comment]
Got it, thanks. 

I see that you write your custom solution to convert fromHexToHsl, but maybe will be useful this module https://github.com/gka/chroma.js
It's pretty straightforward, and you don't need care about color input format, just directly convert to any other type, like:

```js
chroma('orange').rgba(); // [255,165,0,1]

chroma('#f00').hsl(); // [0,1,0.5,1]
```
https://vis4.net/chromajs/#color-hex


I did some script to convert colors for myself with nested structure, maybe will be useful for someone, I'll leave it there

```js
const chroma = require('chroma-js');

const currentThemeColors = {
  black: 'rgba(0, 0, 0, 1)',
  white: 'rgba(255, 255, 255, 1)',
  primary: {
    DEFAULT: 'rgba(238, 45, 69, 1)',
    lighter: 'rgba(253, 226, 230, 1)',
    light: 'rgba(244, 118, 133, 1)'
  }
}

const iterate = (obj) => {
    Object.keys(obj).forEach((key) => {
      if (typeof obj[key] === 'string') {
        obj[key] = chroma(obj[key]).hex();
      }
      if (typeof obj[key] === 'object') {
        iterate(obj[key]);
      }
    });
  };
  
iterate(currentThemeColors);
```
