### ISSUE TITLE
tailwind typography affects card-title h2 margins

### ISSUE THREAD

**Issue by bbugh** [saadeghi/daisyui#1229]
Hi! 👋🏻 daisyUI is very cool, thanks for making and sharing it.

I noticed while using `prose` with the example card code that `card-title` does not remove the heading margins added by @tailwind/typography.

**Expected**

![Screen Shot 2022-10-08 at 21 49 27](https://user-images.githubusercontent.com/438465/194735350-12ea4a60-31bd-4fc0-b347-fec33a3119ae.png)

**Actual**

![Screen Shot 2022-10-08 at 21 45 49](https://user-images.githubusercontent.com/438465/194735308-a531f502-03b5-4292-96e2-862c882f9493.png)

<details>
<summary>Example HTML</summary>

```html
<main class="prose">
  <div class="card w-96 bg-base-100 shadow-xl">
    <div class="card-body bg-info-content">
      <h2 class="card-title">Card title!</h2>
      <p>If a dog chews shoes whose shoes does he choose?</p>
      <div class="card-actions justify-end">
        <button class="btn btn-primary">Buy Now</button>
      </div>
    </div>
  </div>
</main>
```
</details>

**Comment by NikarashiHatsu** [comment]
This is definitely not the issue in DaisyUI, fyi `prose` is affecting all of the typography components for its children.

Use `no-prose` along with `card`. It should fix the issue. Let me know if the issue still persists.

**Comment by bbugh** [comment]
I don't know either way, but the docs recommend using @tailwindcss/typography: https://daisyui.com/docs/layout-and-typography/, so the components of the library being changed by it is unexpected.

**Comment by NikarashiHatsu** [comment]
The way @tailwindcss/typography works is expected, it re-styles the typography elements that TailwindCSS has reset.

You should only use `prose` in a content that heavily relies on typography such as a blog, or an article post. Not to style the entire body. Please read their whole [Typography documentation](https://tailwindcss.com/docs/typography-plugin).

Just in case you want to disable a component's typography utility, use the `not-prose` class.

**Comment by bbugh** [comment]
Thank you, I understand, I'm saying that this is not expected. The way this is [explained in the docs](https://daisyui.com/docs/layout-and-typography/#-1):

> You should use official [TailwindCSS Typography plugin](https://github.com/tailwindlabs/tailwindcss-typography). It handles everything and it's fully customizable ***daisyUI adds some style to @tailwindcss/typography so it will use the same theme as other elements.***

I read that as "use the same theme as other elements" to be "applying DaisyUI styles so it looks correct with DaisyUI" but that's not the case.

It seems like this would benefit from adding additional info to the docs.

**Comment by saadeghi** [comment]
I think it's important to know where to use `prose`  
Read the first paragraph [here](https://tailwindcss.com/docs/typography-plugin):
>The official Tailwind CSS Typography plugin provides a set of prose classes you can use to add beautiful typographic defaults to any vanilla HTML you don’t control, like HTML rendered from Markdown, or pulled from a CMS.

No one can guarantee your CSS to work correctly when you apply typographic style to any other element. Typography plugin, as mentioned, should be used for content like paragraphs, headings, bullet points, etc.

I highly recommend to be careful with using `prose` class. Yes. It's recommend to use Typography plugin. But not as a parent of a `card` or any other element that must have specific style because Typography plugin will apply its own CSS and does not care about other styles.

You should only use `prose` for the sections that are pure content (headings, paragraphs, bullet lists, etc)

Let me know if you have any questions
