### ISSUE TITLE
tables overflow on smaller screens

### ISSUE THREAD

**Issue by gacallea** [saadeghi/daisyui#1284]
hi :)

ref. code: https://github.com/gacallea/gentlewashrec/blob/main/templates/albums.html#L136-L170
ref. issue page **with** table: https://gentlewashrecords.com/albums/aasb
ref. working page **without** table: https://gentlewashrecords.com/albums/liminal

using tables in daisyUI overflows on smaller screens. I tried anything I could think of to make it work. it think it's a bug.

happy to provide more details and available for tests.

**Comment by saadeghi** [comment]
This is tricky because you have paddings around your table and then you have `w-full for the table container` which will fill the whole width and the minimum width would be the minimum width of the table content. So, to fix this special case, you need a class name like `w-[calc(100vw-4rem)]` so your table container fills the whole browser width, minus `2rem` padding on the sides:
```diff
- <div class="overflow-x-auto w-full">
+ <div class="overflow-x-auto w-[calc(100vw-4rem)]"> 
  <table class="table table-compact table-zebra w-full">
    ...
```

**Comment by gacallea** [comment]
thank you so so much! :)

the weird thing is that I tried even with w-full on either or both, then max-w-prose, then extrapolating the table out of the card, and so on. still no luck. you solution + lg:w-full works.
