### ISSUE TITLE
Avatar Placeholder does not center when using tailwindcss @apply method and loading in styles

### ISSUE THREAD

**Issue by the-programmer-alex** [saadeghi/daisyui#1292]
Using NextJS, when importing in the avatar and placeholder classes, the span content does not center. However, when directly using the classes, it does. 

JSX Component
```
import styles from '@/components/ListItem.module.css'

      {/* Imported class styles doesn't work for Avatar/Placeholder. Doesn't center content */}
      <div className={styles.item_avatar_container}>
        <div className={styles.item_avatar_shell}>
          <span className={styles.item_avatar_text}>
            T
          </span>
        </div>
      </div>
     
      {/* This works, centered content */}
      <div className="avatar placeholder">
        <div className="bg-neutral-focus text-neutral-content rounded-full w-24">
          <span className="text-xl">K</span>
        </div>
      </div> 
```

CSS File
```
ListItem.module.css

.item_avatar_container {
  @apply avatar placeholder
}

.item_avatar_shell {
  @apply bg-neutral-focus text-neutral-content rounded-full w-16
}

.item_avatar_text {
  @apply text-xl
}
```

Would this be an issue with Daisyui or more of an upstream problem? For now, the solution would be just to not use css file imports for avatar and placeholder classes.

**Comment by saadeghi** [comment]
I wouldn't suggest using daisyUI like this because when you use daisyUI class names with `@apply` inside another class name it all depends to the CSS build tool to how it renders the original style to the new class name and It's not accurate sometimes.

In this case, this is the daisyUI style for placeholder:
```css
.avatar.placeholder > div {
    display: flex;
    align-items: center;
    justify-content: center;
}
```
But since you're not using `avatar` and `placeholder` together, that line of style wouldn't apply. You can add the following style to your CSS to fix this:
```css
.item_avatar_container > div {
  @apply flex items-center justify-center;
}
```

But again, I suggest not using daisyUI or even Tailwind CSS like this. This was a common practice with CSS modules but using utility-first frameworks like Tailwind CSS, you won't need to manually add `component.module.css` files. Simply use Tailwind class names and everything will be easier, faster, more efficient and your shipped CSS code will be smaller. Utility-first frameworks are about re-using styles but when you use them like CSS modules, there will be more no re-usable style because your build tool generates new lines of style for each component.
