### ISSUE TITLE
Trigger drawer programmatically.

### ISSUE THREAD

**Issue by dcruz1990** [saadeghi/daisyui#1298]
Hello, is there a way to trigger drawers from JS? i have to get the element using `document.getElementById()` and then clicks? or there is another way to do it?

**Comment by saadeghi** [comment]
The checkbox controls the drawer.  
You can check or uncheck the checkbox using JS.  Here's an example: https://www.w3schools.com/jsref/prop_checkbox_checked.asp

But if you're using a JS framework or compiler (React, Svelte, Vue, etc...) dont' use `document.getElementById`. Instead bind the value of checkbox using the syntax of your JS framework.

**Comment by MikePreston17** [comment]
Here's how I did it using [AlpineJS](https://alpinejs.dev/):
```
<div id = 'container' x-data="setup()"> 
//... other stuff
<input id="my-drawer" type="checkbox" x-model="drawer_is_active" :checked="drawer_is_active"
      class="drawer-toggle" />
    <div class="drawer-content">
    
//... contents of my current page...
</div>

// this is a script I place at the bottom of my HTML.  Also works with templating engines like Razor Pages or Django.
<script >
function setup() {
   return {
      drawer_is_active: false,

      toggle_drawer() {
        console.log('toggling...')
        this.drawer_is_active = false;
        console.log(this.drawer_is_active)
      },
}
}
</script>
```

Breakdown:

- `x-data` tells Alpine to treat all vars as reactive, as well as to import methods.  These are both scoped to the `div`.

- `x-model` tells Alpine to treat `drawer_is_active` as the model for the input field to read from.

- `:checked` is shorthand for the `x-bind:` directive.  It does what it says - binds the input's `checked` value to `drawer_is_active`.

*NOTE: Normally, AlpineJS would have no trouble recognizing `drawer_is_active` the input, which is inside the `div`.  Why it doesn't idk, but `x-model` seems to be necessary in this case*

There may be a better way, but this is the easiest I've tried since reading some of the other answers here.

I'd suggest adding AlpineJS to your projects.  It makes weird things like this simpler and lets you control your HTML way easier than Vanilla JS in many cases.
