### ISSUE TITLE
Framework components for Svelte/Sapper with daisyui

### ISSUE THREAD

**Issue by moisesbites** [saadeghi/daisyui#13]
Hello @saadeghi ,

Your UI framework is the best I found in the web. And, now I am working in a project with [Svelte](https://svelte.dev/Svelte)/[Sapper](https://sapper.svelte.dev) and I think would be good to implement a solution like a component framework for Svelte/Sapper using your UI framework.

I'm not good with css, but the Svelte/Sapper is very easy to work with components.

What do you think about that?

**Comment by saadeghi** [comment]
Thanks!
I think there's a long long way for a Svelte version. Currently I'm focusing on adding all common components (the list at the end of readme file) as HTML/CSS for DaisyUI version 1.0.0
Then I can work on JS framework releases. React and Vue would be first picks because of the larger audience. Then I can work on a Svelte version.  
So... It will not be ready anytime soon unless someone else contribute for it.

**Comment by jquesada2016** [comment]
I'm working on this now, though focusing on the components I need the most at the moment. I'll create a pull request when I think I have something decent.

**Comment by moisesbites** [comment]
@jquesada2016 Great! Very good! 

About Sapper, I changed it to Svelte.kit. But, it's still Svelte.
