### ISSUE TITLE
Using @apply on indicator class does not correctly apply the style

### ISSUE THREAD

**Issue by the-programmer-alex** [saadeghi/daisyui#1346]
Using Nextjs css modules, tailwind and daisyui, using the `indicator` class with @apply in a module doesn't work, the styles aren't applied properly. 

But it does work fine when setting directly in the HTML. Which is strange, because most of daisyui works via @apply. 

```
MyItem.module.css

.indicator_div {
  @apply indicator
}

.indicator_btn_item {
  @apply indicator-item indicator-bottom indicator-center flex items-center justify-center
}

```

```
Component

    // Works fine when applied directly
    <div className="indicator">
      {/* Indicator styled as button */}
      <div className="indicator-item indicator-bottom indicator-center flex items-center justify-center">
        <button className={styles.indicator_btn}>{skill}</button>
      </div>

     // Fails when using the .module.css styles, even if the parent `indicator` class has been applied directly
      <div className={styles.indicator_btn_item}>
        <button className={styles.indicator_btn}>{skill}</button>
      </div>

      {/* Card with image */}
      <div className={styles.indicator_card}>
        <figure>
          <img
            className={styles.indicator_img}
            src="https://placeimg.com/400/225/arch"
            alt="Shoes"
          />
          {/* TODO: Enable real image after adding into folder */}
          {/* <img src={imageFileName} alt='Skill Image'/> */}
        </figure>
      </div>
    </div>

```

### Images
**Styles applied via module. Failed**

![image](https://user-images.githubusercontent.com/114461478/201451759-733564ca-0672-46b1-aae7-fefd42d65d4e.png)

**Styles applied directly. What it should look like**

![image](https://user-images.githubusercontent.com/114461478/201451796-2301e55a-69fd-42f1-8a84-b751852e7567.png)

### Versions
```
    "daisyui": "^2.38.1",
    "next": "^13.0.2",
    "react": "^18.2.0",
    "react-dom": "^18.2.0",
    "tailwindcss": "^3.2.2",
```

**Comment by saadeghi** [comment]
May I ask why are you using CSS modules for a utility-first CSS framework?  

Because the whole point of Tailwind CSS is to avoid scoping styles so we end up with one small CSS file for the whole app instead of duplicate styles for each component. Scoping styles using `@apply` inside a component is not a good idea because your app will have much much more lines of CSS shipped to production (because of duplicate lines of styles).  
The best way is to just use CSS classes inside your component.

There's no guarantee for CSS modules to work correctly with `@apply` because when we use `@apply` in a specific component, The build tool processes the style to rename all class names to new class names and when there's a child selector or sibling selector or any relation between the style of elements, there's a high chance the CSS processor can not see the relation.

**Comment by the-programmer-alex** [comment]
For neatness and readability. It's all scoped to each component, and if I needed to duplicate styles, then I'd make a top level css module. But, I guess this would be an issue with the "There's no guarantee for CSS modules to work correctly with @apply" part you mentioned. 

I think it's just something that needs to be figured out per individual daisyui class then. Some specific daisyui classes don't work with `@apply`, but most do. 

[Nextjs component level css](https://nextjs.org/docs/basic-features/built-in-css-support#adding-component-level-css)

**Comment by saadeghi** [comment]
I really really don't recommend using using CSS modules and utility first libraries (like Tailwind CSS) together.  

**Consider this scenario:**  
Let's say a HTML page has elements that need 100 total unique CSS rules for styling. Theoretically that would result about 100 utility classes made by Tailwind. But when you scope the Tailwind CSS utility classes in each component using CSS modules, it will create duplicate styles.  

If we have 20 components and each component use 20 of our total needed 100 CSS rules, CSS modules creates 20*20=400 unique class names. Each of our 20 components is generating 20 unique class names for duplicate CSS rules just because it is scoped to the component.  

The larger the project gets and the more components you have, it will dramatically increase the total size of CSS you're delivering to the browser (2x to 10x in size)
