### ISSUE TITLE
Tailwind /w daisyUI Dark Mode workflow

### ISSUE THREAD

**Issue by musosoft** [saadeghi/daisyui#137]
Hi,

Currently, I'm using your `theme-change` package to toggle `mytheme-light` and `mytheme-dark`.  Now let's say I want to use Tailwind's '[dark:](https://tailwindcss.com/docs/dark-mode)' prefix e.g.:
`bg-white dark:bg-gray-800`

What would be the best way to make it compatible with the daisyUI dark theme, along with `theme-change` toggle and `darkMode: 'media'` in `tailwind.config.js` to support `prefers-color-scheme` also?

 Not sure, if it's clear what I mean. Basically I want to:
1. set `mytheme-{light|dark}` on the first page load based on `prefers-color-scheme` 
2. if user toggles the theme then save it in localstorage
3. if `mytheme-dark` is set, make the `dark:` prefix work and vice-versa.

Thank you for your help, hope it will help others too to bridge these two awesome CSS tools.

**Comment by saadeghi** [comment]
@musosoft daisyUI themes and Tailwind's dark mode are 2 different methods. I don't think using both at the same time makes sense.

Tailwind color names (gray-200, red-500, etc...) are the actual name if the colors. So when you want a dark text on light background you need to use something like `text-gray-900 bg-gray-100` and also `dark:text-gray-100 dark:bg-gray-900` for the dark mode.
There's no way other than defining every exact color for every element.

daisyUI colors however are using a different approach.  
We name the colors as `primary`, `base-100`, `base-content`, etc... So the class names in your HTML won't care what color is a `primary` color. The primary color is a CSS variable. Could be red in one theme. Could be green in another theme. So when we change themes, the class names on HTML stays the same. This way we can achieve multiple themes with 1 class name.

Achieving this with Tailwind's color names and prefix classes would be a chaos:
```
theme1:bg-gray-200 theme2:bg-gray-900 theme3:bg-blue-100 theme4:bg-blue-900
```
That would be so many classes. For each theme.
But with daisyUI colors you just need `bg-primary` and the value of primary changes based on theme.

So what to do?
You won't need dark mode prefixes.
You can customize theme colors in daisyUI. Your first custom theme on tailwind.config.js would be the default (light) theme.
The built-in `dark` theme also activates for `prefers-color-scheme`. If you name your own custom theme as `dark` that would also work with `prefers-color-scheme`

Please let me know if you have any questions.

**Comment by RSickenberg** [comment]
@saadeghi IMO, what would be cool is to be able to use `dark:` modifier form Tailwind to change the color 😃,

Like `btn-default` and `dark:btn-defaultDark`.

**Comment by saadeghi** [comment]
@RSickenberg I mean... It doesn't fix any problem 🤷‍♂️

**Comment by musosoft** [comment]
@saadeghi appreciate a fast and comprehensive answer. I would like to describe my feeling and point of view, hope it can be well digested on your side.

I have discovered daisyUI just a few days ago. I was amazed about how nice the components are, and thought it would ease the development of my blog. I already coded it for plenty of time and it's full of Tailwind classes. My idea was that I will just install daisyUI and use the best of both worlds. Reading your reply I am now completely lost. Now I would need to change all the color classes I have used before. Lose all the class freedom I had and basically make the project closer to Bootstrap than Tailwind. I'm thinking if it's good enough to sacrifice that just to be fit for those nice daisyUI components and other benefits it offers. 

I would really like to see daisyUI being more integrated into Tailwind's ecosystem. It seems they are not on the same boat now :( 

Hard to think about how to make it different than it is now, though. I might just silently copy the design and combine your class name ideas with Tailwind's `@apply` functionality along with `dark:` prefix and so on.

Damn it me, why I never read the docs better before I spend day(s) experimenting...

**Comment by saadeghi** [comment]
@musosoft I understand but the whole reason I used this color system was to make things easier and cleaner.  
Using Tailwind's dark-mode, we need to add `dark:` prefix to every color (which must change)
```html
<div class="bg-gray-100 text-gray-700 dark:bg-gray-700 dark:text-gray-100">
</div>
```
- ☹️ You can't have a third theme. only light/dark
- ☹️ You have to add a `:dark` class for every color utility class you have in order to define a different color for dark mode.
- ☹️ You end up with slightly different colors used all over the pages. (should I use `gray-600` or `gray-700`?)
- ☹️ If you decide to change one color on your design you should replace hundreds of class names.

But with daisyUI colors, you just need
```html
<div class="bg-base-100 text-base-content">
</div>
```
- ✅ You can have multiple themes
- ✅ You don't need to add another class names for a new theme
- ✅ You have one source of truth for your color values, like any design system.
- ✅ You can change a color everywhere, without changing class names

I see this as a better option.

However, this is not forcing anything.  
You can use daisyUI components but you can keep using Tailwind colors and Tailwind's dark mode.
You can use `btn` component but instead of `btn btn-primary` you can use `btn bg-red-500 dark:bg-blue-500` or any other color.
There is no limit but for theming, you just need to **pick one side**. Using Tailwind dark-mode or daisyUI colors. Both works but you can't  use both at the same time.

Please let me know if you have any questions
