### ISSUE TITLE
Feature Request: Use of semantic HTML

### ISSUE THREAD

**Issue by shreyas2101** [saadeghi/daisyui#1371]
It would be nice to use semantic HTML in the components which will be helpful for Server-side rendering.

**Comment by saadeghi** [comment]
Please be more specific.  
Which component an which tag is causing issues for you?

**Comment by shreyas2101** [comment]
> Please be more specific. Which component and which tag is causing issues for you?

For example - the navbar component doesn’t use the <nav> tag, it uses a <div> instead

**Comment by saadeghi** [comment]
daisyUI styles are based on class name so you can safely use `<nav>` tag instead of div. As long as it has the class name, it will work.

The reason I used div in the examples is that `div` is a general propose container. Developers can replace it with anything else.  
`<nav>` tag semantically should be used for the navigation menu. However, the `navbar` component that daisyUI provides, is not essentially a navigation menu. As you can see on the examples, it can just contain a logo. Or a logo + a Signup button... It can be anything.  

So if your `navbar` component doesn't have a literal navigation menu, I don't think you should use `<nav>` for it.

Let me know if you have any questions.
