### ISSUE TITLE
Feature request: Generate color name for element states

### ISSUE THREAD

**Issue by dacrystal** [saadeghi/daisyui#1377]
I would be to nice to have color names generated for element states (using CDN).

The following example will not work:

```html
<input type="checkbox" class="peer"/>
<span class="peer-checked:text-neutral peer-checked:no-underline text-base-300 line-through">Checked</span>
```

However, using `var` works:
```html
<input type="checkbox" class="peer"/>
<span class="peer-checked:text-[color:var(--n)] peer-checked:no-underline text-base-300 line-through">Checked</span>
```

**Comment by saadeghi** [comment]
Unfortunately It's not worth it to add `peer-checked` prefix for all color names in the CDN file because CDN file is already too large and people rarely use `peer-checked`.  
Adding this prefix for all color names will increase the file size by 1MB at least.  
I recommend to build the CSS file using the NPM package because daisyUI CDN is just for test projects.

Let me know if you have any questions.
