### ISSUE TITLE
Navbar is not correct in mobile 

### ISSUE THREAD

**Issue by Thenafi** [saadeghi/daisyui#1386]
![Screenshot_2022-11-24-11-30-29-00_40deb401b9ffe8e1df2f1cc5ba480b12.jpg](https://user-images.githubusercontent.com/65831153/203701891-928eaf1a-fe54-40a2-9452-86c2eb5314f7.jpg)

This not render correctly in phone.

**Comment by Sahad-09** [comment]
Why would someone want to use daisy UI from their phone ?!

**Comment by sgrds** [comment]
Having mobile responsiveness built in would be fantastic, as I typically have to implement it myself. It would be very convenient to have it included by default.

**Comment by saadeghi** [comment]
This is fixed.

> Having mobile responsiveness built in would be fantastic, as I typically have to implement it myself. It would be very convenient to have it included by default.

For navbar I really shouldn't decide for everyone how they want their items too look like on mobile.

From [this related discussion](https://github.com/saadeghi/daisyui/discussions/1896):

>It's not a good idea for the navbar itself to be responsive because there are infinite ways to make a navbar depending on the content (logo, menu, buttons, dropdown, text, icons, search field...) and where to position each one (left, center, right) and how we want them to be placed on mobile. Even sometimes we need to completely restructure things on mobile (for example moving a search field from navbar to sidebar or transforming menu items from "text + icon" to "icon only"
So if I provide a few specific ways to design a navbar. it would limit the design choices completely.
Instead, we provide positioning options. You can position items at start, end, or center. Then you can decide what to show/hide on different screens using Tailwind CSS utility classes. (something like hidden lg:block to show it only on desktop. Or lg:hidden to show it only on mobile)
This is the most efficient and customizable way


So in the document site I provided a few examples to show/hide different parts. It's not hard. It's either something like `hidden lg:flex` or `lg:hidden`  
But the class names that daisyUI provide are just for positioning (left/right/center) and it's really more than a simple flex because each section can work independently and the center part always stays in the center regardless of other sections' width. So I think even though it's not providing responsive parts (because of reasons I mentioned) it's still useful.
