### ISSUE TITLE
Button with type="submit" has no background

### ISSUE THREAD

**Issue by lucasmerlin** [saadeghi/daisyui#1387]
Hi! 
a button with type="submit" loses it's background color.
I made a codepen example here: https://codepen.io/lucasmerlin/pen/VwdxmJr

I think the tailwind preflight css normalization clashes with the daisyui button here

**Comment by jboyens** [comment]
I've got the same issue. I, however, ended up working around it using tomfoolery:
```JSX
<button css={[tw`btn`, tw`btn-primary`]} type="submit">Save</button>
```

It looks to me like this is ultimately a specificity issue.

**Comment by saadeghi** [comment]
It is indeed a specificity issue but I think this only happens in CodePen using the CDN files.  
As you can see here, it works as expected when we use daisyUI as a Plugin: https://play.tailwindcss.com/Nq41QIcqRp  

The problem is daisyUI style should come after Tailwind CSS reset style.  
- If we put daisyUI CDN file after Tailwind CSS CDN file, it works well.  
- If we install daisyUI NPM package it also works well.
- But when we add a JS file and a CSS file to CodePen, we can't control which one loads first. So CodePen adds Tailwind CSS CDN file (the JS file) after daisyUI's CSS file and it ruins the specificity. 

I'm not sure if there's a way to fix this on CodePen because we really shouldn't increase the specificity of the button style. We just should make sure the component style comes **after** the reset style.

**Comment by lucasmerlin** [comment]
Ah, that was a good hint. I was having the issue in a NextJS project but I was just able to fix it by changing the order of the @tailwind directives:
Previously I had: 
```css
@tailwind components;
@tailwind base;
@tailwind utilities;
```

Putting base first fixed it: 
```css
@tailwind base;
@tailwind components;
@tailwind utilities;
```

I think when first setting up daisyui I followed the nx tailwind guide, where they have the order wrong: https://nx.dev/recipes/other/using-tailwind-css-in-react.
I'll open an issue there so they can fix the instructions.

**Comment by saadeghi** [comment]
Yes, `base` should be before `components` definitely .
