### ISSUE TITLE
How can I use 2 class toghether apply css

### ISSUE THREAD

**Issue by aryabod-kh** [saadeghi/daisyui#1393]
for ex : 
.btn-outline.btn-primary {
    --tw-text-opacity: 1;
    color: hsl(var(--p)/var(--tw-text-opacity));
}
![image](https://user-images.githubusercontent.com/84322737/204134370-10212063-e0a5-4904-8381-4f504068014d.png)

how can I apply this ?
I use 
@apply btn btn-primary btn-outline;
but the color not changes
![image](https://user-images.githubusercontent.com/84322737/204134344-5000760b-45ae-479b-816e-d4ae10af1068.png)

**Comment by saadeghi** [comment]
I wouldn't suggest using `@apply` to extend daisyUI class names in the first place.

This is how `@apply` works:  
When you use `@apply btn` it searches all available styles for the `.btn` class and it copies them for the new selector.  
When we use it for multiple class names like `@apply btn btn-primary btn-outline` again it searches the style for each individual class name. It ignores the relation between the class names tho.  
So it will ignore the `.btn-outline.btn-primary` rule that comes from daisyUI but daisyUI only applies the "primary outline" style only when an element has both class names.

I would suggest that when you're using Tailwind CSS (with or without daisyUI) just don't do component scoping, don't do extending class names with `@apply` and don't redefine class names using CSS modules. It will prevent CSS reusability. It will result a much larger CSS size because of repetitive CSS rules and It might create unwanted CSS results because `@apply` has no idea about the relation between CSS rules.  
Just simply use the class names in your HTML. It will be faster, simpler and more maintainable. Trust me.
