### ISSUE TITLE
Buttons stuck on dark mode?

### ISSUE THREAD

**Issue by WilliamBlais** [saadeghi/daisyui#14]
Hi @saadeghi,

First of all, thanks for this awesome UI library!

After upgrading from 11.5 to 14.2, I noticed that all buttons are using dark theme scheme, even in light theme. https://imgur.com/a/eqSVdoD

If this isn't a bug, how could I set the behaviour to the old one?

Thanks!

**Comment by saadeghi** [comment]
Thanks for using DaisyUI!  
There was a change in color names to improve dark themes: [read more here](https://twitter.com/Saadeghi/status/1366813950428471301)

You can see the changes [here](https://github.com/saadeghi/daisyui/commit/b968fe633338953f58982dce26c71745ecefbb83) and the new color names on the  [site](https://daisy.js.org/core/colors)

Everywhere you saw a problem on your code, you need to fix the color names. For example, instead of using `content-100` ~ `content-900`, use neutral colors and base colors.

I'm sorry about these breaking changes but it was a huge improvement for better theming.

**Comment by WilliamBlais** [comment]
@saadeghi No worries!

If I understand correctly, if I want the old behaviour back for buttons (gray buttons in light mode), I should either edit the neutral color of the theme, or add '.bg-base-200' to the button (which won't be ideal because I will also have to modify the text color).

**Comment by saadeghi** [comment]
`class="btn"` will indeed give you a *dark* gray button. It uses `neutral` color as background color and `neutral-content` for text color. If you want gray button and white text you won't need to change anything but if you want a different shade of gray or any other color, you can change the neutral colors in your theme CSS.  
Let's say you want a light gray and black text for default `btn` component. You just need to change `neutral` (n) and `neutral-focus` (nf) colors to lighter gray in your theme and `neutral-content` (--nc) to black. You won't need to add a text color class to your button.   

Please let me know if you have any questions.

**Comment by WilliamBlais** [comment]
@saadeghi Got it! Thank you so much for your detailed explanation.

**Comment by hamidkhaleghi** [comment]
Hey there @saadeghi,
If I'm getting it right, have you dropped the support of using color variants from buttons? I'm using `class="btn btn-primary"` but the primary color is not being applied on the button.

also, Thanks for the awesome library.

**Comment by saadeghi** [comment]
@hamidkhaleghi no, color variants should work. Make sure you're not using a half-string/half-variable class name: https://tailwindcss.com/docs/content-configuration#dynamic-class-names
