### ISSUE TITLE
Prettier and daisyui

### ISSUE THREAD

**Issue by nvsd** [saadeghi/daisyui#1413]
For some reason daisyui's logs are getting prepended to files by prettier on save.

I use nvim as my editor, I tried vscode and can't reproduce there.
```

[35m🌼 daisyUI components 2.42.1[0m [0m https://github.com/saadeghi/daisyui
  [32m✔︎ Including:[0m [0m base, components, themes[2], utilities

/** @type {import('tailwindcss').Config} */
module.exports = {
            content: ["./src/**/*.{js,ts,jsx,tsx}"],
            theme: {
                extend: {},
            },
            plugins: [
                require("@headlessui/tailwindcss"),
                require("@tailwindcss/forms"),
                require("daisyui"),
            ],
        };
        ```

**Comment by saadeghi** [comment]
The logs should be printed on terminal, not the file.  
I don't know how, but something seems wrong about your environment, or tools or editor config.

Maybe if you provide a sample repo and steps to reproduction, I can help...

Any way, you can safely disable daisyUI logs from the config: https://daisyui.com/docs/config/#logs

Let me know if you have any questions.

**Comment by nvsd** [comment]
Seems like I'm not the only one.
https://github.com/tailwindlabs/tailwindcss/discussions/8380

I run prettier from the cli and it also happens

**Comment by saadeghi** [comment]
I wish I could help but I really can't do anything about it because the issue is not from daisyUI.  
Basically daisyUI just has 2 lines of `console.log` to inform the user about the daisyUI version and everything that is included.  
It's `console.log` and it should be in the terminal output. I really don't understand why prettier plugin or the build tool (?) is appending them to the file content. It doesn't make sense 🤷‍♂️

And I'm not even sure if the issue is from the prettier plugin because prettier's job is to format file content not to append anything.

**Comment by rathod-sahaab** [comment]
I use `neovim` with `null-ls`

This occurs because `neovim` uses lua; hence, we cannot use prettier JS API, so formatted code is read from stdout, and daisy logs are also picked up.

```json
/** @type {import('tailwindcss').Config} */
module.exports = {
	content: ['./src/**/*.tsx'],
	theme: {
		extend: {},
	},
	plugins: [require('@tailwindcss/typography'), require('daisyui')],
	daisyui: {
		logs: false,
		themes: ['dark', 'light', 'black', 'corporate', 'garden', 'night'],
	},
}
`

Turning logs to false help, @saadeghi only thing you can do is turn logging off by default. I went to null-ls, prettier, tailwind then finally daisy UI page figuring this out took 2 hrs FML😂

**Comment by saadeghi** [comment]
@rathod-sahaab the logs are important because daisyUI applies some default style to the project even if you don't use any component class names (for example themes and foreground+background colors for the whole page). So if someone just adds the plugin it should be obvious for them that daisyUI styles are applied for them. And since daisyUI works on build time, that console log is the only way of communicating with the developer.  

So, I don't think disabling it by default would be a good idea. Especially when the majority of developers have no issue about it.  

I think if the formatted code is read from stdout (as you mentioned) that's just a super lazy solution form the developers of that tool. And it will create further problems as well. For example, Tailwind CSS itself shows warnings on the console log if there's a change on their API and you're still using a deprecated one. That warning and any other console log belongs to terminal. not the file output.

**Comment by szachy113** [comment]
I'm facing the same problem. I resolved it by disabling the logs. I don't see any other feasible solution. Thanks for bringing this up, @nvsd!

**Comment by TheodorRene** [comment]
Just chiming in to say that this was a big issue for me as well when using Neovim, Neoformat and Prettier. It just broke formatting for me. Any tool that use the prettier CLI will break because the info will be added on the top when outputting the formatted code to stdout. Will disable the logs for now.

**Comment by joekrall** [comment]
I've had success using `prettierd` with [`conform.nvim`](https://github.com/stevearc/conform.nvim), installed with Mason. The logs are not prepended as `prettierd` runs a server. As a project, it looks unmaintained right now.
