### ISSUE TITLE
Fix colour contrast errors

### ISSUE THREAD

**Issue by kudadam** [saadeghi/daisyui#1415]
Hi, 
I was browsing a site which uses DaisyUI and I realized some colour contrast errors on the site. I decided to contact the dev and he says the problem was from this library so am just informing you guys if you could work on it as it would increase readability

**Comment by saadeghi** [comment]
daisyUI is just a library that provides tools for creating a UI. It gives developers components, colors, etc... but the way developers use these pieces to make a page is not something we can control. For example, the `primary` button from daisyUI has a background color and text color by default and it passes [an accessibility test](https://github.com/saadeghi/daisyui/blob/master/src/tests/a11y.test.js) to make sure it has a readable contrast but all colors and themes are customizable. developers literally can change the colors as they want and make an unreadable text.  

If a website is made using daisyUI I can not guarantee that it has a good UI/UX at all because at the end it's up to the developer how to use the library. In an ideal scenario, for creating a good page, developers are needed to have a basic knowledge about design so they know where to place elements or how to make a layout. They also need to have a basic knowledge about colors and accessibility so they how and when to use a color.

**Comment by kudadam** [comment]
Oh, alright. Thanks for the info
