### ISSUE TITLE
Could you please provide js imported cdn like tailwindcss3 to reduce the file size?

### ISSUE THREAD

**Issue by aoaostar** [saadeghi/daisyui#1422]
Hello, the file full.css introduced by cdn is too big, about 1.47MB+. Could you please provide js imported cdn like tailwindcss3 to reduce the file size?
My project requires all components, and npm on-demand import isn't for me to use.
Thanks a lot.
![image](https://user-images.githubusercontent.com/86001674/206618814-591c62a2-25fe-4d33-ab1b-68802040b6a7.png)

**Comment by saadeghi** [comment]
Currently I have no plans for creating that because CDN files (even Tailwind's CDN script) are not for production.  
Even if you're using every possible daisyUI class name (which I doubt), it still costs less to ship a CSS file to the browser than a JS file.  

1MB of JS is not equal to 1MB of CSS.  
Both CSS and JS have a `network cost`: the time it takes to download a file  
But JS, on top of a `network cost` also has `parse and compile cost` + `execution cost` + `memory cost`  

That's why Tailwind's team also wouldn't recommend using their CDN file for production even though the JS file size is just ~100kb

I would suggest to build both Tailwind CSS and daisyUI on build time. If you want to make sure a specific list of class names are included, whitelist them  
And if you really need all class names, you can either whitelist all daisyUI class names (read https://github.com/saadeghi/daisyui/issues/1383) or you can simply import `daisyui/dist/full.css` file to your project from your `node_modules`

Let me know if you have any questions.
