### ISSUE TITLE
swap issue

### ISSUE THREAD

**Issue by FLasH3r** [saadeghi/daisyui#1431]
`@tailwindcss/forms` is causing this issue - maybe state this in the docs?

swap checkbox is visible
 
 package.json
 ```json
"tailwindcss": "^3.2.4"
"@tailwindcss/forms": "^0.4.1",
"@tailwindcss/typography": "^0.5.7",
"daisyui": "^2.42.1",
```

in build:
```
🌼 daisyUI components 2.43.0  https://daisyui.com
  ✔︎ Including:  base, components, 2 themes, utilities
  ❤︎ Support daisyUI:  https://opencollective.com/daisyui 
  ```

tailwind.config.js
 ```javascript
 plugins: [
    require('@tailwindcss/forms'),
    require("@tailwindcss/typography"),
    require("daisyui")
  ],
  daisyui: {
    themes: ["fantasy","dark"],
  },
  ```

![image](https://user-images.githubusercontent.com/1413249/207197221-e6a16f0c-996e-4c92-9f98-4af2a91af414.png)
![image](https://user-images.githubusercontent.com/1413249/207198017-c7abf8f0-2faa-425c-87cf-36788484d880.png)

![image](https://user-images.githubusercontent.com/1413249/207197581-6c49489d-9b0f-4284-8267-40e7e8f54baf.png)

![image](https://user-images.githubusercontent.com/1413249/207197665-1a61f352-2143-4d82-a741-0450b67621e8.png)

![image](https://user-images.githubusercontent.com/1413249/207197701-50b71cab-a921-48a6-8e6c-e13682f7ad3d.png)

![image](https://user-images.githubusercontent.com/1413249/207197744-791b03d7-adc5-4ed0-a632-d7bc9fd7fd23.png)

**Comment by saadeghi** [comment]
What `@tailwindcss/forms` does is precisely described [in its repo](https://github.com/tailwindlabs/tailwindcss-forms):
>**All of the basic form elements you use** will now have some simple default styles that are easy to override with utilities.

So when we install a plugin that says it applies style to all form elements by default, we can't expect otherwise.  
This is not an issue. `@tailwindcss/forms` is simply doing its job.  

If you really need `@tailwindcss/forms` alongside with daisyUI (which I doubt because both are doing the same job) consider using its [`strategy: 'class'` config](https://github.com/tailwindlabs/tailwindcss-forms#using-only-global-styles-or-only-classes) so it only applies style to the elements with specific class name (not all form elements)

Let me know if you have any questions.

**Comment by aimehai** [comment]
![image](https://github.com/saadeghi/daisyui/assets/125627850/23d6f27f-d38d-463b-b59e-30658b04b813)
![image](https://github.com/saadeghi/daisyui/assets/125627850/2a8ef392-10f4-49bf-8b0b-833a2739d352)
I still have this problem

**Comment by saadeghi** [comment]
@aimehai Flowbite has a same class name `.toggle` as daisyUI's `.toggle` so using them together will mix the styles.  
To avoid that when using daisyUI and Flowbite together you may want to [add a prefix](https://daisyui.com/docs/config/) to only daisyUI class names. This avoids mixing the styles with the same class name coming from other CSS libraries.
