### ISSUE TITLE
Theme colors are not applied correctly

### ISSUE THREAD

**Issue by robin-thoene** [saadeghi/daisyui#1435]
When I override my selected themes (light / dark) from daisyui and set my CI primary color and inspecting the result in the browser (for example, the daisyui primary button) the color is not the same. 

See sample:
![image](https://user-images.githubusercontent.com/110201991/207617527-79c3aaf0-6a3e-4167-ba14-b728939ac577.png)

How do I manage to see the same HEX color in the UI as defined in my theme?
The color difference can be verified using color picker and also using the Chrome dev tools.

**Comment by robin-thoene** [comment]
Turns out that the color my stakeholder provided was not converting from hex to hsl and back consistently. I think it is an color issue and have nothing to do with daisyui, since I found other colors online and with them everything worked as expected.

**Comment by saadeghi** [comment]
It should work correctly 🤔  
daisyUI is using this library to change color formats and in my experience, it's accurate:  
https://www.npmjs.com/package/color

Can you give me your color palette so I can test?

**Comment by robin-thoene** [comment]
I just dived into it and saw that daisyui is converting to HSL. After that I tested my HEX '#314EF3' by putting it into an HSL converter, than took the HSL and converted it back to HEX using the same tool. The HEX at the end was different from my original. So there is nothing wrong with daisy, but with the color of my stakeholder.

I think there is no need for further investigation.

**Comment by saadeghi** [comment]
The reason that you're seeing a different Hex code is because the decimals in hex values are being rounded.  
Here are the exact numbers:
```
#314EF3 => hsl(231,89%,57.3%)
#2F4DF3 => hsl(230.8,89.1%,56.9%)
```
As you can see, the difference is so low and in my opinion, it's safe to say they are the same colors. It's impossible to distinguish them from each other.

<img width="400" alt="2" src="https://user-images.githubusercontent.com/7342023/207858691-608ceb6b-31bb-4b8e-8e8d-ebc68d2fadd6.png">
<img width="403" alt="1" src="https://user-images.githubusercontent.com/7342023/207858697-d2399968-40ef-40c2-894e-6284749498c2.png">
