### ISSUE TITLE
button groups containing buttons with indicators are broken

### ISSUE THREAD

**Issue by gaultierq** [saadeghi/daisyui#1467]
`.btn:not(:first-child):not(:last-child) {` will not work as `.btn` will be wrapped in a `.indicator`

**Comment by saadeghi** [comment]
This is challenging because `btn-group` selects all the buttons inside and sets their `border-radius` accordingly. but since indicator is adding a parent element (and there's no other way for it to handle this style).

For now you can set the `btn` class to the `indicator` itself to make it look as expected:
```diff
- <div class="indicator">
+ <div class="indicator btn">
   <span class="indicator-item badge badge-secondary">99+</span> 
-  <button class="btn>inbox</button>
+  <button>inbox</button>
</div>
```

I will try to find a way to avoid issues like this...

**Comment by saadeghi** [comment]
What do you think about this idea: https://github.com/saadeghi/daisyui/discussions/1572
