### ISSUE TITLE
Feature request: Collapsible/Expandable table

### ISSUE THREAD

**Issue by MathieuAndrade** [saadeghi/daisyui#1489]
Actual Collapse element cannot be used in combination with table 😕 

Exemples: 
https://mui.com/material-ui/react-table/#collapsible-table
https://codepen.io/pc3b3r/pen/vLxONL?editors=1010

**Comment by cuongn265** [comment]
Do we have any update on this?

**Comment by saadeghi** [comment]
We have to wait for the next major version (`3.0`) because this will be a breaking change. I'm working on it

**Comment by saadeghi** [comment]
Unfortunately there is no good way to do this using CSS only.  
A possible way to do this is using a hidden checkbox but the checkbox should be positioned before the hidden row so we can show the hidden row when the checkbox is checked. Then we can use a label inside the previous row to check/uncheck the checkbox. But this is a bad idea inside the table because the only valid element inside `<table>` is a `<tr>` and if the checkbox is not a sibling of the hidden row, we can't select it using CSS.  
It would be possible with CSS `has()` but CSS `has()` is not supported by FireFox yet.  

Maybe a few months from now, when the browser support gets better, we can have this with pure CSS.  
Until then, use JS to hide and show a table row
