### ISSUE TITLE
Does unused styles from the plugin get purged

### ISSUE THREAD

**Issue by kaushalyap** [saadeghi/daisyui#150]
Awesome work.!

I would like to know if the unused styles from plugin get purged with typical purge config like below

` purge: ['./src/**/*.{js,jsx,ts,tsx}'],`

or [should we set purge mode to all](https://tailwindcss.com/docs/optimizing-for-production#removing-all-unused-styles) and manually provide paths

**Comment by saadeghi** [comment]
@kaushalyap yes it will get purged just like other tailwind styles. No config needed.

**Comment by T-Alkathiri** [comment]
Thank you.

**Comment by kaushalyap** [comment]
@saadeghi  Thanks for reply, glad to know manual config is not necessary.


Another question Read me say it is 2KB when gzipped but [bundlephobia say 31.7KB gzipped.](https://bundlephobia.com/package/daisyui@1.13.2) which is correct? 2 KB vs 31.7KB

**Comment by saadeghi** [comment]
@kaushalyap Bundlephobia calculates the whole package, including [all css and js files](https://unpkg.com/browse/daisyui@1.13.2/) in the package.

**Comment by kaushalyap** [comment]
@saadeghi I am aware of it.

Sometimes bundlephobia calculations are not accurate [see tailwindcss](https://bundlephobia.com/package/tailwindcss@2.2.7) for example

My question is how many KBs added to the bundle by `daisyui`?

**Comment by saadeghi** [comment]
@kaushalyap 31KB. but I think I should remove that Bundlephobia badge because what actually matters is the size of CSS when it's added as a Tailwind CSS plugin and that CSS gets purged for production.  
So in reality it doesn't matter that [tailwind.min.css](https://unpkg.com/browse/tailwindcss@2.2.7/dist/) is 2.93MB or daisyUI's [styled.css](https://unpkg.com/browse/daisyui@1.13.2/dist/) is 89.7KB because they all get purged in production.

**Comment by kaushalyap** [comment]
@saadeghi I think you may remove the bundlephobia badge, since it seems like unreliable tool as I showed in the tailwindcss case. You may also add a note under the 2KB point in the README about purging of unused CSS.
