### ISSUE TITLE
Modal | any option to render it deeply inside but have it a global modal?

### ISSUE THREAD

**Issue by talksik** [saadeghi/daisyui#1500]
For the most common use cases, modals should appear in the center of the screen and darken out the entire background. Currently, daisyui has modals open within the scope of the parent container.

Is there some option to make it global so to speak? Or would I have to send state back up the tree and then render it way at the top of the tree?

Thank you?

**Comment by fini** [comment]
Could you provide more info, describing your issue. For me it works exactly as you first describe: Appears centered in the window and the entire background is dimmed.

**Comment by saadeghi** [comment]
You can put the modal deep inside your HTML tags but there's a high chance it may cause positioning problems. Because the modal is fixed in the center of the page and we want it that way but if any off the parent elements is positioned relatively, or if there are grids, flexboxes, etc... They will affect the positioning of the child element.

So it's suggested for the modal box to be placed outside any container element in the root of the page. This is basically how every JS modal plugin works too but they add or remove the element on demand. daisyUI is a CSS-only solution but you can add or remove the modal box or change its content using JS the way you want.


Let me know if you have any questions
