### ISSUE TITLE
Feature Request: Simpler Inputs

### ISSUE THREAD

**Issue by danielniccoli** [saadeghi/daisyui#1502]
I think inputs can be simplified. What takes this amount of code:

```html
<div class="form-control w-full max-w-xs">
  <label class="label">
    <span class="label-text">What is your name?</span>
    <span class="label-text-alt">Alt label</span>
  </label>
  <input type="text" placeholder="Type here" class="input input-bordered input-primary w-full max-w-xs" />
  <label class="label">
    <span class="label-text-alt">Alt label</span>
    <span class="label-text-alt">Alt label</span>
  </label>
</div>
```

Can really be condensed to

```html
<div class="form-control">
  <label for="input1">What is your name?</label>
  <label for="input1">Alt Label</label>
  <input id="input1" type="text" placeholder="Type here" class="border border-sky-500" />
</div>
```

- A `label` does not need a class `.label`. Default style can be applied to the `label` element.
- It is not necessary to nest `span` within `label`. Any formatting can be done through the class attribute of `label`.
- The alternative labels could be identified by the nth-child selector. Where the first label would always be the primary and all others would be alternative labels.
- The positioning of the label attribute could be managed with an additional class `<label for="input1" class="label-pos-{pos}">What is your name?</label>`, where `{pos}` would be `tl | tr | bl | br`.
- An `input` does not need a class `.input`. Default style can be applied to the `input` element with the help of the `type=` attribute.
- When you want to apply a border, instead of `.input-bordered.input-primary` you could just apply `.input-primary` and it still works. Maybe just remove the superflous `.input-bordered`?

Last but not least, maybe even the `.form-control` could be removed and labels and groups would be grouped together via the `for=` attribute. If something like that would even be possible.

**Comment by saadeghi** [comment]
Thank you for the issue.

I totally agree that it can be simpler. But the goal is not just having simpler code. we need to provide a good balance between simplicity and flexibility. and also we don't want to force design decisions so it should be possible to opt-out of daisyUI's design anywhere on the page. Sometimes people just need to use Tailwind CSS utility classes or custom CSS for a specific element instead of the design daisyUI provides.

The goal is providing class names, as simple and as flexible to make any common UI pattern.


> * A `label` does not need a class `.label`. Default style can be applied to the `label` element.
It really needs to be a class name. because a `<label>` can be used for other things. It's a valid code if we put the `<input>` inside the `<label>` and many people do this instead of using `<label for="ID">`.  
Also there may be other labels inside the `form-control` to do anything else. for example to control a checkbox, etc...  
What the class name `.label` is made for is not exactly what a `<label>` tag can be used for. the class name `.label` is just for a visual text we can use to describe the input.

> * It is not necessary to nest `span` within `label`. Any formatting can be done through the class attribute of `label`.
It's not necessary but we should consider different ways people can visually assign a descriptive text to an input. All the positions (top-right/top-left/bottom-right/bottom-left) are common places in UI design to put a descriptive text or helper text for an input.

> * The alternative labels could be identified by the nth-child selector. Where the first label would always be the primary and all others would be alternative labels.
Well, I can never know which one is the alternative. Maybe the title of the input is top-left. maybe it's bottom-left. maybe a helper link (like "forgot password?") is on the bottom right. maybe it's bottom left. I don't want to force people to use a very opinionated design. I just want to give them the tool and they can use it however they UI needs to be.

> * The positioning of the label attribute could be managed with an additional class `<label for="input1" class="label-pos-{pos}">What is your name?</label>`, where `{pos}` would be `tl | tr | bl | br`.
That's an interesting idea. I will think about it.

> * An `input` does not need a class `.input`. Default style can be applied to the `input` element with the help of the `type=` attribute.
Again, we never know what an input is for. It can be anything. it can be hidden input. it can be a checkbox. anything...  
daisyUI works with classnames. it doesn't apply styles to elements by default. This way, people can use a style for an element only when they want it. Otherwise they can use a custom style or the can use Tailwind CSS classes for an element on the page.

> * When you want to apply a border, instead of `.input-bordered.input-primary` you could just apply `.input-primary` and it still works. Maybe just remove the superflous `.input-bordered`?
You're right.

> Last but not least, maybe even the `.form-control` could be removed and labels and groups would be grouped together via the `for=` attribute. If something like that would even be possible.
Again, the goal is not to style everything by default. only if people use that `form-control` class, it means they're committed to have the flex layout and all the positioning daisyUI is suggesting. Otherwise they can use their own order of elements with a custom positioning and just use the `input` class for the text input. We're not forcing anything.

Let me know if you have any questions.
