### ISSUE TITLE
select-ghost has background when activated

### ISSUE THREAD

**Issue by pheianox** [saadeghi/daisyui#1513]
https://user-images.githubusercontent.com/77569421/211764987-0b136971-7d48-4506-8936-42e762d77b78.mp4

is this design or bug? also can I disable that somehow, i know it's gonna look ugly :)

**Comment by saadeghi** [comment]
It is intentional. I think it makes sense for it to have a background when it's focused. This way it's more obvious.  
It's an opinionated design and it's based on [the way text input looks](https://daisyui.com/components/input/#ghost-no-background)

You can use `focus:bg-transparent` to remove the background color:
```html
<select class="select select-ghost focus:bg-transparent">
```
https://play.tailwindcss.com/9afXRviAiX
