### ISSUE TITLE
Unable to focus elements: swap, modal button, etc

### ISSUE THREAD

**Issue by TicTak21** [saadeghi/daisyui#1514]
It seems like some elements can't be focused or pressed after using `Tab`.

For example [swap icons with rotate effect](https://daisyui.com/components/swap/#swap-icons-with-rotate-effect). Yes, it is possible to focus this button, but I can't press it using `Enter`. I understand this is related to the `label` usage in the implementation. But I wonder if it is possible to update/change the implementation so users could use this in a more accessible way?

I'm having a similar issue with the [modal open button](https://daisyui.com/components/modal/#modal-using-label--hidden-checkbox). But in this case I can't even focus button because it is skipped.

https://user-images.githubusercontent.com/44474697/211785803-959d2f1f-1b8f-4869-af44-79a86ce4c507.mov

Thank you.

**Comment by amirsinaa** [comment]
Hey @TicTak21,
The problem here is not `daisyui` related in fact the real cause of this is that the `<label>` element is not focusable via the `tab` key so therefore `swap` and `modal` components or any other components that use a `<label>` element for triggering some action or effect it's not focusable with tab key and the below code won't be viewable by user : 
`
    element:focus-visible {
      outline: 2px solid whatEverColor;
    }
`

One workaround that I could think of but it's not recommended because of markup best practices violations is that wrap your label with a `<button>` : 

`
<button class="btn btn-primary relative">
  <label class="w-full h-full absolute hover:cursor-pointer" for="my-modal"></label>
  open modal
</button>
<input type="checkbox" id="my-modal" class="modal-toggle" />
<div class="modal modal-primary">
  <div class="modal-box">
    <h3 class="font-bold text-lg">Congratulations random Internet user!</h3>
    <p class="py-4">You've been selected for a chance to get one year of subscription to use Wikipedia for free!</p>
    <div class="modal-action"><label for="my-modal" class="btn">Yay!</label></div>
  </div>
</div>
`

demo: https://play.tailwindcss.com/9j31fPjr7W

**Comment by TicTak21** [comment]
Thank you for your response.
It appears that even when the button is focused, users are unable to use the "Enter" or "Space" keys to open the modal.
Nonetheless, I have decided to use an anchor modal as it is more user-friendly.
