### ISSUE TITLE
Redo dark mode

### ISSUE THREAD

**Issue by DanDev95** [saadeghi/daisyui#152]
Please redo the dark mode, or add a new darkmode that actually looks more like the standard darkmode on websites. This one is too light (almost like silver) and doesn't really look like a true dark mode.

**Comment by saadeghi** [comment]
@DanDev95 I prefer not to change the colors of themes because they are currently being used on many projects.  
But you can add your own themes, which means you can have the same `dark` theme with the colors you want. See this example: https://play.tailwindcss.com/as5ew5YnXr?file=config

Please let me know if you have any questions
