### ISSUE TITLE
Drawer is limited to only 1 per layout

### ISSUE THREAD

**Issue by timothymarois** [saadeghi/daisyui#1524]
Looks like the drawer is limited to 1 drawer for your layout. You can't create multiple. If you want to use it as the app menu nav, that fine. But if you want to use it as a way like some management systems use for modals, you cant create multiple instances of different drawers, this feature is a lot more powerful if it could be used for multiple instances.

**Comment by saadeghi** [comment]
It's not limited to 1 per layout. You can use multiple drawers in a page. See this discussion:  
https://github.com/saadeghi/daisyui/discussions/709  

But since this is not a JS plugin, daisyUI can't create or delete DOM elements on the go. It's a CSS only solution so it should be a container with a checkbox so we can styles inside the `.drawer` based on the checkbox value. So if we want a second drawer, we should put it inside the `drawer-content` of the first one.   
The HTML code would be more confusing if we put multiple drawers inside each other tho. So I would suggest that if you have different content to show in a drawer sidebar, just use 1 drawer and change the content using JS dynamically.

Another option would be using a JS plugin for an off-canvas drawer sidebar because JS can create or delete DOM elements on demand.

Let me know if you have any question.
