### ISSUE TITLE
Modal-open not working

### ISSUE THREAD

**Issue by konsumer** [saadeghi/daisyui#1546]
I am using windicss in vite, with this in my tailwind.config:

```js
export default {
  content: ['node_modules/daisyui/dist/**/*.js', 'node_modules/react-daisyui/dist/**/*.js', 'src/**/*.jsx']
}
```

Here is my windi.config:

```js
import { defineConfig, transform } from 'windicss/helpers'

export default defineConfig({
  darkMode: 'media',
  plugins: [
    transform('daisyui')
  ]
})
```

This source does not show a model:

```js
<div className='modal modal-open'>
          <div className='modal-box'>
            <h3 className='font-bold text-lg'>TITLE</h3>
            <div className='py-4'>
             CONTENT HERE
            </div>
            <div className='modal-action'>
              <label className='btn'>Cancel</label>
              <label className='btn btn-primary'>OK</label>
            </div>
          </div>
        </div>
```

I cannot manage the visibility, other than using a checkbox.

**Comment by saadeghi** [comment]
I think this is a problem with Windi's transform plugin. "transform" is not really stable for converting Tailwind CSS plugins and it creates inaccurate CSS rules.  
And since the Windi project is not being maintained anymore I can't be optimistic that this will be fixed so I can suggest to use Tailwind CSS instead of Windi.

Let me know if you have any questions.
