### ISSUE TITLE
[Suggestion] Link :after clarity icon 

### ISSUE THREAD

**Issue by rortan134** [saadeghi/daisyui#1548]
I suggest adding another utility class to add more relevance for the main link class, something like a `link-icon` modifier, and it'd add an icon for specifying if the link will open another external tab.

![image](https://user-images.githubusercontent.com/37253958/213871917-1d7e967d-ad5f-4faf-bfeb-deee2e177d2e.png)

Due to increased accessibility, this is commonly used on production sites.
I'd be happy to open a PR for it.

**Comment by saadeghi** [comment]
Well you can simply put a svg icon after the link text and it works. See the footer links on daisyUI website for example.  
I'm not sure how a new `link-icon` class name can do anything additional.

**Comment by rortan134** [comment]
I think DaisyUI should aim for ease-of-use features and sparing the developer some valuable time. Having something as simple as this without having to manually add an SVG icon helps raise overall UI standards and the general relevance of the `link` class, since in my opinion it's one of the least useful classes 🤷‍♂️

**Comment by saadeghi** [comment]
I agree that daisyUI should aim for ease of use. But I really don't want it cross lines with icon libraries. daisyUI components are opinionated to some degree and there are design decisions but I think it's better to let the developer use their own icons wherever needed.  
Currently the only places daisyUI injects an icon is on [`collapse`](https://daisyui.com/components/collapse/), [`select`](https://daisyui.com/components/select/) and [`breadcrumbs`](https://daisyui.com/components/breadcrumbs/). Simply because they needed a few generic icons and it would be so hard to make put SVG icons inside them. But we should draw a line somewhere.  

The `link` class may not be so useful on every project because it only applies a pointer cursor and underline but when working with a a large amount of text content, simply adding a `link` class. It also provides opportunity to apply other custom styles to the link on the theme level.

Let me know if you have any questions.
