### ISSUE TITLE
bug: css does not work with npm install but works with cdn link. i am working in vite + react project

### ISSUE THREAD

**Issue by shufolislam1** [saadeghi/daisyui#1554]
### What version of daisyUI are you using?

2.47.0

### Describe your issue

I am working on a project with vite + react where css of daisy ui is not working with npm install. But after adding cdn in html file, it works fine. I am sure that i'm using latest version of tailwind css upto 3.0 and 2.47.0 version of daisy ui. What's the problem? why css is not working? I am including my github repo of the project.

### What browsers are you seeing the problem on?

Chrome

### Reproduction URL (optional)

https://github.com/shufolislam1/eduWeb

**Comment by saadeghi** [comment]
I can't see your project on GitHub. Is it a public project?  

Also, make sure that [the `content` object on your `tailwind.config.js` file](https://tailwindcss.com/docs/content-configuration) is including the path to all your markup files. Otherwise, Tailwind CSS can't generate styles for the class names you used.

**Comment by shufolislam1** [comment]
> I can't see your project on GitHub. Is it a public project?
> 
> Also, make sure that [the `content` object on your `tailwind.config.js` file](https://tailwindcss.com/docs/content-configuration) is including the path to all your markup files. Otherwise, Tailwind CSS can't generate styles for the class names you used.

ok. Bug fixed. Thank you. Actually, my tailwind css was having some problems. Issue fixed.
