### ISSUE TITLE
bug: checkbox-neutral doesn't work

### ISSUE THREAD

**Issue by drftls** [saadeghi/daisyui#1555]
### What version of daisyUI are you using?

v2.47.0

### Describe your issue

Greetings. Thank you for sharing Daisy UI with us!

`class="checkbox checkbox-neutral"` does not use the neutral color from mytheme in tailwind.config.js. 

Perhaps this is intentional. I just wanted to let you know.

### What browsers are you seeing the problem on?

Edge

### Reproduction URL (optional)

https://play.tailwindcss.com/BYWXpNUVrQ

**Comment by saadeghi** [comment]
The `checkbox-neutral` class does not exist. and It's not even [on the docs](https://daisyui.com/components/checkbox/) so it wouldn't do anything...  
The default `checkbox` class uses [`base-content` color](https://daisyui.com/docs/colors/).  

The reason we don't have a `neutral` color for the checkbox, toggle, radio, etc... is that the `neutral` color is expected to be a dark shade on both dark and light themes. And if we use a dark checkbox on dark theme, it wouldn't be visible enough.  
  
The reason we have a `neutral` color in the first place is that on a light theme it's okay to have a high contrast dark section on a light background but on a dark theme, it's not okay to have big bright color on a dark background. So there should another color name that we can safely use it on both dark and light themes, it shouldn't be a vivid color like `primary`, `secondary` etc. and it should be a low-brightness color. It's called `neutral` color on daisyUI.

Not all daisyUI color names are available for all components because components are based on a design system and the goal is only provide color choices that will be accessible on all themes.

About your code example, If your'e making a new theme you should define all required color names for your theme:
```
primary
secondary
accent
neutral
base-100
```
See this table for more info: https://daisyui.com/docs/colors/  
Or use this theme generator: https://daisyui.com/theme-generator/

Let me know if you have any questions
