### ISSUE TITLE
bug: Daisy collapse doesn't play with @tailwindcss/forms

### ISSUE THREAD

**Issue by LeviticusMaximus** [saadeghi/daisyui#1581]
### What version of daisyUI are you using?

v2.46.1

### Describe your issue

In a Vue3/Vite app

I'm using a collapse element from Daisy to show/hide content.

I've now installed @tailwindcss/forms but I'm finding that the open/close by clicking on the collapse-title element no longer does its job. 

I'm guessing that tailwindcss is changing the Daisy behaviour for checkboxes so that the Collapse functionality gets broken.

I could possibly pass a daisy-prefix using the config option, but not sure how I can apply it to the input type=checkbox (if that's what's causing the problem?)

Anyone, can you help me? 

Would be much appreciated.

Thanks

### What browsers are you seeing the problem on?

Chrome

### Reproduction URL (optional)

https://play.tailwindcss.com/Q5aLXVr7ej

**Comment by saadeghi** [comment]
You should know that `@tailwindcss/forms` by default, applies opinionated styles to _all form elements_ on the page. This will cause conflicts with daisyUI or any other UI library you might want to use.  

You can change this behavior by changing [the `strategy` config](https://github.com/tailwindlabs/tailwindcss-forms#using-only-global-styles-or-only-classes) to `class` so Forms plugin only applies styles when you use [their class name](https://github.com/tailwindlabs/tailwindcss-forms#using-classes-to-style) (for example `form-input`)

And generally I don't think you would need both daisyUI and `@tailwindcss/forms` on the same project because they both do the same job on styling form elements.

**Comment by LeviticusMaximus** [comment]
Thanks, that's great and really helpful.

I agree that I wouldn't usually need to use both libraries but I've been asked to use a component supplied by a third party in tailwindUI so I was constrained to using it for brevity.

Many thanks again for your quick response, hard work and helpfulness.
