### ISSUE TITLE
bug: Dynamically setting colour properties sometimes doesn't work

### ISSUE THREAD

**Issue by SkepticMystic** [saadeghi/daisyui#1596]
### What version of daisyUI are you using?

2.49.0

### Describe your issue

I have a component which takes in a diasyui colour utility name. e.g. `primary`, `warning`, or `success`.
I then style the component using the colour passed in, for example:

```svelte
<div class='bg-{colour}'>Test</div>
```

The issue is, this sometimes works, and sometimes doesn't. Sometimes the correct colour is applied, and sometimes it just isn't 🤷🏼 
When checking the built HTML, the class is correct - there is a `div.bg-warning`, for example.

The work around I have is to use a sort of switch statement on every possibility:

```svelte
<div 
    class:bg-primary={colour === 'primary'}
    class:bg-warning={colour === 'warning'}
    class:bg-success={colour === 'success'}
>Test</div>
```

This option works, the colours are applied correctly.

### What browsers are you seeing the problem on?

Chrome, Other

**Comment by saadeghi** [comment]
Tailwind CSS class names should not be half-variable/half-string like `bg-{colour}`  
Because this way when Tailwind CSS searches your markup files it can't find the class name. Somewhere in your files the class name should exist as a whole string (like `bg-primary` or `bg-red-600` or anything)  
Read more: https://tailwindcss.com/docs/content-configuration#dynamic-class-names


You can also [safelist](https://tailwindcss.com/docs/content-configuration#safelisting-classes) the needed class names if you really have to use them as half-variables.

I think the reason that it's working sometimes is either the whole class name string exists in another file as well or you're running the dev build. On the dev build when you only remove a class name it doesn't get removed. It only adds new class names or replace them because it's faster for dev environment.

Let me know if you have any questions

**Comment by SkepticMystic** [comment]
Thanks for the quick and interesting response!
This makes sense, I'll make some changes on my side.
