### ISSUE TITLE
docs: Code examples on the homepage use wrong markup

### ISSUE THREAD

**Issue by matuzo** [saadeghi/daisyui#1597]
### On which page do you see this issue?

https://daisyui.com/

### Describe the issue

Hey,

the code samples on the homepage are all showing the usage of inaccessible markup. Given the popularity of this project, this should be fixed because someone might following these examples. I'd be happy to create a PR if you're open to implementing the changes.

```html
<a class="btn btn-primary">Button</a>
```

This is neither a button nor a hyperlink. It's “placeholder link” which is not accessible via keyboard. The demo should either show a `<button>` or at least `<a>` with `href`.  

```html
<input type="checkbox" class="toggle"/>
```

The toggle has no accessible name and should be labelled.

```html
<ul class="menu p-3 bg-base-200 rounded-xl">
    <li class="menu-title">
      <span>Menu Title</span>
    </li>
    <li><a>First Menu Item</a></li>
    <li><a>Second Menu Item</a></li>
    <li><a>Third Menu Item</a></li>
  </ul>
````

Again placeholder links, and “Menu Title" shouldn't be part of the list if it's not a option but a heading or some kind of other label.

Please give me a quick thumbs up if you're interesting in these changes and I'll create a PR.

Thank you,
Manuel

### What browsers are you seeing the problem on?

Chrome, Safari, Firefox, Edge, Other

**Comment by saadeghi** [comment]
I think there's a misunderstanding here because daisyUI is just a CSS library and everything on the docs only shows how to use the CSS class names.

>the code samples on the homepage are all showing the usage of inaccessible markup
I understand your point but as you said it's not a link.  
It's not and a link. It shouldn't do anything so why should it be accessible via keyboard when It's just a demo to show people how to use a class name?  

Let's say someone copies `<a class="btn btn-primary">Button</a>` to their project. Yes it's inaccessible code. But either if it's a link or button or anything, it won't do anything without context anyway. If I write `<button class="btn btn-primary">Button</button>` on daisyUI homepage, that's technically accessible markup but it still doesn't do anything. because context and functionality is up to the developer. either if it's a button or a link, developer should write some code for it to work.

If you think it would be helpful to replace `<a class="btn btn-primary">Button</a>` with `<button class="btn btn-primary">Button</button>` make a PR and I will merge it but I don't think it would be helpful to anyone. The point here is the class name... 

>The toggle has no accessible name and should be labelled.
Of course. In a real project. but there are multiple ways to use a HTML label (input inside label, input next to label with an ID) or even input in another node with an ID pointing to the input) daisyUI docs shows you how to use the class name. It's up to the developer how to use it. For example if I show an example with `label` and `input` with an ID to connect them, developers will assume this is the only way daisyUI style works. which is not true. daisyUI style works when you add the class name. and the docs should only show how to use the class name.  

>Again placeholder links, and “Menu Title" shouldn't be part of the list if it's not a option but a heading or some kind of other label. I don't think list items should be necessarily clickable or being an option. It's an unordered list and it can include links or text or anything. This is valid HTML. The HTML specification has nothing for caption of a `<ul>` (unless we use other elements for it like `<figure>` and `<figcaption>` but it feels weird to put `<ul>` inside a `<figure>` and I never seen someone do that) so I think it's okay to put the title of the list as the first list item.

Let me know what you think. I am willing to do anything for improvement but I really don't want to dictate people how to write code. I can only show them how to use a class name.

**Comment by matuzo** [comment]
> make a PR and I will merge it

Awesome, thank you. I should find some time next week!
