### ISSUE TITLE
bug: user-select css should also use -webkit-user-select for Safari

### ISSUE THREAD

**Issue by computeronix** [saadeghi/daisyui#1637]
### What version of daisyUI are you using?

2.51.0

### Describe your issue

In the CSS code generated by daisyui the browser suggests and provides an error saying you also need to use -webkit-user-select for Safari users (desktop and iOS), when using user-select

Is this a known bug or a way to add this code?

Let me know any other information needed

### What browsers are you seeing the problem on?

Edge

**Comment by saadeghi** [comment]
If you're using Tailwind CSS CLI, the prefixes will be generated.  
If you're using PostCSS, you need to install [`autoprefixer`](https://github.com/postcss/autoprefixer) which is also [suggested by Tailwind CSS docs](https://tailwindcss.com/docs/installation/using-postcss)

If you already installed `autoprefixer` and you have it inside your `postcss.config.js` file and prefixes like `-webkit-user-select` are not getting generated, it might be because of your [`browserlist`](https://github.com/browserslist/browserslist) config (if you have that config file) which specifies which browsers should be considered for prefixes to generate.

Let me know if you ahve any questions.
