### ISSUE TITLE
bug: accessibility problems with modal

### ISSUE THREAD

**Issue by renanbrayner** [saadeghi/daisyui#1662]
### What version of daisyUI are you using?

2.51.3

### Describe your issue

The user can't close the modal pressing `esc` and he can still navigate outside of the modal pressing `tab`.

### What browsers are you seeing the problem on?

Chrome, Firefox, Other

### Reproduction URL (optional)

[your own documentation has this problem](https://daisyui.com/components/modal/#)

**Comment by saadeghi** [comment]
daisyUI is a CSS file. How am I supposed to set functionality for `esc` key in a CSS file?  
If you're using a JS framework, I suggest using a JS plugin for modal because it can provide you keyboard navigation using JS and you can also append the modal content on demand.

What daisyUI as a CSS file can provide for you is just showing and hiding divs visually.  

These are some headless JS modal plugins I would suggest: 
- https://headlessui.com/react/dialog
- https://www.radix-ui.com/docs/primitives/components/dialog
