### ISSUE TITLE
bug: Card figure not rounded with Gatsby-image on safari

### ISSUE THREAD

**Issue by hrenaud** [saadeghi/daisyui#1670]
### What version of daisyUI are you using?

2.51.3

### Describe your issue

I'm using Tailwind/DaisyUI/Gatsby to create my website.

In 2 pages, I'm using the DaisyUI Card component. In each usage and alternative (Normal, Compact and Card-side), the rounded corners aren't rendering.

https://novagaia.fr or https://novagaia.fr/posts/

### What browsers are you seeing the problem on?

Safari

### Reproduction URL (optional)

https://novagaia.fr

**Comment by saadeghi** [comment]
I'm assuming Gatsby is either injecting a different HTML structure or some custom CSS and if that's the case, I'm afraid I can't do anything about it. if your CSS and HTML is the same as the examples, you would get the same result. if the result is different because of something else, you may want to add some custom CSS (or utility classes) to fix them.
