### ISSUE TITLE
bug: Adding caption to table break rounded corner

### ISSUE THREAD

**Issue by Marthym** [saadeghi/daisyui#1683]
### What version of daisyUI are you using?

2.51.3

### Describe your issue

If you add a caption to the table, the top rounded corners was broken.

```html
<div class="overflow-x-auto">
  <table class="table w-full">
    <caption>description</caption> <!-- break rounded corner -->
    <!-- head -->
    <thead>
      <tr>
        <th></th>
        <th>Name</th>
        <th>Job</th>
        <th>Favorite Color</th>
      </tr>
    </thead>
    <tbody>
      <!-- row 1 -->
      <tr>
        <th>1</th>
        <td>Cy Ganderton</td>
        <td>Quality Control Specialist</td>
        <td>Blue</td>
      </tr>
      <!-- row 2 -->
      <tr>
        <th>2</th>
        <td>Hart Hagerty</td>
        <td>Desktop Support Technician</td>
        <td>Purple</td>
      </tr>
      <!-- row 3 -->
      <tr>
        <th>3</th>
        <td>Brice Swyre</td>
        <td>Tax Accountant</td>
        <td>Red</td>
      </tr>
    </tbody>
  </table>
</div>
```

### What browsers are you seeing the problem on?

Firefox

**Comment by gukanozadze** [comment]
I don't know `:where` and `*:first-child` syntax but this happens because in source code we are selecting 
table => first-child (thead) => first-child (tr) => th and applying border-radius

When you add `caption` element, first-child becomes caption element and we can't find th anymore.



<img width="336" alt="image" src="https://user-images.githubusercontent.com/21206256/226684726-8e7ffd28-25ee-46d5-bb9f-8738ad6fea0b.png">

**Comment by gukanozadze** [comment]
### solution

Add border radius manually 

<img width="511" alt="image" src="https://user-images.githubusercontent.com/21206256/226685978-c6218135-1381-46ca-8b2a-af8d39f364a4.png">

**Comment by saadeghi** [comment]
@gukanozadze is right. I didn't consider `caption` tag in the style.    
Until it gets fixed in the source code, you can use @gukanozadze's workaround until then.
