### ISSUE TITLE
bug: Carousel scroll-snap issue

### ISSUE THREAD

**Issue by thdoan** [saadeghi/daisyui#1686]
### What version of daisyUI are you using?

2.51.3

### Describe your issue

If you happen to scroll during the middle of a slide transition, the animation stops midway. Example:

https://www.loom.com/share/7cbae9d72e46445996492c47a5e6ab67

Does anyone have a way to resolve this using CSS only?

I was going to use JavaScript to detect `scroll` events so that I can disable vertical scrolling while the slide is transitioning, but would prefer a CSS-only solution.

### What browsers are you seeing the problem on?

Chrome

**Comment by saadeghi** [comment]
This is really not something I can fix on my side. It's just how browsers handle the scroll.  

Here you can see a simper example without daisyUI. Click on a number and then press `space` key (for scroll) during the animation and you can see the the scroll snap stops working:  
https://codepen.io/saadeghi/pen/poOLxpK?editors=1000

I don't know if it's a bug from the browsers or it's intentional or if it's a performance trade-off.

Anyway, for better experience, I would suggest using a JS plugin for a slider because a JS plugin can handle slides without needing an anchor link (so this issue won't happen) and a JS plugin can also give you more functionalities like keyboard navigation, etc.  

It's perfectly fine to mix and match daisyUI plugin with JS plugins wherever you need a JS plugin. Because there are specific things that a JS plugin can handle better.

Let me know if you have any questions
