### ISSUE TITLE
bug: White line above file-input-sm

### ISSUE THREAD

**Issue by dgmp88** [saadeghi/daisyui#1700]
### What version of daisyUI are you using?

2.50.1

### Describe your issue

file-input-sm has a white line that appears at the top: 
<img width="390" alt="Screenshot 2023-03-21 at 10 17 41" src="https://user-images.githubusercontent.com/6919834/226577568-85ff702d-a8d1-405b-a8b3-b21229dbd98d.png">

It's visible for me on Chrome and Safari (not tested on others) on [the docs page](https://daisyui.com/components/file-input/) too. [Taking away the top border helps](https://play.tailwindcss.com/81BGI2e2eW)

Thanks for the awesome work, Daisy UI is amazing! :D 

### What browsers are you seeing the problem on?

Chrome, Safari

### Reproduction URL (optional)

https://play.tailwindcss.com/81BGI2e2eW

**Comment by gukanozadze** [comment]
### Problem

`file-input-lg` and `file-input-md` have line-height set to 2.0

`file-input-xs` has line-height set to 1.625

for some reason, `file-input-sm` has line-height set to `2rem` which is taller than height of input, that's why you see white line between top border and input.

### FIX
converting `file-input-sm` line-height to 1.625 just like `file-input-xs` will fix the issue.

I will try to do a pull request
