### ISSUE TITLE
bug: Carousel bring me to the bottom of the component

### ISSUE THREAD

**Issue by xvimnt** [saadeghi/daisyui#1704]
### What version of daisyUI are you using?

2.51.3

### Describe your issue

 **Carousel with indicator buttons** and **Carousel with next/prev buttons**  are bringing me to the bottom of the component when I change the current image

### What browsers are you seeing the problem on?

Chrome

### Reproduction URL (optional)

https://daisyui.com/components/carousel/

**Comment by saadeghi** [comment]
It's a CSS only carousel and it works with HTML anchor links. That scrolling is the default behavior of the browser because it wants to scroll to the active anchor item.  
I would suggest using a JS plugin for carousel. It's perfectly fine to use any JS plugin alongside daisyUI because sometimes JS plugins can provide you features that CSS can't do.

Let me know if you have any questions.

**Comment by xvimnt** [comment]
all right, anyway, would be great to prevent the default behavior such as the one in Flowbite [ ](https://flowbite.com/docs/components/carousel/)
