### ISSUE TITLE
bug: carousel works Firefox, Chrome but not Safari

### ISSUE THREAD

**Issue by mrfragger** [saadeghi/daisyui#1717]
### What version of daisyUI are you using?

2.51.5

### Describe your issue

carousel let's one navigate to next image with right arrow key or back with left arrow key and it's perfect.  Just on Safari (mobile) it doesn't contain images (svgs in this case) as it's just displays them all vertically.  I'm read your comments you suggest using a JS image slider as it'll handle most probably but an all CSS solution would be awesome like daisyui if possible.

<div class="w-full carousel">
<div id="item1" class="carousel-item w-full justify-center"><img src="01animated.svg"></div>

Not sure if it's a scroll snap bug or what as I've searched but tough to nail it down.

.carousel::-webkit-scrollbar{display:none}

.carousel{display:flex;overflow-x:scroll;scroll-snap-type:x mandatory;scroll-behavior:smooth;-ms-overflow-style:none;scrollbar-width:none}

.carousel-vertical{flex-direction:column;overflow-y:scroll;scroll-snap-type:y mandatory}

.carousel-item{box-sizing:initial;display:flex;flex:none;scroll-snap-align:start}

.carousel-center 

.carousel-item{scroll-snap-align:center}

.carousel-end 

.carousel-item{scroll-snap-align:end}

### What browsers are you seeing the problem on?

Safari

**Comment by saadeghi** [comment]
Here's a video of all examples working on iOS 16  

https://user-images.githubusercontent.com/7342023/235749159-e26611a6-1da4-49d5-a5ca-0e50478ae5f5.mp4

>Just on Safari (mobile) it doesn't contain images (svgs in this case) as it's just displays them all vertically.

Please share a sample project because there's nothing wrong with examples or the package. It is working on every other project and CSS scroll snap is supported by all browsers. If it's not working on your project, probably Tailwind CSS config on your project is not correct.

> for me none of the carousels on the example page are working (firefox, safari & chrome)

Unless you're using a really old browser, it should work:  
<img width="712" alt="Screenshot 2023-05-02 at 21 14 16" src="https://user-images.githubusercontent.com/7342023/235750689-8c3173f6-8b16-4670-b85a-e34cf7588fae.png">
