### ISSUE TITLE
bug: "The `text-primary-400` class does not exist" after enabling plugin

### ISSUE THREAD

**Issue by slhck** [saadeghi/daisyui#1724]
### What version of daisyUI are you using?

v2.51.5

### Describe your issue

This seems related to:

- https://github.com/saadeghi/daisyui/issues/1702
- https://github.com/saadeghi/daisyui/issues/683

I am getting the error but in a slightly different context.

In my Next.js 13 app's `globals.css` I have:

```css
main a {
  @apply text-primary underline;
}

main a:hover, main a:focus {
  @apply text-primary-400;
}
```

And my Tailwind config looks like this:

```js
/** @type {import('tailwindcss').Config} */
module.exports = {
  content: ['./src/**/*.{js,ts,jsx,tsx}', './node_modules/@tremor/**/*.{js,ts,jsx,tsx}'],
  theme: {
    colors: {
      primary: {
        DEFAULT: '#1F7A8C',
        50: '#D2E4E8',
        100: '#B6D3D9',
        200: '#9AC3CB',
        300: '#7EB2BD',
        400: '#62A2AF',
        500: '#4691A0',
        600: '#1F7A8C',
        700: '#1A6777',
        800: '#11424D',
        900: '#103D46',
      },
      // ...
    },
  },
  plugins: [
    // require('daisyui')
  ],
};
```

Once I enable the plugin, I get the error:

```
./src/styles/globals.css:70:3
Syntax error: /Users/werner/Documents/Projects/.../src/styles/globals.css The `text-primary-400` class does not exist. If `text-primary-400` is a custom class, make sure it is defined within a `@layer` directive.

  68 | 
  69 | main a:hover, main a:focus {
> 70 |   @apply text-primary-400;
     |   ^
  71 | }
```

Why does this work when I do not have `daisyui` enabled?

Note that I am not explicitly using the `text-primary-400` class in any of my components, but it worked before.

### What browsers are you seeing the problem on?

Chrome

**Comment by saadeghi** [comment]
Here's how it works, I hope it answers the confusion:  
Tailwind CSS has a wide range of color names. They are constant colors like `gray-800`, etc.  
You can also define your own color names in Tailwind config (like you did) and name them anything (`primary`, etc)  

However, All these color shades exist so developers can build anything with it. Because Tailwind has no opinion about your project's color palette. In a real-life design system you can not and should not use all shades of color. In reality, you would only need 1 or 2 or sometimes 3 brand colors (primary, secondary, accent) and then you need some state colors (success, error, info, warning) and also some neutral UI colors for (usually shades of gray. To display dark text on light background or light text on dark background) This is basically a standard on almost every design systems.

And here's what happens when you add daisyUI:  
daisyUI adds [24 additional color names](https://daisyui.com/docs/colors/) to Tailwind. Now Tailwind can create color utility class names for them too. So you can use `bg-primary` or `text-success` etc.  
daisyUI color class names don't use constant color values like `#1f2937` (the way Tailwind colors do) Instead they use CSS variables like `hsl(var(--p))` ([see this table](https://daisyui.com/docs/colors/)). This way we can change the color value in the runtime by changing a theme. For example when we use the built-in `cupcake` theme, primary color will be teal green and when we use `corporate` theme, primary color will be light purple ([see all themes here](https://daisyui.com/docs/themes/))  

This is useful for rapidly make dark/light themes without even thinking about the correct color combination on each theme. For example when you use `base-content` color on `base-100` background color you know it will look good on all themes without even testing it.  

Apart from colors, daisyUI registers new component classnames to Tailwind, They are predefined class names and only specific component names have specific color variations (because not all components need all color variations) They are not getting generated automatically so `btn-primary-800` or `btn-blue-500` won't work. You can see the available class names for each component on the docs.  

So now you know why [your example of re-using the colors from your extended theme](https://play.tailwindcss.com/PYoPx4u7nR?file=config) works. Because daisyUI components don't care about your Tailwind color shades. You can basically set any color names in Tailwind. They will all work using utility classes like `text-*` or `bg-*` but daisyUI component `btn btn-primary` only works with daisyUI's `primary` color. It can't get generated automatically because it will easy lead to having a inaccessible color combination (why? because when we use `btn-primary`, we're basically using `bg-primary` for background, `text-primary-content` for text and `bg-primary-focus` for hover state. It's not just one color. If we automatically generate all button color variations based on all available colors, most of them would have a bad color contrast unless we force developers to define background color and foreground color and hover color for each button)

I would suggest instead of defining hundreds of HEX color shades, to just trust [daisyUI's limited naming](https://daisyui.com/docs/colors/) and use [the theme-generator](https://daisyui.com/theme-generator/).  This limited color palette is not a new radical approach. It's a naming convention that design systems were using for many years and was adopted by most famous design systems and component libraries like Material, Bootstrap and everyone else.

Let me know if you have any questions.

**Comment by slhck** [comment]
> because when we use btn-primary, we're basically using bg-primary for background, text-primary-content for text and bg-primary-focus for hover state. It's not just one color

I think that's the crucial part I was not directly aware of. It makes total sense. Thanks!

> I would suggest instead of defining hundreds of HEX color shades

True, that'd work for most cases. In the example I gave those were just imported from another project that happened to generate the shades already (for UI libraries that didn't auto-generate them).

**Comment by sangayt1997** [comment]
@saadeghi Thank you for the solution
