### ISSUE TITLE
bug: select-sm and select-xs don't format properly

### ISSUE THREAD

**Issue by mark1502** [saadeghi/daisyui#1731]
### What version of daisyUI are you using?

v. 2.31.0

### Describe your issue

When using select-sm or select-xs, the text in the select doesn't  appear properly.  The droplist itself looks fine, but the text in the element where you'd click to open the droplist does not appear correctly.

Strangely, it looks fine on the daisyui select documentation page.  I'm not sure why it looks ok there, but not in my code.

Here's the html used:
  ```
<select class="select select-bordered select-sm" id="showSelect" v-model="state.show" @change="showChanged">
    <option>6</option>
    <option>8</option>
    <option selected>10</option>
    <option>12</option>
    <option>15</option>
    <option>20</option>
    <option>25</option>
</select>
```
Here are pics of the select-sm and select-xs with and without the droplist.  The pics are from Chrome.  It's slightly better on Firefox, but still the same problem.

**select-sm pics:**

![select-sm_1](https://user-images.githubusercontent.com/38567111/229633684-53ef3152-b78e-49e0-895c-dfbe0d342e88.gif)
![select-sm_2](https://user-images.githubusercontent.com/38567111/229633689-11913661-4773-4bb3-9cad-e15312c92575.gif)

**select-xs pics:**

![select-xs_1b](https://user-images.githubusercontent.com/38567111/229904687-f4e72dce-5452-4966-86e2-dd71a4b905f9.gif)
![select-xs_2](https://user-images.githubusercontent.com/38567111/229633692-71a0f3ec-8c72-4cb5-a044-22f7c63209ed.gif)

Thanks

### What browsers are you seeing the problem on?

Chrome, Firefox

**Comment by msyavuz** [comment]
Unable to reproduce this in firefox. 

### Url

https://play.tailwindcss.com/hlopLkvekB

**Comment by saadeghi** [comment]
I think you're using `@tailwindcss/forms` package.

You should either use [the `strategy: 'class'` config for Tailwind Forms](https://github.com/tailwindlabs/tailwindcss-forms) so this plugin only applies style to the inputs with specific class names or you should disable Tailwind Forms completely if you're not using it (because it basically does the same job as daisyUI)

Related topics:
- https://github.com/saadeghi/daisyui/issues/1431
- https://github.com/saadeghi/daisyui/issues/1378
- https://github.com/saadeghi/daisyui/issues/1301
- https://github.com/saadeghi/daisyui/issues/804
