### ISSUE TITLE
bug: bumblebee checkbox error in theme changer

### ISSUE THREAD

**Issue by keanesnow98** [saadeghi/daisyui#1765]
### What version of daisyUI are you using?

2.51.5

### Describe your issue

I have opened theme changer in [DaisyUI](https://daisyui.com), all is working correctly when I am switching between themes, but if I select `bumblebee` theme, I can't see the checkbox. Here's picture:
![image](https://user-images.githubusercontent.com/119104736/233720515-bbffc09e-6e63-41a0-bd31-7ceef908f379.png)
This is important since it is placed in your site.

### What browsers are you seeing the problem on?

Chrome

**Comment by saadeghi** [comment]
I can't see the issue.  
1. Does this happen only for the "bumblebee" item?
2. Do you have this issue in a incognito browser tab as well?
3. Are you using any software or plugin that may change or manipulate web page contents? like an ad blocker or any CSS customization plugin?

**Comment by keanesnow98** [comment]
It only happens for "bumblebee" item.
And I don't use any blockers. I have just tested it on both incognito and guest mode, but the same issue occurs.

**Comment by keitoAtZ** [comment]
I think this is happening because there is less margin in Windows.

Windows11 + Chrome
<img alt="daisyUI1" src="https://user-images.githubusercontent.com/4322436/234043888-e1071f92-794f-46d7-bf1c-21027bab5af4.png">

MacOS + Chrome
<img alt="daisyUI2" src="https://user-images.githubusercontent.com/4322436/234044084-cbe123b4-4e9a-4958-8672-095f7e2bbc29.png">

**Comment by saadeghi** [comment]
I see. Will be fixed soon. thank you
