### ISSUE TITLE
bug: dropdown menu in drawer aside not show up correctly

### ISSUE THREAD

**Issue by Seandor** [saadeghi/daisyui#1786]
### What version of daisyUI are you using?

v2.51.5

### Describe your issue

The dropdown menu is cut off on the edge of drawer aside, have tried different ways to fix it. I learned about stacking context, but it seems it's not the case. I have added overflow-visible to all it's parent element, still not working. I am getting more and more curious what could cause this behavior?

### What browsers are you seeing the problem on?

Edge

### Reproduction URL (optional)

https://play.tailwindcss.com/rHeawCuNRD

**Comment by saadeghi** [comment]
By default `drawer-side` has `overflow-x: hidden` and `overflow-y: auto` because we don't want horizontal scroll and we want vertical scroll when the content is longer than screen. Unfortunately the way CSS overflow works is when we use `overflow-y: auto`, we can not make horizontal overflow visible. I couldn't find a workaround for it yet but if you are sure you won't want a vertical scroll, you can add `!overflow-visible` to `drawer-side` and force it to show the overflow items.  
Example: https://play.tailwindcss.com/cxYX4g1Vyu?size=1074x582

Good news is, daisyUI 3.0 will be released this month and it will provide collapsible menu items.

Let me know if you have any questions.
