### ISSUE TITLE
bug: Buttons with state colors do not have animation on hover

### ISSUE THREAD

**Issue by kyngs** [saadeghi/daisyui#1790]
### What version of daisyUI are you using?

2.51.6

### Describe your issue

There's no animation when hovering over buttons such as info, success, warning, or error. This issue is reproducible on the official site:

https://user-images.githubusercontent.com/38181667/235652937-1de862a0-50e0-4d7b-b850-78347146f812.mp4

### What browsers are you seeing the problem on?

Chrome, Firefox

**Comment by dtcooper** [comment]
+1 on this one! Thanks :)

**Comment by kyngs** [comment]
> +1 on this one! Thanks :)

Unfortunately, it kinda seems like this got forgotten.

**Comment by saadeghi** [comment]
It's not forgotten, but this improvement is expensive in file size and I don't think it's worth it. Currently there are `primary-focuse`, `secondary-focus`, etc colors but there's no `error-focus`, `info-focus`, `warning-focus`, `success-focus` colors. In another there's a need for a soft version of these colors (because an alert with soft blue background and normal blue text looks better than normal blue background and white text. But for a button, blue background and white text looks better)  
I haven't yet find a way to handle all these colors without increasing the amount of color names and making it more confusing to make themes. And keeping the number of CSS variables low.

I was planning to use CSS color-mix function because it solves all these issues but the browser support is not good yet.

**Comment by saadeghi** [comment]
Fixed in daisyUI 4
