### ISSUE TITLE
border for different avatar style such as hexagon

### ISSUE THREAD

**Issue by khoivan88** [saadeghi/daisyui#180]
Hi, again, thank you for this project and keep updating it. I have been using it for a while now. I know this might not be easy but would you mind considering adding avatar with circle style for hexagon and other Mask shapes?

Thank you very much!

**Comment by saadeghi** [comment]
@khoivan88 It's not possible to have a visible border when we use a css mask, because the mask crops anything outside of shape and border is outside of the shape; 
***but*** we can get a similar result by nesting two masks: https://play.tailwindcss.com/NL5SRDnqkx  
let me know if you have any questions

**Comment by khoivan88** [comment]
@saadeghi  That is so clever, thank you so much!!
