### ISSUE TITLE
bug: collapse collapses in use with form elements

### ISSUE THREAD

**Issue by mark1502** [saadeghi/daisyui#1815]
### What version of daisyUI are you using?

v2.51.6

### Describe your issue

I have a collapse div on a form.  The collapse has several input elements in a div with collapse-content.

But after the collapse is opened, if I click on any input element or select within the collapse to enter data, the collapse closes, so I can't put any form elements in the collapse.  

I can click within the collapse on some text within a paragraph tag, or on the background, and the collapse remains open.  But if I click on a form element like an input or select, the collapse closes.

I'm attaching a file with an example of the collapse.  It's from a vue template, so it uses some vue components.  But I also tested it using just plain html form elements with the same result.

Thanks
[DaisyUI_collapse_issue.txt](https://github.com/saadeghi/daisyui/files/11455773/DaisyUI_collapse_issue.txt)

### What browsers are you seeing the problem on?

Chrome, Firefox

**Comment by saadeghi** [comment]
There are 2 types of `collapse`.  

If you're using [collapse with focus](https://github.com/saadeghi/daisyui/discussions/653) this is an expected behavior. It works with focus event so when you focus any other element, it will get closed.

Use [collapse with checkbox](https://daisyui.com/components/collapse/#collapse-with-checkbox) for this case

**Comment by mark1502** [comment]
Yes, that was the problem with my code.  It works great now, thanks!
