### ISSUE TITLE
bug: Modal backdrop is getting limited inside the dive. Not covering the entire screen

### ISSUE THREAD

**Issue by Nagarajnaidu921** [saadeghi/daisyui#1827]
### What version of daisyUI are you using?

v2.51.6

### Describe your issue

When we use modal inside any div, it is getting fixed inside the div , It is should get entire screen covered

![image](https://github.com/saadeghi/daisyui/assets/20486700/d7dbae2f-3425-4cc3-9c79-f6be6aa66e45)
![image](https://github.com/saadeghi/daisyui/assets/20486700/b52f1eca-baf7-41db-8538-7952bfbd0df1)

### What browsers are you seeing the problem on?

Firefox

### Reproduction URL (optional)

https://play.tailwindcss.com/Sse6YJfBoG

**Comment by saadeghi** [comment]
Do you see the comment saying `put this part before </body> tag`? Put it before `</body>` tag 😊

**Comment by Nagarajnaidu921** [comment]
This not useful when it comes to creating react and creating components out of it

**Comment by saadeghi** [comment]
In react, as far as I know you can move DOM elements to other parts of page using [CreatePortal](https://react.dev/reference/react-dom/createPortal)  
But good news, daisyUI `3.0` will be released in 2 weeks which uses the new HTML `<dialog>` element and it won't have this positioning requirement.  

Alternatively, it's totally okay to use a react plugin for modals because If you're using React, a React modal can give you features that can not be handled using CSS such as keyboard navigation, routing, and more importantly, rendering the modal content on-demand. As far as I know, in most modal plugins you can customize the class names or CSS so you can use daisyUI colors in them and it will match your website theme.

Let me know if you have any questions.
