### ISSUE TITLE
bug: Submenu items need z-index like dropdown

### ISSUE THREAD

**Issue by awhitford** [saadeghi/daisyui#1833]
### What version of daisyUI are you using?

v2.51.6

### Describe your issue

I have a [NavBar](https://daisyui.com/components/navbar/) with a submenu and a dropdown.
Below the NavBar is an [AG Grid](https://www.ag-grid.com/).

The Dropdown items appear fine, but the Submenu items are hidden by the AG Grid.
I think I traced the discrepancy to the fact that _Dropdown items_ will override the `z-index: 50;` while _Menu items_ will not.

### What browsers are you seeing the problem on?

Chrome

**Comment by saadeghi** [comment]
dropdown having a z-index was a mistake from me and that z-index will be removed soon in daisyUI `3.0` because sometimes we need the dropdown to go under other items (for example a fixed navbar that should be on top of the dropdown) and sometimes we need the dropdown to be on top.  
So it depends on the project and I think having a hardcoded z-index was a mistake. Instead, depending on the design devs should use `z-*` utility class to control the z-index as they need.

let me know if you have any questions.
