### ISSUE TITLE
bug: Carousel button scroll the page until the button are at the top of the screen

### ISSUE THREAD

**Issue by armanyfelix** [saadeghi/daisyui#1843]
### What version of daisyUI are you using?

^2.51.6

### Describe your issue

When I click the button, it doesn’t just change the image; it also scrolls the page down until the buttons are at the top of the page and only half of the picture is shown. I tried changing the transition property, but nothing has worked yet. Also, this process takes time and makes the image transition very slow. In the documentation, the same thing happens, but it’s more noticeable on my website. I think it’s because the carousel in the documentation scrolls to the bottom of the page and there is more space on my page.

### What browsers are you seeing the problem on?

Chrome, Firefox, Edge

### Reproduction URL (optional)

https://daisyui.com/components/carousel/#carousel-with-nextprev-buttons

**Comment by saadeghi** [comment]
It works with anchor links (because there is no JS here. only CSS + HTML)  
It scrolls to the top of the element with the same `id` as the button has as `href` and that's how anchor link works. it scrolls to the target (It's not scrolling to the bottom of page)

It's hard to guess why it's going that down on your page unless you provide a code example but here are my guesses: 
- make sure all the `id`s on your page are unique and the anchor tags are pointing to the right id
- make sure the item with the target `id` is a block element (not inline) and is positioned on top of your slider. Because where ever the element top is positioned, it will be scrolled there.
- make sure you're not using something like `scroll-padding-top` because that affects the offset for scrolling to anchor id.

If there points didn't help, please provide a code example where I can see the issue.

**Comment by armanyfelix** [comment]
> It works with anchor links (because there is no JS here. only CSS + HTML) It scrolls to the top of the element with the same `id` as the button has as `href` and that's how anchor link works. it scrolls to the target (It's not scrolling to the bottom of page)
> 
> It's hard to guess why it's going that down on your page unless you provide a code example but here are my guesses:
> 
> * make sure all the `id`s on your page are unique and the anchor tags are pointing to the right id
> * make sure the item with the target `id` is a block element (not inline) and is positioned on top of your slider. Because where ever the element top is positioned, it will be scrolled there.
> * make sure you're not using something like `scroll-padding-top` because that affects the offset for scrolling to anchor id.
> 
> If these points didn't help, please provide a code example where I can see the issue.

This works. The id wasn’t in the parent element of the component, which is why the scroll went so far down. Thanks for the support. 👍🏼 awesome library.

**Comment by zpydee** [comment]
so in my case, the anchor tags cause the to of the carousel to snap to the top of the screen, which is a negative UX. how can i prevent this?

**Comment by ariady-putra** [comment]
@zpydee I use `a onClick` instead of `a href`
```js
e.preventDefault();
document.querySelector(`#slide-${index}`)?.scrollIntoView({
  behavior: "smooth",
  block: "nearest",
});
```
