### ISSUE TITLE
v3: custom theme changes

### ISSUE THREAD

**Issue by gurgunday** [saadeghi/daisyui#1877]
### What version of daisyUI are you using?

v3.0

### Describe your issue

Hey, just upgraded to v3, and for the most part, it's awesome! 2 things caught my eye though when using custom themes.

1) Button text colors seem to have changed, was this intended?
![old](https://github.com/saadeghi/daisyui/assets/74139498/cfa9d2ca-5420-45ae-9fdd-84c78fa31025)
to this:
![new](https://github.com/saadeghi/daisyui/assets/74139498/4074c566-c6d2-4c9c-b0a3-bce1b4635838)

2) This one is a bit more obvious, but some colors darken too much when mouse is hovered over them. Here's an example:
![old2](https://github.com/saadeghi/daisyui/assets/74139498/17cf6834-aa02-4d5d-90aa-51b7904bcad3)
and v3:
![new2](https://github.com/saadeghi/daisyui/assets/74139498/48daccda-0c34-4f8b-bb2b-06d336dabba5)

Here's the corresponding theme:
```js
{
          neutral: "#290029",
          primary: "#290029",
          secondary: "#00e894",
          accent: "#f1fb00",
          "base-100": "#000000",
}
```
The button's HTML:
```html
<button class="btn-primary btn mt-10 w-80 sm:w-96">
              Submit Settings
</button>
```

**Comment by gurgunday** [comment]
This function seems to be causing the excessive darkening of some darker colors:

```js
  generateDarkenColorFrom: function (input, percentage = 0.07) {
    const str = colord(input).darken(percentage).toHslString();
    return this.turnColorValuesToString(str);
  }
```

Changing it to this was my temporary solution:
```js
  generateDarkenColorFrom: function (input, percentage = 0.07) {
    if (colord(input).isDark()) {
      percentage = percentage / 2;
    }

    const str = colord(input).darken(percentage).toHslString();
    return this.turnColorValuesToString(str);
  }
```

**Comment by saadeghi** [comment]
Yes it was intentional and this change creates better contrast for background/foreground colors. How ever you can still take full control of all colors.
By default, if you don't specify `primary-content` it generates a color for the foreground automatically using this function.  
But you don't need to change the function. Just add `"primary-content"` to your custom theme:
```
{
  neutral: "#290029",
  primary: "#290029",
  "primary-content": "#FCA4FD", // add this
  secondary: "#00e894",
  accent: "#f1fb00",
  "base-100": "#000000",
}
```
Example: https://play.tailwindcss.com/PYEromdAWL?file=config

You can add other optional colors as well: https://daisyui.com/docs/colors/
