### ISSUE TITLE
bug: Drawer has poor keyboard accessibility

### ISSUE THREAD

**Issue by probablykasper** [saadeghi/daisyui#1939]
### What version of daisyUI are you using?

3.0.3

### Describe your issue

When tabbing using the drawer, there's no indication of what you're tabbed over.

Additionally, the [Navbar menu for desktop + sidebar drawer for mobile](https://daisyui.com/components/drawer/#navbar-menu-for-desktop--sidebar-drawer-for-mobile) example lets you tab into the `drawer-toggle` checkbox on desktop:

https://github.com/saadeghi/daisyui/assets/11315492/68063fab-3cb0-4139-88c9-6e89f1c0c687

### What browsers are you seeing the problem on?

Chrome

**Comment by saadeghi** [comment]
As far as I know, there is no solution for this. The hidden checkbox should be before the `drawer-content` because that's the only way to control the style (unless CSS [`has()`](https://caniuse.com/?search=has) gets a better browser support)  
And the label is the only thing that can control the checkbox without using JS but a HTML label can not have CSS `:focus-within` and it can't be focused so we can't show an outline for it. Instead the hidden checkbox is getting the focus because otherwise there would be no way to open the drawer with keyboard.

Until we get a better browser support with CSS `has()` the a workaround to improve the accessibility would be using a `<button>` instead of `<label>` and check/uncheck the checkbox using JS when button clicked.

**Comment by probablykasper** [comment]
What about something like this?
```css
input:focus-visible ~ .drawer-content label.drawer-label {
	outline: auto 1px red;
}
```

For making it not tabbable on desktop, `sm:hidden` could be added to the `input`
