### ISSUE TITLE
Is it possible to expand the palette? 

### ISSUE THREAD

**Issue by tom-acceleratecompliance** [saadeghi/daisyui#195]
Hi again,

In tailwind directly, it's possible to add as many variants as you like for a specific color, with the ability to fall back to the default if not found. 

With our usage, we've found it would be hugely valuable to add support for something like `primary-100`, `primary-200` etc, that could be defined in the theme and fall back to `primary` directly if the theme doesn't have definitions. Is it possible to expand the `primary`, `secondary`, `accent` definition include non-default variants?

Thanks!

**Comment by saadeghi** [comment]
@tom-acceleratecompliance Currently there's no easy way to do this (you have to add all possible utility classes for all custom colors manually). But you can always use Tailwind colors anywhere.  
I believe 2 shades of primary color is a common practice in a design system. some design systems add a wider range of shades but I don't find that practical in a real product.

**Comment by ohmree** [comment]
I think one use case for this is social sign in buttons, I think it's acceptable to break out of the site-wide design system and make, for example, the twitter sign in button have the iconic twitter color.

I can extend the tailwind theme and do something like `btn bg-twitter` but then the rest of the styling (hover background, borders etc.) still comes from the stock `btn`.

[Bootstrap has this in the form of a mixin](https://getbootstrap.com/docs/5.1/components/buttons/#mixins) you can include in any class you want that also gets called automatically on the theme map, so you can also extend/modify that before including bootstrap and have variants like `btn-twitter` auto-generated for you.
Since tailwind uses postcss instead of sass I'd imagine you could in theory supply a utility like this, no?
I'd also imagine the built-in styles could benefit from something like this to be less repetitive so to me it looks like a win-win situation.
And if the way tailwind works allows this you could maybe have it auto-applied to user-added colors, so if I add a `twitter` color to the theme it could auto-generate a `btn-twitter` just like in bootstrap.

**Comment by saadeghi** [comment]
The idea of using `primary`, `secondary`,... colors is that they are theme agnostic. `primary` can be red on one them and can be blue on the other theme. But if we want to use a specific color like the brand color of twitter, I don't think that should change based on a theme.  

Currently there are many ways to have custom colors:
1. Extending Tailwind CSS colors: https://play.tailwindcss.com/vwaJZ9OyBP?file=config
2. Using Tailwind CSS arbitrary color utilities: https://play.tailwindcss.com/foxnbeTL0K
3. Having custom modifier class for a component: https://play.tailwindcss.com/MaCwWuv6pw?file=css
4. Define theme specific style for a component: https://play.tailwindcss.com/tuvtwGPCyB?file=config

**Comment by ohmree** [comment]
> The idea of using `primary`, `secondary`,... colors is that they are theme agnostic. `primary` can be red on one theme and can be blue on the other theme. But if we want to use a specific color like the brand color of twitter, I don't think that should change based on a theme.

Sure, but the same utilities that one can use to create a theme also apply to this use case.
So maybe "theme" isn't the right here, but I think there should be a way to reuse daisyui's styling where possible - something like bootstrap's `button-variant` mixin that generates all of the constant boilerplate (stuff like border radius and hover background color that can be computed from the regular background color) while allowing you to fill in the variables - namely the background and border colors.

> Currently there are many ways to have custom colors:
> ...

But none of them are very DRY - you have to manually duplicate the styling done in daisyui to get a button that's consistent with the rest of the components but has a different color.
Now correct me if I'm wrong but from what I've seen daisyui itself does this - copy-pasting the constant parts of the styling for different variants and changing the bits that should change like the colors.
Don't you think adding utilities that generate this boilerplate could reduce duplication inside the codebase while also allowing others to use the design language for one-off cases like mine much more easily?

**Comment by saadeghi** [comment]
Every component is using the colors in a unique way.
For example, a button uses 2 shades of `primary` color for background and border. A checkbox uses only 1 shade of primary. A breadcrumb link doesn't even have to use primary color.

So I can't just define an array of colors and generate all components with all colors. That would look cool from (over)engineering aspect but we're talking about design systems here. In a design system there are colors, sizes, fonts, etc. available as tokens and every component should only use the required ones.    

Can we have 12 brand colors in 1 app? Yes.  
But should we have 12 brand colors in 1 app? Never.  

I'm certain that it's possible to recreate 99% of every legit UI just by using the current daisyUI color names. 

There are edge cases of course. We might need rainbow gradients. We might need social login buttons as you mentioned. But these ones are constant colors on dark mode/light mode (or all themes) There's no need to put their values in variables because they're not meant to be variables.

The part you said about copy pasting is not correct. Every component has its own isolated style. If you expected it to define (let's say) width values and use them across all components, daisyUI doesn't do that because Tailwind CSS already has a great width scale. I just used them on components as it is.  There are theme-level design decisions tho that need to be different on every theme like colors, border radius, etc. These are the ones I added and the values are all coming from CSS variables.

**Comment by ohmree** [comment]
I might not have explained myself very well.
I meant that to me for example all of the button variants from [this line](https://github.com/saadeghi/daisyui/blob/7d4ceb63238b62d4e5098d2bf2d285b9d3ab76aa/src/components/styled/button.css#L27) all the way to line 99 (and possibly more) look like the only difference between them is in the colors, so you could extract them into a postcss function, e.g. `button-variant($color, $color-css-variable)` that generates something like this:
```scss
&-#{$color} {
  @apply border-#{$color} bg-#{$color} text-#{$color}-content;
  &:hover,
  &.btn-active {
    @apply border-#{$color}-focus bg-#{$color}-focus;
  }
  &:focus-visible {
    outline: 2px solid hsl(var(#{$color-css-variable}));
  }
}
```
And then if this utility is exposed to users they could, instead of having to dig into the daisyui sources, just say "the class `btn-twitter` should be styled like daisyui styles its buttons, except using this color instead of whatever color each of the stock buttons use".
Am I missing something obvious that prevents this from being done?
(apart from lack of interest, which is 100% valid.)

**Comment by saadeghi** [comment]
I think you're missing the point here so let me ask:  

Give me an example UI:
- while [these 24 colors](https://daisyui.com/docs/colors/) are not enough 
- and you need 1 more color which should have different values in different themes.

**Comment by ohmree** [comment]
You probably know better than me so I'll agree with you that for an end user designing a UI that that is consistently styled what daisyui offers currently is enough.
But I still do think that my suggestion could help reduce duplication internally and make it easier for users to include the _constant_ parts of daisyui's styling.
In bootstrap I can do this and instantly have a button variant that is like the stock ones in every aspect, except for the colors:
```scss
@use 'bootstrap';
$twitch-purple: #9146ff;
.btn-twitch {
  @include bootstrap.button-variant($twitch-purple, $twitch-purple);
}
```
And in fact this is how the default bootstrap buttons are generated - they loop over the theme colors map (primary, secondary, light, dark, warning, info, etc.) and use the same mixin to generate all of the constant parts of the style, with the variable part being the actual color:
```scss
@each $color, $value in $theme-colors {
  .btn-#{$color} {
    @include button-variant($value, $value);
  }
}
```
I just think having something like this in daisyui (and maybe similar features for other components that have different color variants) could solve this issue elegantly while also reducing boilerplate internally.
If you disagree then I guess all I have to say is thanks for creating daisyui, it really is nice.

**Comment by saadeghi** [comment]
I agree that it would be cool to extend components like that but what we should consider here is that the usual stack people are using on a Tailwind CSS project is either **PostCSS + Tailwind CSS** or just **Tailwind CSS** package without PostCSS.  
Since we're not using Sass, creating the same extending functionality would require PostCSS plugins as dependencies.

If daisyUI was a Sass plugins I would certainly go that way but this is a different environment and I think in a Tailwind environment [using `@apply` to extend the style](https://play.tailwindcss.com/MaCwWuv6pw?file=css) is way more easier than using a custom way of extending style using an external PostCSS plugin.

**Comment by theoradicella** [comment]
https://github.com/saadeghi/daisyui/discussions/653
