### ISSUE TITLE
bug: span in join does not work correctly (style)

### ISSUE THREAD

**Issue by xJeneKx** [saadeghi/daisyui#1964]
### What version of daisyUI are you using?

v3.0.22

### Describe your issue

Span is displayed incorrectly in join, the same case with input-group works well

<img width="331" alt="image" src="https://github.com/saadeghi/daisyui/assets/3996862/ab64a879-e31c-4106-85a5-e0caf5348fcc">

### What browsers are you seeing the problem on?

Chrome

### Reproduction URL (optional)

https://play.tailwindcss.com/NHGPRfqRdc

**Comment by saadeghi** [comment]
Yes, it was causing problems because all other daisyUI styles were getting applied using class names and this one span was being forced to have styles just by the tag name. So when developers wanted to add an span with a different style it was annoying to fight this forced style.

You can use something like `bg-base-300 flex items-center px-4` for the span to get the previous style:  
https://play.tailwindcss.com/me6Qu0CsZM

I'm working on fixing other issues this week but soon I will add a new class name for this [visual] label to be used next to the input.
