### ISSUE TITLE
bug: Tooltip padding is incorrect on flexbox

### ISSUE THREAD

**Issue by gerardmarquinarubio** [saadeghi/daisyui#1968]
### What version of daisyUI are you using?

3.0.22

### Describe your issue

Tooltip padding is incorrect in a flexbox `flex flex-row items-baseline gap-1 flex-wrap max-h-12 overflow-hidden`
![Screenshot 2023-06-10 014323](https://github.com/saadeghi/daisyui/assets/106877422/408add2c-205c-478a-9845-05948fbc6e30)

### What browsers are you seeing the problem on?

Chrome, Edge

**Comment by gerardmarquinarubio** [comment]
Nevermind, it was due to the overflow hidden, can this be fixed?

**Comment by saadeghi** [comment]
When you use `overflow-hidden` it will crop everything. In this case if you really have to use `overflow-hidden` you may want to add a padding to provide more space so it doesn't crop the tooltip

Let me know you have any questions.

**Comment by gerardmarquinarubio** [comment]
> When you use `overflow-hidden` it will crop everything. In this case if you really have to use `overflow-hidden` you may want to add a padding to provide more space so it doesn't crop the tooltip
> 
> Let me know you have any questions.

In my opinion a tooltip should render above everything ignoring any parent's overflow hidden.

**Comment by saadeghi** [comment]
> In my opinion a tooltip should render above everything ignoring any parent's overflow hidden.

It's not a good idea for every scenario. Imagine having a fixed navbar and having a tooltip in page content. It won't look good if the tooltip goes on top of the fixed navbar when you're scrolling.  
Same situation with every scrollable section.


Also we can't really render a tooltip on top of everything using CSS. There are JS tooltip plugins that can do that because they can dynamically monitor the element position and they can add/remove a new DOM element at the end of HTML when element is hovered and they can position that new DOM element when you scroll or when the element moves. That's not possible with CSS. With CSS, we can show a tooltip box (using a pseudo element or a HTML tag) right after the target element and we can show/hide it using CSS hover.  
And everything inside an `overflow:hidden` element will be cropped. That's how it's supposed to work.

You can use a JS library for tooltip (alongside daisyUI) and you can use daisyUI class names for other things. They will work fine together.
