### ISSUE TITLE
bug: migration to v3 dropdown will be blocked by input

### ISSUE THREAD

**Issue by gylove1994** [saadeghi/daisyui#1972]
### What version of daisyUI are you using?

v3.0.25

### Describe your issue

<img width="604" alt="image" src="https://github.com/saadeghi/daisyui/assets/47300853/ea05d3f6-74da-4f97-b231-d81788d213c6">

### What browsers are you seeing the problem on?

Chrome

**Comment by ravsii** [comment]
Shouldn't this be fixed just by using `z-**` classes?

**Comment by saadeghi** [comment]
From changelog: https://daisyui.com/docs/changelog/#breaking-changes

>`dropdown` doesn’t have a z-index by default now.

Using z-index for dropdown as a default style was a mistake because sometimes we need elements on top of the dropdown and sometimes we want the dropdown to be on top of other elements. Now you can use `z-[1]` or any other z-index class to control it as you want.
