### ISSUE TITLE
Angular version?

### ISSUE THREAD

**Issue by kaname-png** [saadeghi/daisyui#209]
A version for Angular would be great because DaysiUI is lightweight, and the current ones increase a little the bundle size of an Angular application, so it would be a positive point.

I would be very happy if there could be an Angular version of this great css framework.

**Comment by saadeghi** [comment]
You can use daisyUI with Angular ([example](https://github.com/saadeghi/daisyui/tree/master/examples/angular))  
And Tailwind should be purging unused CSS so there won't be any issues with bundle size.

**Comment by kaname-png** [comment]
Yes, I understand that part but I mean in a native way, for example: instead of `<Button class="class buttons"` it should be `<Button type="primary"`.

And I also wondered if there are no problems with Drawers type components in angular.

**Comment by saadeghi** [comment]
@kaname-png I don't have any plans for an Angular package myself but daisyUI is open source and MIT licensed so I would appreciate if any other developer wants to make an Angular version.

About `drawer`:  
There shouldn't be a problem as far as I know because daisyUI is just CSS and the same `drawer` CSS code is working on other frameworks and environments.
