### ISSUE TITLE
bug: radial-progress ::after circles appears in the wrong position

### ISSUE THREAD

**Issue by lushangkan** [saadeghi/daisyui#2095]
### What version of daisyUI are you using?

v3.1.0

### Describe your issue

radial-progress ::after circles appears in the wrong position

Code :  
```
<div class="radial-progress w-[88px] h-[88px] shadow-sm shrink-0" style="--value:70">70</div>
```

Screenshot:
![image](https://github.com/saadeghi/daisyui/assets/41252325/cd5354f8-e96a-4e77-b7b9-7157bbc3203e)

### What browsers are you seeing the problem on?

Edge

**Comment by lushangkan** [comment]
The problem is solved after changing the transform value in the `.radial-progress:after` class in css to `rotate(calc(var(--value) * 3.6deg - 90deg)) translate(calc(var(--size) / 2))`

**Comment by saadeghi** [comment]
Instead of using `w-*` and `h-*`, use the `--size` CSS variable to customize the size, like [the last example on this page](https://daisyui.com/components/radial-progress/#custom-size-and-custom-thickness)

```
<div class="radial-progress" style="--value:70; --size:12rem;">70%</div>
```

That CSS variable calculates the correct size for the line and the circle and spacing and everything.
