### ISSUE TITLE
bug: Icon not visible in date pickers when in dark mode.

### ISSUE THREAD

**Issue by Jabronironi** [saadeghi/daisyui#2106]
### What version of daisyUI are you using?

v3.1.10

### Describe your issue

The icons in the date pickers are not visible in dark mode.

My current workaround is to apply a style:

[data-theme='dark'] ::-webkit-calendar-picker-indicator { filter: invert(1); }

### What browsers are you seeing the problem on?

Chrome, Edge

### Reproduction URL

https://play.tailwindcss.com/rq1s1AUiQn

**Comment by saadeghi** [comment]
Colors of daisyUI themes work with daisyUI class names so if you add [`input` class](https://daisyui.com/components/input/) to it, it will have expected color:  
https://play.tailwindcss.com/RX9hsfSUp1

Also, I wouldn't suggest using `@tailwindcss/forms` with daisyUI together because that plugin adds styles to _all_ form elements by default and it will conflicts with daisyUI styles.  

If you really need `@tailwindcss/forms` alongside with daisyUI (which I doubt because both are doing the same job) consider using its [`strategy: 'class'` config](https://github.com/tailwindlabs/tailwindcss-forms#using-only-global-styles-or-only-classes) so it only applies style to the elements with specific class name (not all form elements)

**Comment by Jabronironi** [comment]
Okay, that is very helpful.  Thank you!
