### ISSUE TITLE
Use Just-In-Time mode for better performance

### ISSUE THREAD

**Issue by max-programming** [saadeghi/daisyui#211]
I loved this project! I just noticed the website was a little slow on an old machine. So for performance improvements, just use the [Just-In-Time](https://tailwindcss.com/docs/just-in-time-mode) mode in TailwindCSS.

```js
// tailwind.config.js
module.exports = {
  mode: 'jit',
  // other config
}
```

**Comment by saadeghi** [comment]
@max-programming you mean running the daisyui.com Nuxt website with `npm run dev` is slow?

**Comment by max-programming** [comment]
> @max-programming you mean running the daisyui.com Nuxt website with `npm run dev` is slow?

I didn't know it;'s built with nuxt tho. I mean that daisyui.com main website is a little slower on an old machine. I am not running the project locally. If you are using JIT already then close this issue coz I could not find the tailwind config for the site.

**Comment by saadeghi** [comment]
@max-programming JIT has nothing to do with site's loading speed for end-user.  
It just provides faster build time for development and production builds by generating class names on-demand (instead of generating all class names and then purging unused style for production build)  
If you're experiencing slow homepage on [daisyui.com](https://daisyui.com/) it's probably because of that large `glass` box with blur effect on the home page. Browsers on older machines can't render CSS blur with a high performance.

**Comment by max-programming** [comment]
Got it!
