### ISSUE TITLE
bug: drawer-content has weird scrolling behaviour on all browsers.

### ISSUE THREAD

**Issue by ahmetskilinc** [saadeghi/daisyui#2118]
### What version of daisyUI are you using?

2.52.0

### Describe your issue

I'm having issues with the drawer-content where the it has a box outside of it where it scrolls but also the content inside it scrolls.

I've tried many different things and cannot get it to work properly.

I haven't upgraded to 3.x because it feels incomplete and some things are also not playing right.

https://github.com/saadeghi/daisyui/assets/37756565/86e0ecaa-b8a8-427f-97eb-e86f0b3cb24a

I can provide code if needed.

### What browsers are you seeing the problem on?

All browsers

### Reproduction URL

https://sniplondon.com/

**Comment by saadeghi** [comment]
`drawer` style had a complete refactoring in version 3 and it fixed many problem so I would suggest upgrading.  

But your page has a weird problem 🤔  
There is no issue on Firefox but Safari and Chrome have this issue for some reason.

It's those `sr-only` class names for the 3 icons on the footer. `sr-only` makes the element `absolute` but for some reason on your page they move to the end of page and create that extra scroll. If you add `relative` class to one of their parent elements (for example `<a class="relative">`) the `sr-only` will stay in position.  
It's a workaround but I really don't know why they move that far in Chrome and Safari. It's the first time i'm seeing this but as far as I know, this issue won't happen with daisyUI 3 drawer.

Also, you can use `aria-labelledby` for SVG icons instead of using a hidden paragraph with `sr-only` class:
```html
<svg aria-labelledby="My icon title"
```



> I haven't upgraded to 3.x because it feels incomplete and some things are also not playing right.

Can you tell me what are the problems with version 3?

**Comment by ahmetskilinc** [comment]
That has fixed my issue! Thanks.

> Can you tell me what are the problems with version 3?

Some classes aren't playing right in 3.x with `pure-react-carousel`, so I just need to fix those issues and I should be okay to upgrade. I don't think its related to DaisyUI, however.
