### ISSUE TITLE
bug: Navbar details attribute not removed after user click away or click an item in it

### ISSUE THREAD

**Issue by FatalFriction** [saadeghi/daisyui#2128]
### What version of daisyUI are you using?

3.2.1

### Describe your issue

![image](https://github.com/saadeghi/daisyui/assets/43514974/62c89bdc-573a-4e4f-89c6-4224bcc250f4)
https://daisyui.com/components/navbar/
when i tried to click away from the navbar menu item it won't close itself i assume it has something to do with open attribute in `<details/>` also it only remove the open attribute when i clicked the summary button itself again which is not handy.

### What browsers are you seeing the problem on?

Chrome

**Comment by saadeghi** [comment]
submenu uses the [HTML `<details>` tag](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/details) It opens with click and closes with second click. It's the best option we can use to create an accessible menu that works on all devices and with screen readers.  

If you want it to get closed when clicked outside, you can handle that with JS.  
We can't really handle the `click outside` behavior on CSS. We need JS for that. In CSS we can use CSS focus to show something when it's focused but it's not accessible for screen readers and also we can't make multi level menus with that because only 1 element can be focused at a time and when the second level submenu gets focused, the first level will be closed. So it's not possible with CSS.

Here is a pure JS example: https://stackoverflow.com/a/68644266  
And there are also packages for frameworks: 
- https://www.npmjs.com/search?q=svelte%20click%20outside
- https://www.npmjs.com/search?q=vue%20click%20outside
- https://www.npmjs.com/search?q=react%20click%20outside

**Comment by FatalFriction** [comment]
Thanks, it helped a lot!
