### ISSUE TITLE
bug: Collapse (Accordion) component overlaps sticky header in table

### ISSUE THREAD

**Issue by camin-mccluskey** [saadeghi/daisyui#2132]
### What version of daisyUI are you using?

v3.1.9

### Describe your issue

Components using `collapse` with a radio button to achieve an accordion effect seemingly have a high z-index such that they overlap sticky headers in a table. 

I can't seem to find where this z-index is being set. 

<img width="547" alt="Screenshot 2023-07-13 at 17 27 40" src="https://github.com/saadeghi/daisyui/assets/18604525/0070746c-28cb-4b75-9940-4c3e836aa181">

_Screenshot showing z-index issue for collapse component in table. Notice the "No Data" paragraph component is correctly overlapped_

The z-index of the parent div with className `collapse` is set to auto (as are the child divs with classNames `collapse-title` and `collapse-content`)
<img width="277" alt="Screenshot 2023-07-13 at 17 29 01" src="https://github.com/saadeghi/daisyui/assets/18604525/57db4b60-fb1e-4f60-ac47-327fe266eb08">

I do notice the z-index of the radio input component is 1 however.
<img width="859" alt="Screenshot 2023-07-13 at 17 50 30" src="https://github.com/saadeghi/daisyui/assets/18604525/3fd933eb-fcdf-406b-afaf-a4b78644d9d3">

Short of setting the z-index of the table header artificially high (which causes other issues) I can't seem to fix this issue 

### What browsers are you seeing the problem on?

All browsers

**Comment by AdrianApan** [comment]
Just adding to this, I have the same z-index issue but when pairing accordion with a `menu menu-dropdown` component. Screenshot attached.

![CleanShot 2023-08-02 at 08 50 05@2x](https://github.com/saadeghi/daisyui/assets/69169115/d9386519-a2e4-4171-b11c-a23d8dbea18b)

**Comment by saadeghi** [comment]
The best way to deal with this would be adding z-index like `z-10` etc.  
It's not a good idea if we include the z-index rules in daisyUI components by default because it depends on the page content and layout which element should be on top. for example, you may want a dropdown to go op top of a navbar, or you may want it to be under the navbar.

I will add some z-index class names in doc examples of `dropdown` but just for the example so it should be obvious and easy to remove/change.

**Comment by godignorant2** [comment]
@AdrianApan https://sonata-voracious.github.io/VWckOn4KtPAxlkkYyaGRDSrtqamGYUh7tOmC5lwqRjWGO9YWc/
