### ISSUE TITLE
bug: Problems with Drawer

### ISSUE THREAD

**Issue by dbirak** [saadeghi/daisyui#2154]
### What version of daisyUI are you using?

3.0.25

### Describe your issue

Hello everyone. I have two problems with Drawer components. First problem is z-index digits from step component bigger than drawer overlay. Second problem is enabling click on Collapse when drawer is visible.

first problem:
![image one](https://github.com/saadeghi/daisyui/assets/41111309/535f547e-4a41-47ba-b110-c905c6dae456)

second problem:
https://github.com/saadeghi/daisyui/assets/41111309/6458cb70-25c0-4287-85f5-83954f61f684

### What browsers are you seeing the problem on?

Google Chrome (114.0.5735.199)

**Comment by saadeghi** [comment]
Can you provide a code example about the second problem? Because I can't reproduce that (I can't click the items under the overlay)

**Comment by mpearce-bain** [comment]
Wanted to confirm that I'm also observing the same issue with z-index items not being hidden being the overlay -- in this case using a `indicator-item` class on a `badge component`.

**Comment by MilesWuCode** [comment]
+1
https://github.com/MilesWuCode/nuxt3-demo
![截圖 2023-08-14 上午10 08 58](https://github.com/saadeghi/daisyui/assets/1192835/f5732901-057b-477f-9faf-f72c3c02f582)
![截圖 2023-08-14 上午10 09 11](https://github.com/saadeghi/daisyui/assets/1192835/b771fec1-ba99-4889-bd14-b80145fa5b39)

**Comment by CharlieEtienne** [comment]
This problem is due to transform css property applied on all drawer-side children. It creates a new stack and z-index no longer works correctly. More info here (https://philipwalton.com/articles/what-no-one-told-you-about-z-index/) and here (https://developer.mozilla.org/en-US/docs/Web/CSS/CSS_Positioning/Understanding_z_index/The_stacking_context)

The specific rule causing that is

```css
.lg\:drawer-open > .drawer-toggle ~ .drawer-side > *:not(.drawer-overlay) {
        transform: translateX(0%)}
```

The workaround would be to explicitly assign a position: relative and a z-index other than empty to the things that are layering unexpectedly.

Unfortunately, in my case, I need an absolute positionning on the element which behaves strangely...

**Comment by vivere-dally** [comment]
Any updates on this or other fixes besides what @CharlieEtienne mentioned?

**Comment by saadeghi** [comment]
This is no longer an issue because that CSS transform rule is removed from daisyUI last year.
