### ISSUE TITLE
Remove PRC flag

### ISSUE THREAD

**Issue by frankwwu** [saadeghi/daisyui#2160]
### Describe your issue

Hi @saadeghi, Simplified Chinese 中文 is not only spoken by people in PRC, but also people in Singapore, and many overseas-Chinese. Therefore, PRC flag can not represent Simplified Chinese 中文 at all.

**Comment by NikarashiHatsu** [comment]
Please stop making unnecessary issues/PRs related to flag representation. I'm pretty sure this related issue has been heard by the maintainer, and they will take action sooner or later.

#2156 has covered the best arbiter PR, but due to the previous geopolitical issues, it may not be merged immediately.

Just... stop... Seriously.
