### ISSUE TITLE
bug: Accordion donot close on clicking on arrow

### ISSUE THREAD

**Issue by AsadShah2003** [saadeghi/daisyui#2166]
Hey, I recently learned about Daisy UI and tried to implement a simple accordion, and it went smooth but there is a small problem all the accordion examples on the website proerply works for me but the accordion donot close when clicking back on the arrow? It only closes if I click on the other accordion item

**Comment by saadeghi** [comment]
This is how an accordion should work. As you see, it says `Click to open this one and close others`  

You can of course change the value of the radio input using JS if you want a different behavior, but since it is working with radio inputs, this is the expected behavior. when we choose a radio input, it gets enabled until we choose another one. clicking it again wont turn it off.

You might also want to use [`collapse`](http://localhost:3000/components/collapse/) instead (which is independent with each item)
