### ISSUE TITLE
Bug: Dropdown max-width is set to width of parent menu item, wrapping text unnecessarily 

### ISSUE THREAD

**Issue by kartzke** [saadeghi/daisyui#2182]
### What version of daisyUI are you using?

3.5

### Describe your issue

When using the [navbar component](https://daisyui.com/components/navbar/), the dropdown menu width seems to be set to the width of the parent item.  This causes reasonably short text in the dropdown menu to wrap unnecessarily.  

You can see this live in the DaisyUI docs, screenshot attached.   This is also happening on my project site, where the text used for the menu item in the dropdown is 15-20 characters long.

![image](https://github.com/saadeghi/daisyui/assets/713503/7657b2e0-35c5-4117-8197-d2e31067e2ff)

### What browsers are you seeing the problem on?

All browsers

**Comment by NikarashiHatsu** [comment]
<img width="1138" alt="Screenshot 2023-08-02 at 17 16 18" src="https://github.com/saadeghi/daisyui/assets/43662951/2e58642e-1856-49b0-a9a4-7f315821338e">

Your concern here is more towards the `dropdown` component rather than the `navbar`. I think it is really intended to change the width property based on how you'll use it. Example above, I added `w-52` class to the dropdown.

https://daisyui.com/components/dropdown/

**Comment by kartzke** [comment]
Yeah, I was able to override the width of the drop-down manually with a CSS class.  But the drop downs didn't work this way in DaisyUI 2.0, and maybe it's expected behavior in 3.0, but it feels like this might be a bug caused by #2148 and/or #1924, which were part of the 3.4 release:  

`menu item text now breaks by default if the text is long`

**Comment by saadeghi** [comment]
The solution to this is adding a width utility class like `w-52` as @NikarashiHatsu mentioned.  
We shouldn't break the text by default nor we shouldn't make the menu to grow by the content width because in both cases, it breaks layouts if the text is long. We shouldn't also set a default width because this design decision depends on the design and the content of the page.

So it's better to let people set their desired width using a utility class. I added a width utility class to the example in docs.
