### ISSUE TITLE
bug: click isn't registered in navbar's dropdown

### ISSUE THREAD

**Issue by Qqkyu** [saadeghi/daisyui#2191]
### What version of daisyUI are you using?

3.2.1

### Describe your issue

Hi, I've noticed a bug with clicking on rows in dropdown (in my case in navbar).
It works fine on my PC in chrome and firefox. However, when using safari on my phone (iPhone 13 pro) the click doesn't seem to be registered:

https://github.com/saadeghi/daisyui/assets/44360754/eb49458e-c23f-4982-bf09-4637cced2862

In the video above I try to click 3 times. However, every time dropdown closes and nothing happens.
For comparison, here is the correct behavior on my PC:

https://github.com/saadeghi/daisyui/assets/44360754/0edd1924-64df-4d8e-87bb-911ea4e176f0

I've also checked chrome on android and it seems to work fine there, also.

Here's a link to my site where I checked this: https://www.taboocardsapi.com/
I followed [this example](https://daisyui.com/components/navbar/#navbar-with-dropdown-center-logo-and-icon) when creating this navbar.

### What browsers are you seeing the problem on?

Safari

### Reproduction URL

https://www.taboocardsapi.com/

**Comment by NikarashiHatsu** [comment]
Hi @saadeghi, sorry for mentioning.
I think <details> didn't have the correct behavior on Safari.
It also happens in #2203

**Comment by NikarashiHatsu** [comment]
Update, sorry for not checking the documentation in advance.
As [this page](https://daisyui.com/components/dropdown/#method-2-using-label-and-css-focus) mentions, `We use a <label tabindex="0"> instead of a <button> because Safari has [a bug](https://bugs.webkit.org/show_bug.cgi?id=22261) that prevents the button from being focused.`.

Apparently, `tabindex="0"` should be implemented to the Dropdown as well. Check my screen record below, I added `tabindex="0"` to the `<ul>` component, and it works as intended.

https://github.com/saadeghi/daisyui/assets/43662951/e8545f6f-25df-4538-bb8a-5d12c416e02b

**Comment by Qqkyu** [comment]
> Update, sorry for not checking the documentation in advance. As [this page](https://daisyui.com/components/dropdown/#method-2-using-label-and-css-focus) mentions, `We use a <label tabindex="0"> instead of a <button> because Safari has [a bug](https://bugs.webkit.org/show_bug.cgi?id=22261) that prevents the button from being focused.`.
> 
> Apparently, `tabindex="0"` should be implemented to the Dropdown as well. Check my screen record below, I added `tabindex="0"` to the `<ul>` component, and it works as intended.
> 
>  2023-08-02.17-36-12.mp4

Thank you so much @NikarashiHatsu !! I haven't read that part before. It works flawlessly now
