### ISSUE TITLE
docs: Accessibility improvements of examples

### ISSUE THREAD

**Issue by nandi95** [saadeghi/daisyui#2221]
### Describe the issue

It would be really nice if the code examples on the documentation would include all relevant aria attributes, roles and anything concerning accessibility. This would mean people can just copy paste the examples with such attributes/best practices already set in place. Are there plans to do this?

### What browsers are you seeing the problem on?

All browsers

**Comment by NikarashiHatsu** [comment]
I really think there's no priority concerns about this yet, I was concerned about this as well. Thank you for coming up with this idea.

**Comment by saadeghi** [comment]
> include all relevant aria attributes, roles and anything concerning accessibility

Not all, but I'm positive with including only the necessary ones.

However a lot of times the aria attributes is part of the content or they should be implemented based on the context of your own page. For example aria labels should include a label that you provide based on your content. If I put a dummy text there, copy pasting it would be even worse because with a dummy text aria label, your code editor/linter/etc will not warm you to fix the dummy text I wrote for you but without an aria label, your editor will warn you and guides you to add it.

**Comment by MikaelJohnAndersson** [comment]
Just started using DaisyUI and are having the same concerns. It seems that the docs are suggesting somewhat dubious implementations from an accessibility perspective.

For instance, the [Drawer](https://daisyui.com/components/drawer/#drawer) should at least use an `aria-expanded` attribute.
Also, it doesn't seem like best practice to use checkboxes and empty `Label`-tags.

**Comment by saadeghi** [comment]
@MikaelJohnAndersson There's no way for daisyUI (as a CSS file to add/remove `aria-expanded` attribute conditionally) but you can add/remove that using JS based on your framework syntax.

**Comment by saadeghi** [comment]
Aria attributes added for alert, modal, tab, btm-nav, pagination and drawer examples in docs.   
(Most elements, being native HTML elements, are already accessible both with screen readers and keyboard navigation. For example, the `toggle` is native HTML checkbox. Some JS component libraries use `<div>`s to recreate that visual which would need `role="checkbox"` or `role="switch"`.)

If there are still missing attributes on docs examples, please create new issues for each one.
