### ISSUE TITLE
bug: Getting error `:global(...) must contain a single selector`

### ISSUE THREAD

**Issue by yashash-pugalia** [saadeghi/daisyui#2246]
### What version of daisyUI are you using?

v3.5.1

### Describe your issue

So I was adding daisyUI to a svelte app (using rollup)

Tailwind was installed using postcss, it works fine but as soon as I add daisyUI plugin inside the tailwind.config the build fails.

```js
[!] (plugin svelte) ValidationError: :global(...) must contain a single selector
src/App.svelte
1966:   border-radius: var(--rounded-btn, 0.5rem);
1967: }
1968:   :global(.table) :global(:where(th), :global(td)) {
                        ^
1969:   padding-left: 1rem;
1970:   padding-right: 1rem;
ValidationError: :global(...) must contain a single selector
```

I think it might be due to nesting of global in my app.svelte
```svelte
<style global lang="postcss">
  @tailwind base;
  @tailwind components;
  @tailwind utilities;
</style>
```

I tried moving the @tailwind things to a separate .css file and importing it to `app.svelte` but tailwind stopped working this way (no errors were coming though)

**Comment by saadeghi** [comment]
> I tried moving the @tailwind things to a separate .css file and importing it to `app.svelte` but tailwind stopped working this way (no errors were coming though)

Make sure you are importing the CSS file in your .svelte file.

The example StackBlitz link of SvelteKit here can help you:  
https://daisyui.com/docs/install/

Putting the whole Tailwind inside `<style global lang="postcss">` is not recommend because it adds another layer of CSS processing which is unnecessary and it forces SvelteKit to add `:global` to the selectors for no reason.

Let me know if you have any questions
