### ISSUE TITLE
bug: Tooltip icon appears on top of all the overlay

### ISSUE THREAD

**Issue by pasindu1997** [saadeghi/daisyui#2265]
### Describe your issue

The tooltip icon appears on top of all the overlays (eg modals, navigations)

![image](https://github.com/saadeghi/daisyui/assets/47180202/0692134b-343c-4b98-8157-0212785d5b59)
![image](https://github.com/saadeghi/daisyui/assets/47180202/daec2578-2a86-46a9-b9e5-ce01bda9761e)

### What browsers are you seeing the problem on?

Chrome, Edge

**Comment by saadeghi** [comment]
Use z-index class names like `z-[1]` or `z-20` etc. to put elements on top of each other.  
We shouldn't use default z-index values for the components by default because the decision that if something should be on top or on bottom depends on the content of the page.

Let me know if you have any questions.
