### ISSUE TITLE
bug: Next Js theme change issue

### ISSUE THREAD

**Issue by Tajammal-Maqbool** [saadeghi/daisyui#2285]
### What version of daisyUI are you using?

3.5.1

### Describe your issue

Hello,
I am using Next JS and DaisyUI. I found issue in change theme. Issue is that if I change the theme, store in local storage and when reload page then fetch it and change the theme using document.documentElement.setAttribute. But issue is that we need to use this (setAttribute) in useEffect hook therefore it load first default theme and then change on the useEffect, it is making a very clear glitch. 

![image](https://github.com/saadeghi/daisyui/assets/76564182/c7a9f597-a4ed-4b89-816b-54cffe232edd)

Please check this issue and let me know,

### What browsers are you seeing the problem on?

All browsers

**Comment by MubasharAhmad** [comment]
I am facing the same issue

**Comment by saadeghi** [comment]
This is not a bug from daisyUI. daisyUI doesn't have anything to do about JS and how frameworks run scripts (to dynamically change the theme or anything else)

The problem is, first your HTML loads then your JS reads the local storage and changes the theme. This wouldn't be a problem if the chosen theme is stored in the server.  

But if you want to read the chosen theme from local storage and you also want to avoid the flash of themes changing, you should read the local storage before loading the HTML.  
You can do so by adding something like this to your `<head>` tag:
```html
<script>try{document.documentElement.setAttribute('data-theme',localStorage.getItem('theme'));}catch(e){}</script>
```
This one line won't have any negative effect on loading time or the lighthouse score. I'm using something similar for daisyUI website as well.

([related discussion](https://github.com/saadeghi/theme-change/issues/3))

**Comment by Tajammal-Maqbool** [comment]
Thanks!
I have solved like this. I am using typescript and Next js
```jsx
import { Head, Html, Main, NextScript } from 'next/document';

export default function Document() {
    return (
        <Html lang="en">
            <Head>
                <script dangerouslySetInnerHTML={{
                    __html: `
                        try {
                            document.documentElement.setAttribute('data-theme', localStorage.getItem('theme') ?? 'light');
                        } catch (error) {
                            
                        }  
                    `
                }} />
            </Head>
            <body>
                <Main />
                <NextScript />
            </body>
        </Html>
    )
}
```

**Comment by MubasharAhmad** [comment]
> Thanks! I have solved like this. I am using typescript and Next js
> 
> ```js
> import { Head, Html, Main, NextScript } from 'next/document';
> 
> export default function Document() {
>     return (
>         <Html lang="en">
>             <Head>
>                 <script dangerouslySetInnerHTML={{
>                     __html: `
>                         try {
>                             document.documentElement.setAttribute('data-theme', localStorage.getItem('theme') ?? 'light');
>                         } catch (error) {
>                             
>                         }  
>                     `
>                 }} />
>             </Head>
>             <body>
>                 <Main />
>                 <NextScript />
>             </body>
>         </Html>
>     )
> }
> ```

Thanks it also worked for me.
