### ISSUE TITLE
docs: Which colors used for `:hover`?

### ISSUE THREAD

**Issue by merchako** [saadeghi/daisyui#2287]
### On which page do you see this issue?

https://daisyui.com/docs/colors/

### Describe the issue

Indicate which colors are intended for `:hover` (and other) states
* I noticed that `.primary-focus` is used for `.btn-primary:hover` even though the name suggests its intended for `.btn-primary:focus`.
* I noticed that `.base-300` is used for `.btn:hover` even though there's no indication in the docs which base color might be used for which state. 
* I'm probably missing a lot of additional patterns!

Is there a predictable pattern to know which color will be brightened or darkened in which circumstances? How does inverting the theme (light vs dark mode) affect that?

### What browsers are you seeing the problem on?

Safari, All browsers

**Comment by saadeghi** [comment]
>I'm probably missing a lot of additional patterns!  

There is no mathematic pattern and here's why:

daisyUI and every similar component library ever existed (Bootstrap, MUI, Chakra, etc...) they all offer styled components so you don't need to focus on smaller details. You can investigate every CSS rule and every color that is being used on components and you can change them but it's not something that should be documented because the general use case is, developers see variations of a button from the docs and pick one of them and use it.  

I can document every single CSS rule that is being used for each component but that wont be useful for the majority of developers. And those who seek these details, can easily see which CSS rules and which colors are being used from the devtools.  
For example in below picture, you can see `--b2` (`base-200`) color is being used as the background of `.btn` and `--bc` (`base-content`) as the text color. It's not something most developers would need to even know. They just use `btn` class and expect a button with a `distinguishable` color and a text with good contrast from the background color.  

<img width="1126" alt="3" src="https://github.com/saadeghi/daisyui/assets/7342023/63da9de6-78d9-475b-992c-ba1f3654c6fd">

All color names including `*-focus` color names (like `primary-focus`) are named from the UI design perspective (not the CSS `:focus` state).  
- Some libraries use names like `primary-darken` or `primary-lighten`. That's problematic because the lightness can be different in dark and light themes. `primary-lighten` name suggests a lighter version of `primary` but we may need a lighter color on light theme and a darker color on dark mode. So that name wouldn't be theme-agnostic.  
- Some libraries use numbered variations like `primary-100`, `primary-200`, etc... That would also create the same problem.
- In daisyUI we use `primary-focus` as a focused version of the color. It can be used in different situations. It's not just about buttons and their CSS state. For example when you have 3 divs with `primary` color and you want one of them to stand out, you can use `primary-focus`. With buttons, we need that visual color change when the button is hovered so we apply `primary-focus` color when it's hovered.

In conclusion, `primary-focus` color name shouldn't be confused with the CSS `:focus` state. It's a color name (just like Tailwind CSS color names) and it can be used anywhere.

**About base colors:**  
Generally, `base-*` colors are used for the components that needed a color differentiation form the background color. For example:
- The default `.btn` uses `base-200` as the background, and uses `base-300` as hover color.  
- The default `.alert` uses `base-200` as the background. It doesn't need a hover or focus color.
- The default `.kbd` uses `base-200` as the background.
- Only some components need color variations like `primary`, `secondary`, etc...
- Most of the components don't even need a color as background.

There is no mathematic pattern. And it's not just about daisyUI. All component libraries use colors in a way to create a visual harmony.  

Let me know if you have any questions.

**Comment by merchako** [comment]
Thank you, @saadeghi . You've answered most of my questions. It was especially to helpful to understand that there's no relationship intended between `*-focus` and CSS `:focus`.
