### ISSUE TITLE
bug: scale not applied when 

### ISSUE THREAD

**Issue by BenoistP** [saadeghi/daisyui#2316]
### What version of daisyUI are you using?

3.6.3

### Describe your issue

Hello,

It seems scale is not applied to svg/icons in combination with swap-on

<label class="swap swap-rotate">

  <input type="checkbox" />

  
<svg class="swap-on fill-current w-10 h-10 scale-50 hover:scale-100" xmlns="http://www.w3.org/2000/svg" viewBox="0 0 24 24"><path d="..."/></svg>
  

  
  <svg class="swap-off fill-current w-10 h-10 scale-50 hover:scale-100" xmlns="http://www.w3.org/2000/svg" viewBox="0 0 24 24"><path d=".."/></svg>

</label>

swap-off fill-current w-10 h-10 scale-50 hover:scale-100

### What browsers are you seeing the problem on?

Chrome, Firefox, Other

### Reproduction URL

https://codepen.io/BenoistP-/pen/bGOejre

**Comment by saadeghi** [comment]
Use `scale-50 hover:scale-100 transition-transform` class names on `swap`. Not the icons.  

The reason it's not working the way you used it, is that both icons are (should be) on top of each other in the same place because that's the only way to have a smooth fade (or rotate) effect where first icon fades out and at the same time the second icon fades in. The second icon is no replacing the first icon. They are in the same position, and one is hidden.

Let me know if you have any questions.

**Comment by BenoistP** [comment]
My bad ...
Thanks for your prompt support :+1:
