### ISSUE TITLE
bug: File input is cut off at the botton

### ISSUE THREAD

**Issue by thonkinator** [saadeghi/daisyui#2360]
### What version of daisyUI are you using?

3.7.6

### Describe your issue

When using the `file-input` class, the bottom of the file input is slightly cut off:
<img width="1425" alt="image" src="https://github.com/saadeghi/daisyui/assets/51034477/48f48c86-61b1-4c8d-9005-02b701428f44">
(notice how the bottom left border curve is cut off at the bottom)

This issue is also present, and much more noticeable, when the input has a color/border:
<img width="1482" alt="image" src="https://github.com/saadeghi/daisyui/assets/51034477/ea85b5bb-0f53-4502-9110-0c3057264b36">

From testing, when using a file input with a border, this issue only seems to show up with larger font sizes. I suspect that the background is always some proportion smaller than it should be, but for smaller font sizes the difference is so small that it hides behind the border.

### What browsers are you seeing the problem on?

Chrome, Safari, Firefox

### Reproduction URL

https://play.tailwindcss.com/2LNOfP77Vh

**Comment by flomero** [comment]
is there a specific reason for `h-[2.875rem]` on `.file-input::file-selector-button` @saadeghi?
seems like using `h-full` instead should fix the issue

(unfortunately i can't check it right now, because i somehow always get `Internal server error: [postcss] Cannot find module` while trying to import an updated local build. any ideas what the reason could be?)

**Comment by thonkinator** [comment]
@flomero manually adding this to the CSS does seem to fix the issue
https://play.tailwindcss.com/9rkbJovwAr?file=css
