### ISSUE TITLE
bug: Daisy should refrain from logging when tailwind is used without an output file (tailwind logs the css)

### ISSUE THREAD

**Issue by ckissane** [saadeghi/daisyui#2372]
### Describe your issue

When tailwind css is called without an output file, daisy's logs pollute the generated css stream. 
Although daisy's logging can be disabled, ideally daisy should never log when the css output is expected to be consumed from the std out, rather than a file.

#### Examples:

With a file output option: (Everything ok)
```
tailwind --input style/main.css --config ./tailwind.config.js --output out.css
```

Consuming std out: (Logs pollute output)
```
tailwind --input style/main.css --config ./tailwind.config.js |  # pipe to some command here
```
Or:
```
tailwind --input style/main.css --config ./tailwind.config.js > out.css
```

See: https://github.com/leptos-rs/cargo-leptos/issues/136 for an example of downstream failure.

#### Proposed fix:
auto disable logs when tailwind has no output file option

### What browsers are you seeing the problem on?

All browsers

**Comment by saadeghi** [comment]
**Why there's a console.log?**  
daisyUI is basically a `.js` file, included to Tailwind CSS as a plugin. As a JS file, it can also print to console.  
It is crucial for daisyUI to have that console.log enabled by default because there's no other way to communicate with the developer. No one is running a Node file from daisyUI and daisyUI doesn't have a CLI. It's a plugin and it works via Tailwind CSS. So the console.log is the only way to inform the developer about how many themes are enabled, how to use RTL mode, how to use prefix config, etc.

>auto disable logs when tailwind has no output file option

I'm not sure if there's a way to do that. As far as I know, there's no API to know what is the output.  
And even if it was, other than using Tailwind CLI, there are many ways to generate the CSS file. It's not possible for a tailwind CSS plugin (which is not running independently - it can only use the provided API to do specific jobs) to guess what is the build tool and how to build tool is handling the output (is it a file or not)

>Of course daisy is engaging in bad practice and should ideally auto disable logging if tailwind is not given an explicit output file.

I would be happy to do anything to prevent such issues. There's not a way on my end as far as I know (other than providing an option to disable the logs)  
However I think "bad practice" is blindingly piping the result from a command, not simply having a `console.log` in a JS file.  
How can a build tool be so sure the result is expected CSS (or any other string)? It can be an error if there's a bug somewhere the build tool would put the error message in a CSS style at the end. That's bad practice.
