### ISSUE TITLE
docs: How to color whole join group red if form field has an error

### ISSUE THREAD

**Issue by maxfriedmann** [saadeghi/daisyui#2383]
### Describe the issue

A focused input field inside a join group that has `input-error` actually looks really good: 

![image](https://github.com/saadeghi/daisyui/assets/2809483/0fd90da1-0926-4ba0-8194-205b83f16998)

Unfocused it doesn't: 

![image](https://github.com/saadeghi/daisyui/assets/2809483/50400d02-b7ad-468f-8b21-fe763a192a69)

I wonder if I am doing something wrong. Here's my simplified html:

```html
<div class="form-control w-full">
  <div class="join">
    <div class="dropdown join-item">
      <!-- drop down stuff -->
    </div>
    <input
      type="text"
      class="input input-bordered w-full join-item"
      [required]="required"
      [ngClass]="{ 'input-error': hasErrors }"
    />
  </div>
</div>
```

How can I achieve that the whole join has a red border?

### What browsers are you seeing the problem on?

All browsers

**Comment by saadeghi** [comment]
> Unfocused it doesn't

You can fix this by adding `isolate` class to the `<input>`

The reason:  

`join` class puts all the items next to each other and also merges their border using `margin-left: -1px` this allows us to have a `1px` border between items when both have a border.  
Here's an example of merging borders and not merging borders.  
An `isolate` class can prevent the input to go under the sibling element.
<img width="1016" alt="Screenshot 2023-10-02 at 20 18 08" src="https://github.com/saadeghi/daisyui/assets/7342023/47de1edc-12f8-414f-a292-13d18e23a29b">


>How can I achieve that the whole join has a red border?  

I wouldn't recommend that. If there's a drop down and an input, the dropdown doesn't have an invalid value. The input does so it makes more sense to set red color for the invalid input only.  
However if you really want to have borders on the `join`, you can use `border border-error` class names to the `join` (instead of using `input-error` on the `<input>`)


Let me know if you have any questions.

**Comment by maxfriedmann** [comment]
The point about not all join'ed inputs being invalid is absolutely true, I did not think about that. Thank you for the hint with `isolate`, I will play around a bit towards this solution.

Many thanks for your time, highly appreciated!
