### ISSUE TITLE
bug: DaisyUI colors in themes are not perfectly applied

### ISSUE THREAD

**Issue by 0xtlt** [saadeghi/daisyui#2478]
### What version of daisyUI are you using?

3.9.4

### Which browsers are you seeing the problem on?

All browsers

### Reproduction URL

https://play.tailwindcss.com/eUmbFJcv1M

### Describe your issue

Hi,

When you define colors in daisy ui with an hexcode (primary, secondary, content etc..., all of them), Daisy UI parse them in HSL but the HSL color is not the equivalent of the hex one.

![CleanShot 2023-11-07 at 13 47 43@2x](https://github.com/saadeghi/daisyui/assets/31560900/3d4eddc7-07cc-4b6b-aafd-2eafb9b1f200)

I debugged DaisyUI and found it use COLORD as a dependency for color management and then I made a test on https://npm.runkit.com/colord with the following code:
```javascript
var { colord } = require("colord")

const hslColor = colord("#022100").toHsl();
const hexColor = colord(hslColor).toHex();

const obj = {
    hslColor,
    hexColor
};
```

And the result of the obj is:
```javascript
Object {hslColor: Object {h: 116, s: 100, l: 6, a: 1}, hexColor: "#021f00" }
```

![CleanShot 2023-11-07 at 13 50 52@2x](https://github.com/saadeghi/daisyui/assets/31560900/75b47ccc-000a-4b30-853b-069ff1294632)

Then the parsed HSL color is not correct, I made another’s test on my side and found the problem is COLORD round the values in HSL.

because HSL color of `#022100` is not `{h: 116, s: 100, l: 6, a: 1}` but `{h: 116,.4 s: 100, l: 6.5, a: 1}` (I rounded it but this HSL gives the good hex code).

So I made this function to wrap my DaisyUI theme to fix this as a temporary solution:

```javascript
function HEXtoRGB(hex) {
  if (hex.length === 3) {
    hex = hex
      .split('')
      .map(function (h) {
        return h + h;
      })
      .join('');
  }
  let r = parseInt(hex.substring(0, 2), 16);
  let g = parseInt(hex.substring(2, 4), 16);
  let b = parseInt(hex.substring(4, 6), 16);
  return [r, g, b];
}

function RGBtoHSL(r, g, b) {
  (r /= 255), (g /= 255), (b /= 255);
  let max = Math.max(r, g, b),
    min = Math.min(r, g, b);
  let h,
    s,
    l = (max + min) / 2;

  if (max === min) {
    h = s = 0; // achromatic
  } else {
    let d = max - min;
    s = l > 0.5 ? d / (2 - max - min) : d / (max + min);
    switch (max) {
      case r:
        h = (g - b) / d + (g < b ? 6 : 0);
        break;
      case g:
        h = (b - r) / d + 2;
        break;
      case b:
        h = (r - g) / d + 4;
        break;
    }
    h /= 6;
  }
  return [(h * 360).toFixed(1), (s * 100).toFixed(1), (l * 100).toFixed(1)];
}

function hexToHSL(hex) {
  let rgb = HEXtoRGB(hex.replace('#', ''));
  return RGBtoHSL(rgb[0], rgb[1], rgb[2]);
}

function Colors(colors) {
  let newColors = { ...colors };

  for (const [key, value] of Object.entries(colors)) {
    let isCSSVariable = key.startsWith('--');
    let contractionKey = isCSSVariable
      ? key
      : '--' +
        key
          .split('-')
          .map((part) => part.charAt(0))
          .join('');

    if (!newColors.hasOwnProperty(contractionKey)) {
      if (/^#[0-9A-F]{6}$/i.test(value)) {
        newColors[contractionKey] = hexToHSL(value)
          .map((value, index) => (index === 0 ? value : `${value}%`))
          .join(' ');
      } else if (!isCSSVariable) {
        newColors[contractionKey] = value;
      }
    }
  }

  return newColors;
}
```

Example of what my function returns:
![CleanShot 2023-11-07 at 14 05 12@2x](https://github.com/saadeghi/daisyui/assets/31560900/4bf5f104-7ecc-4395-b98a-8c40e5c8dd49)

Then you can wrap your theme with this function to define the HSL colors var well

Thank you

**Comment by saadeghi** [comment]
Thanks for the details and thanks for the investigations.

Unfortunately `colord` package has some inaccuracies with color values.  

However it's important to know, daisyUI has to convert the color value to a specific model and we can't directly put the input color into the theme because that way, the opacity utility classes won't work and also the automatic color generation (to automatically generate foreground colors) would stop working. And also it's important to know when we convert the color to another model, sometimes a color value in a model equals to multiple values in another model (because the 2D/3D shape of the color model is different). It's visually the same color.

You can also set a HSL color value directly in the config (instead of hex), to avoid `colord` changing the values the way it processes the color.

In daisyUI version 4.0 we're replacing `colord` package with `culori` and we're also moving from HSL color model to OKLCH which is more accurate, and allows us to use the new P3 gamut colors.
