### ISSUE TITLE
bug: Can't overlay full screen when have two drawers

### ISSUE THREAD

**Issue by hungtp1996nd** [saadeghi/daisyui#2484]
### What version of daisyUI are you using?

v3.9.4

### Which browsers are you seeing the problem on?

Chrome, Edge

### Reproduction URL

https://daisy-drawer-double.vercel.app/

### Describe your issue

In my case, there will be 2 blocks left and right, corresponding to each block will have 1 drawer displayed. When I turn on the drawer from the left, it seems like the screen overlays only the left half, but when I turn it on from the right, that doesn't happen.
I have attached the vercel app link for this bug and here is github link for this issue: https://github.com/hungtp1996nd/daisy-drawer-double

**Comment by saadeghi** [comment]
Each drawer can only fill it's own space.  

Since you don't want both drawers to be open at the same time, an efficient way would be having 1 drawer and changing its content and position using JS.

Another way is to put one drawer inside the content of the other drawer. This you can have both of them work together side by side: https://play.tailwindcss.com/lF2MVBfbVw

**Comment by hungtp1996nd** [comment]
@saadeghi Really appreciate your great help
