### ISSUE TITLE
bug: Using Tailwind forms plugin breaks DaisyUI components like Toggle, Swap.

### ISSUE THREAD

**Issue by 0xPiyush** [saadeghi/daisyui#2529]
### What version of daisyUI are you using?

v4.0.7

### Which browsers are you seeing the problem on?

All browsers

### Reproduction URL

https://play.tailwindcss.com/IIWW8U8Zeq

### Describe your issue

Using the Tailwind Forms plugin with DaisyUI breaks the mentioned components, the toggles do not animate and just behave weirdly in general, the Swap component has the checkbox visible when it shouldn't be.

**Comment by saadeghi** [comment]
There was an attempt to override the forms styles. 
But stone of the compatible styles in version 4.0.0 was preventing utility classes to apply changes. I had to undo it in the next updates 4.0.x  
The problem is, the forms plugin styles have a high specificity and if we override those styles with a higher CSS specificity, then it would be impossible to modify elements with normal Tailwind CSS utility classes.

At this point I don't have any solution for that.  

There's no reason to have daisyUI and the forms plugin together on a project because both do the same job but if you really want both on the same project, you can use the [`strategy: 'class'` config](https://github.com/tailwindlabs/tailwindcss-forms#using-only-global-styles-or-only-classes) so it only applies style to the elements with specific class name (not all form elements)
