### ISSUE TITLE
A11y issues

### ISSUE THREAD

**Issue by IAPBenediktZwoelfer** [saadeghi/daisyui#2590]
### What version of daisyUI are you using?

4.4.12

### Which browsers are you seeing the problem on?

Chrome

### Reproduction URL

https://stackblitz.com/edit/daisyui-sveltekit-f7y6p2?file=src%2Froutes%2F%2Bpage.svelte

### Describe your issue

There are some issues with how the library uses the **label** element.

Example from the docs:

```
     <label class="label">
     	<span class="label-text">This is a label</span>
     </label>
     <select class="select select-bordered w-full max-w-xs">
     	<option disabled selected>Who shot first?</option>
     	<option>Han Solo</option>
     	<option>Greedo</option>
     </select>
```

This produces a A11y error: "_A11y: A form label must be associated with a control_"

When putting the select element into the label we get the issue, that the label is displayed left to the input, not on top:
```
     <label class="label">
     	<span class="label-text">This is a label</span>
     	<select class="select select-bordered w-full max-w-xs">
     		<option disabled selected>Who shot first?</option>
     		<option>Han Solo</option>
     		<option>Greedo</option>
     	</select>
     </label>
``` 
As i am building a big platform and a lot of forms so i don't want any hacky solutions, would be good to know what the creators intended. Thanks!

**Comment by saadeghi** [comment]
This is not an issue from the library itself, but rather from the example on the docs.  

Adding an ID for the `<select>` would fix it:  
https://stackblitz.com/edit/daisyui-sveltekit-4puoch?file=src%2Froutes%2F%2Bpage.svelte
```diff
<div class="form-control">
+  <label class="label" for="my-id"> 👈 Use the same ID here
    <span class="label-text">Card Number</span>
  </label>
+  <select class="select select-bordered w-full max-w-xs" id="my-id"> 👈 Use ID for select
    <option disabled selected>Who shot first?</option>
    <option>Han Solo</option>
    <option>Greedo</option>
  </select>
</div>
```
Read more: https://developer.mozilla.org/en-US/docs/Web/HTML/Element/label

The ID is something developers must add themselves because the ID must be unique and it must be used based on the context of the page.  

I'm going to add a sample ID in the docs example today.

Let me know if you have a question.

**Comment by saadeghi** [comment]
I understand.  
It's better for accessibility to generate unique IDs for the fields because that way, screen readers would know exactly which label is associated with which input. (This is not about daisyUI. It's just how HTML must be written)

Another thing you can do is to use a div instead of label and use the label class for the div. It may look funny but it makes sense because if you can't use unique IDs for the inputs wrapping them inside a label is the only way. While the `label` class from daisyUI is not necessarily for `<label>` element. It's for the visual label on top of the input.

```html
   <label>
     <div class="label">
     	<span class="label-text">This is a label</span>
     </div>
     <select class="select select-bordered w-full max-w-xs">
     	<option disabled selected>Who shot first?</option>
     	<option>Han Solo</option>
     	<option>Greedo</option>
     </select>
   </label>
```
