### ISSUE TITLE
bug: drawer-end makes horizontal scrollbar permanently visible.

### ISSUE THREAD

**Issue by kobe-ra** [saadeghi/daisyui#2622]
### What version of daisyUI are you using?

v4.4.19

### Which browsers are you seeing the problem on?

Chrome

### Reproduction URL

https://daisyui.com/components/drawer/#drawer-that-opens-from-right-side-of-page

### Describe your issue

Horizontal scrollbar is permanently visible when using `drawer drawer-end`.
This issue is also visible in the docs.

![image](https://github.com/saadeghi/daisyui/assets/32091524/649b71d4-51a5-47f5-a0b4-f92ff41a3db3)

**Comment by l1c2d3** [comment]
I'm observing the same behavior in Edge. Firefox renders correctly.
I'm using Next.js 14, tailwindcss 3.3.6, daisyui 4.4.19

I'm using drawer drawer-end in a root layout and that's when this happens. If I change drawer drawer-end to a template or page, the scroll disappears, but the drawer slides from the left, instead of right.

Also, I'm observing some styles not rendering correctly in Edge (oversized components) but correct in Firefox.
This was working fine last week, so this bug must have been introduced in the most recent versions.

I will test with previous releases.

**Comment by gagansuie** [comment]
hi! solved the issue by adding overflow-x-hidden tailwind class to <div class="drawer-side"

**Comment by LanceMoe** [comment]
> hi! solved the issue by adding `overflow-x-hidden` tailwind class to `<div class="drawer-side"`

In my project, by adding `overflow-x-hidden` can be solved on the desktop, but on the mobile phone, the entire screen can be swiped left or right through the touch screen.

After returning to 4.4.14, this problem was solved.

**Comment by gagansuie** [comment]
If that's the case, you can do md:overflow-x-hidden or something to do this fix on certain screen sizes.

**Comment by gereltod-g** [comment]
Using version 4.4.19, this error is still occurring. It's not noticeable on macOS Chrome, but on Windows, an unscrollable scrollbar appears

**Comment by bayasdev** [comment]
> md:overflow-x-hidden

+1
