### ISSUE TITLE
bug: button no-animation doesn't work when button apply style of translate-x or translate-y 

### ISSUE THREAD

**Issue by blueskoo** [saadeghi/daisyui#2658]
### What version of daisyUI are you using?

4.4.19

### Which browsers are you seeing the problem on?

Chrome

### Reproduction URL

https://play.tailwindcss.com/oSX5TWmUqW

### Describe your issue

As mentioned Tailwind Play url:
```
<button class="btn no-animation translate-y-1/2">Should no animation</button>
```

**Comment by saadeghi** [comment]
`no-animation` class disables the animations from daisyUI, not your custom transforms.  
Since both `scale` (used by daisyUI for button press) and `translate` from your utility class are CSS transforms, your `translate-y-1/2` class works on default state but not on focus.

You can use this: `translate-y-1/2 focus:active:translate-y-1/2`: https://play.tailwindcss.com/mLKCQYQLMG

**Comment by blueskoo** [comment]
Thank you and appreciate your help.
