### ISSUE TITLE
inline class not behaving the same as @apply directive

### ISSUE THREAD

**Issue by atavistock** [saadeghi/daisyui#274]
I'm not sure if this is a known issue, but this is not the behavior I would expect:

`<div class="menu horizontal">` generates a horizontal menu just fine.  As it seems to apply a nested selector like `menu.horizontal`

but putting the same in a css file like

`.bottom-menu { @apply menu horizontal }`
and then
`<div class="bottom-menu">`

doesn't seem to work, even if placed inside a `@layer`  block

**Comment by saadeghi** [comment]
Most classes work like this.
example: https://play.tailwindcss.com/P1FdItpq5l  

However, some combinations are not supported because of the way Tailwind extracts those styles.  
When we use `.bottom-menu { @apply menu }` it takes the `.menu` style and adds it under `.bottom-menu`  
but when we use `.bottom-menu { @apply menu horizontal }` it can't take the style because the original style is a child selector (`.menu.horizontal`)

**Comment by atavistock** [comment]
Right, I found it unexpected and counter intuitive.  I understand why its not working, and doing `<div class="custom-menu horizontal">` works fine.
