### ISSUE TITLE
bug: Steps with a hidden element

### ISSUE THREAD

**Issue by robsontenorio** [saadeghi/daisyui#2740]
### What version of daisyUI are you using?

4.5.0

### Which browsers are you seeing the problem on?

Chrome, Safari

### Reproduction URL

https://play.tailwindcss.com/kVDcAHbWno

### Describe your issue

Steps with a hidden element has a weird behavior. Is this expected?

Actually it does not look so bad and accidentally  I liked!

If you think it is not a bug, please, close this issue.

<img width="1215" alt="image" src="https://github.com/saadeghi/daisyui/assets/118955/d1fda064-6671-4938-a6b6-07809d6cb29f">

**Comment by saadeghi** [comment]
The problem here is not being `hidden`, it's that the second item in code is meant to be styled as first item (it shouldn't have a line at left) and in CSS, `.step:first-child` is getting that style, but when you have another element as first child, the visual first child (which is the second child in code) can't get the expected style.

I don't think I can do anything about this in style because there's no `:first-child-with-x-class` selector in CSS 😅

Maybe you can render that element conditionally instead of visually hiding it? 🤔

Let me know if you have a question.
