### ISSUE TITLE
bug: Class "hidden" doesn't work on card with image overlay

### ISSUE THREAD

**Issue by imam-mln** [saadeghi/daisyui#2755]
### What version of daisyUI are you using?

v4.6.0

### Which browsers are you seeing the problem on?

Chrome

### Reproduction URL

https://daisyui.com/components/card/#card-with-image-overlay

### Describe your issue

When I try to play with responsive websites at various sizes by using card with image overlay, then I realize that it is not affected at all by displays like "hidden" or maybe the class "image-full cannot be applied to responsive class (sm,md,lg,xl). Is this a bug or is there a way to work around it?

**Comment by saadeghi** [comment]
How are you using `hidden` class? Can you provide a code example on [Tailwind Play](https://daisyui.com/tailwindplay/)?

**Comment by imammay24** [comment]
> How are you using `hidden` class? Can you provide a code example on [Tailwind Play](https://daisyui.com/tailwindplay/)?

i'm just add class **"hidden"** and it doesn't work anything although in sm/md/lg/xl view

<div className="card w-96 bg-base-100 shadow-xl image-full **sm:hidden**">
  <figure><img src="https://daisyui.com/images/stock/photo-1606107557195-0e29a4b5b4aa.jpg" alt="Shoes" /></figure>
  <div className="card-body">
    <h2 className="card-title">Shoes!</h2>
    <p>If a dog chews shoes whose shoes does he choose?</p>
    <div className="card-actions justify-end">
      <button className="btn btn-primary">Buy Now</button>
    </div>
  </div>
</div>

**Comment by saadeghi** [comment]
The selector for modifier class `image-full` has and must have a higher CSS specificity than `card ` because it should have higher priority. For the same reason it is also having a higher CSS specificity than `hidden` class.

This limitation will be fixed in the next major version. I can't fix it for the current version of daisyUI because it may be a breaking change for some layouts and may break a few apps.

Until it gets fixed, as a workaround, you can use `sm:[.card&]:hidden` or `sm:!hidden` instead of `sm:hidden`.

Let me know if you have a question.
