### ISSUE TITLE
bug: btn-square and btn-circle rendered identical?

### ISSUE THREAD

**Issue by ChenaLee** [saadeghi/daisyui#2771]
### What version of daisyUI are you using?

v4.6.0

### Which browsers are you seeing the problem on?

Chrome Version 120.0.6099.129

### Reproduction URL

https://daisyui.com/components/button/

### Describe your issue

On your website: https://daisyui.com/components/button/

<img width="748" alt="Screen Shot 2024-01-17 at 10 27 53 PM" src="https://github.com/saadeghi/daisyui/assets/24197975/54ea8282-b836-430c-ad30-1947dc960531">

Are those two (btn-square, btn-circle) both supposed to look like that? Looks identical. Same happened when I tried to use btn-square.

**Comment by saadeghi** [comment]
This only happens for themes that have big border-radius (`cupcake`, `valentine`, `forest` and `pastel`)

`btn-square` is not about the _square shape_ necessarily because button border radius changes based on themes. The button is a square but since the theme has a big border radius, it becomes a circle. It's an expected behavior.

When the border radius of button is big, all buttons gain round shape, including the square button. It would look weird if all buttons are rounded and then there's one of them with sharper edges.

Let me know if you have a question.
