### ISSUE TITLE
Tooltip overflowing

### ISSUE THREAD

**Issue by effen1337** [saadeghi/daisyui#280]
![image](https://user-images.githubusercontent.com/37754407/139685472-a5a3158d-9631-4fa1-87fb-3b35da4ab298.png)

Any idea to not let the tooltip overflow but instead fit the actual page?

**Comment by saadeghi** [comment]
@effen1337 well... you have a small icon at the corner of page and a long text on tooltip. The tooltip is at top center so it will go off page.

There are 2 options:
- Add [`tooltip-left`](https://daisyui.com/components/tooltip) class so tooltip opens to left (instead of top)
- If you're using [JIT](https://tailwindcss.com/docs/just-in-time-mode), control the width of tooltip using `before:` utility. [[example](https://play.tailwindcss.com/WApeOVCy8w)]

**Comment by effen1337** [comment]
It happens on mobile sizes but your before: utility advice helped, thanks

**Comment by dmelli** [comment]
Hi, I having the same issue with small screens. Can you share how you resolved that? 
Thanks you.

<img width="323" alt="Screen Shot 2022-01-31 at 02 30 15" src="https://user-images.githubusercontent.com/26146512/151743672-0756fdc6-d2fd-4930-90f6-2f0c96f84f15.png">

**Comment by saadeghi** [comment]
https://play.tailwindcss.com/WApeOVCy8w
