### ISSUE TITLE
bug: Z-index issues with the tooltip component

### ISSUE THREAD

**Issue by nbran** [saadeghi/daisyui#2823]
### What version of daisyUI are you using?

4.6.1

### Which browsers are you seeing the problem on?

Firefox, Other

### Reproduction URL

https://stackblitz.com/edit/vitejs-vite-v8afg3?file=src%2FApp.tsx

### Describe your issue

The Tooltip component appears behind the pinned row table component.

https://github.com/saadeghi/daisyui/assets/25080013/f1388899-17d4-4852-b78e-8d166dd330ff

**Comment by saadeghi** [comment]
By default it has no z-index.  but you can add a z-index like `z-10` or (any value) to the tooltip.
z-index is something you should define based on the content of the page because in some cases you may want things to be placed under tooltip and sometimes you may want them to be over tooltip. It's not a good idea for daisyUI to make decisions about that.

Let me know if you have a question.
