### ISSUE TITLE
Weird console logging output

### ISSUE THREAD

**Issue by Wkasel** [saadeghi/daisyui#283]
#### Issue description

Seeing a weird bug with the daisy UI logger printing on repeat in next.js on dev.

`🌼 daisyUI components 1.16.1  https://github.com/saadeghi/daisyui
  ✔︎ Including:  base, components, themes[22], utilities`

#### Steps to reproduce the issue

1.  setup a basic Next.JS boilerplate with Tailwind, and styled components, in my case [superplate](https://pankod.github.io/superplate/)
2. Added Daisy UI
3. Ran `Yarn Dev`

#### What's the expected result?

- Maybe one output, not repeated

#### What's the actual result?

- Saw many repeat output in dev console

#### Additional details / screenshot

- ![Screenshot](https://raw.githubusercontent.com/Wkasel/daisy-ui-demo/main/screenrecording.gif)
- [Repo](https://github.com/Wkasel/daisy-ui-demo)

**Comment by Wkasel** [comment]
I realized that screen recording might cut it short - [here is a full recording of what happens](https://imgur.com/a/nhrq6RL)

**Comment by saadeghi** [comment]
@Wkasel you can [disable logs from config](https://daisyui.com/docs/config)

**Comment by Wkasel** [comment]
Ahh, ok. No problem. Any idea why this was happening though? Is that expected behavior?

**Comment by saadeghi** [comment]
@Wkasel No. It's not expected behavior. daisyUI only prints the the log once (showing version number and shows what is included based on the config) when the CSS file is built.  
However, all build tools don't work the same way when they are watching the changes.  
- It could be the build tool, running the build process every second (I'm not sure why)
- Or it could be the problem with watch list files path. make sure the list of files to watch only includes the source files. because if it also includes the dist files, it goes in a loop.

I'm not sure about the reason why the CSS build is running multiple times on your build,  
But the fastest way is to disable the logs config. It's just there to show the version and included files. nothing more.
