### ISSUE TITLE
bug: Modal cannot modify rounding in middle

### ISSUE THREAD

**Issue by MarcGodard** [saadeghi/daisyui#2841]
### What version of daisyUI are you using?

Newest

### Which browsers are you seeing the problem on?

Firefox

### Reproduction URL

See screenshots

### Describe your issue

![image](https://github.com/saadeghi/daisyui/assets/5016637/554a2e37-350c-41d5-b796-32452fd7e684)

![image](https://github.com/saadeghi/daisyui/assets/5016637/2d09500b-6d01-4c19-8999-3432523bd472)

![image](https://github.com/saadeghi/daisyui/assets/5016637/eb42d5b3-d68d-406f-b43e-3c37a5aa6b80)

As you can see the addition to rounding isn't being applied when in the middle.

**Comment by saadeghi** [comment]
> ### Reproduction URL
> See screenshots

Please provide a reproduction URL.
The reason I ask for reproduction URL is not to prove a problem exists. Is so I can run the code and see the source code and config and compare it with the result styles on browser so I can find what is causing the issue. 

I don't see the problem: https://play.tailwindcss.com/tjSvwAW0F3

**Comment by MarcGodard** [comment]
@saadeghi not sure why you closed the issue...

https://play.tailwindcss.com/OkrCkTCmOM

There is your code. You are right, I will provide code from now on.

Change the rounded and nothing changes on the modal unless you shrink it to small

**Comment by saadeghi** [comment]
>I will provide code from now on  
Thank you. Without a reproduction code, I would have no idea about how you're using the class names, what markup you're using and how's your build config.  

> https://play.tailwindcss.com/OkrCkTCmOM

Here you can use `sm:rounded-lg` instead of `rounded-lg`.  
The reason is, you have `modal-bottom` by default. It puts the modal to the bottom of page and sets border radius to the top only. Then for screens larger than `sm` you have `sm:modal-middle` to put it in the middle of page. So if there's a different style for `sm`, `sm:` prefix is needed for `rounded-lg` as well.

https://play.tailwindcss.com/Xzbs0cexpw

**Comment by MarcGodard** [comment]
Ahhh I see, kinda quirky but I understand.
