### ISSUE TITLE
bug:  Theme toggle does not default to dark mode if the system/browser is already in dark mode

### ISSUE THREAD

**Issue by indcoder** [saadeghi/daisyui#2847]
### What version of daisyUI are you using?

4.6.0

### Which browsers are you seeing the problem on?

Chrome, Edge

### Reproduction URL

https://daisyui.com/components/theme-controller/

### Describe your issue

We are using the theme controller to control between the light and dark theme

I noticed while the theme controller works as expected if the system/browser is in light mode. But if its not, the theme controller does not default to the dark mode. 

<img width="883" alt="image" src="https://github.com/saadeghi/daisyui/assets/2099300/fc44e85e-4feb-4330-894f-576f5f027e02">

Also when  I change the value to dark when the browser is in dark mode by default  the
<img width="914" alt="image" src="https://github.com/saadeghi/daisyui/assets/2099300/7c51d989-18aa-4dc8-a398-e52969602d38">

I see the checked bool and value getting triggered.

<img width="905" alt="image" src="https://github.com/saadeghi/daisyui/assets/2099300/c4aa190d-d4a4-414b-aada-6cbe0196b7ec">

But when I reverse the toggle back to light, it still remains dark even though css values seem to suggest the light theme needs to be in effect. Also tried with updating checkbox value to "light"

<img width="906" alt="image" src="https://github.com/saadeghi/daisyui/assets/2099300/fb4773b2-50aa-427b-a200-c9912021cfaf">

**Comment by saadeghi** [comment]
Unchecked checkbox with `theme-controller` class does nothing.  
Checked checkbox with `theme-controller` class applies the theme specified in value.  
So `theme-controller` does not care about your system theme, and yes as you said, if the system theme is `dark`, it switches dark to dark.  
This is not a bug. It's how it's expected to work logically if you think about it.

To overcome that, you can disable system dark mode using [`darkTheme: false` config](https://daisyui.com/docs/config/#darktheme). This way, the unchecked checkbox will be light and checked will be dark.

Another thing you can do use radio inputs:  
https://daisyui.com/components/theme-controller/#theme-controller-using-a-radio-input

Because a checkbox can only have 2 values. With radio buttons you can have 3 values or more (system / light / dark)

Let me know if you have a question.
