### ISSUE TITLE
bug: Step Numbers not hidden in Drawer

### ISSUE THREAD

**Issue by encorex** [saadeghi/daisyui#2916]
### What version of daisyUI are you using?

v4.7.3

### Reproduction URL

not

### Describe your issue

When i using a drawer, the numbers from the **steps** elemnt are always visable. I tried Z index without any succes.

Open Drawer
<img width="539" alt="Screenshot 2024-03-18 at 14 28 15" src="https://github.com/saadeghi/daisyui/assets/1597756/5cf7bedb-48ec-4b7b-aeb6-9806d8862153">

Closed Drawer
<img width="526" alt="Screenshot 2024-03-18 at 14 28 20" src="https://github.com/saadeghi/daisyui/assets/1597756/2c24c48c-9442-4028-8609-b48aacfa61ac">

**Comment by ImtiazNayeemShawon** [comment]
it's related to the **z-index**  maybe I can easily fix this issue

**Comment by saadeghi** [comment]
You can add `z-[1]` to `drawer-side` to fix this.  
It's not a good idea for daisyUI to set the z-index value for it by default because z-index is something that depends on your page content. Some people may need some elements to be on top of sidebar (like a fixed navbar or a toast message, etc.)  
So in this case you can use `z-[1]` but others may need another z-index value based on their page content.

Let me know if you have a question.
