### ISSUE TITLE
docs: daisyui.com index page animations make navigation difficult

### ISSUE THREAD

**Issue by imbev** [saadeghi/daisyui#2937]
### On which page do you see this issue?

https://daisyui.com/

### Describe the issue

While navigating through the index page, scrolling is repeatedly locked to show various animations. Because of this, the experience is unpleasant and harms UX. While the index page may have a different purpose from the rest of the website, it is also one of the few pages that contains the footer, which requires effort to access.

Having checked archive.org, this problem appears to have been introduced partway into 2023. The archived prior versions of the index page are significantly easier to navigate. I suggest reverting or modifying the index page to not rely on interaction, such as this version from 2022: https://web.archive.org/web/20220901222507/https://daisyui.com/

### What browsers are you seeing the problem on?

Chrome

**Comment by saadeghi** [comment]
Thanks for the feedback.  

First of all I have to close this because the issue section must be about daisyUI package, not the documentation website. Issues about the documentation website are welcome at Discussions.

Second, can you please explain what is unpleasant about the landing page? I mean what is the actual problem you're facing personally?  
The homepage is long and detailed and it has animations because the purpose is to explain what daisyUI does to new users. However it's not hijacking the scroll. Scroll animation is different from scroll hijacking. With scroll animation, you will have full control of the scroll and the scrollbars while the elements can have transitions and animations based on the scroll position. With scroll hijacking which is a bad UX pattern, the website takes control of the scroll position and scrollbars and it artificially scrolls through the content with a different speed and distance. This is not what daisyUI homepage does and it's important to know the difference.

Let me know if you have any questions.

**Comment by imbev** [comment]
> Issues about the documentation website are welcome at Discussions.

The issue settings might need to be updated

While scroll-jacking may not be the intention, that is the experience on my device. The first two sections of the page scroll normally,  however the "instead of writing 100 class names" section stops the user for 3-4 scrolls. Another instance is the "daisyUI is the most popular component library for Tailwind CSS" section, which stops the user for another 2 scrolls.

The "Fewer class names" and "55 Components..." sections also uses scroll animation, but don't lock me in place the way that the above sections do. The "Unlimited themes with zero effort" section does scroll-jack, but isn't as egregious as the other cases.

Thank you for your work on daisyUI!
