### ISSUE TITLE
bug: btn-link when button is disabled

### ISSUE THREAD

**Issue by deka** [saadeghi/daisyui#2971]
### What version of daisyUI are you using?

4.10.1

### Which browsers are you seeing the problem on?

Chrome

### Reproduction URL

https://play.tailwindcss.com/aw6PHLJHuV

### Describe your issue

When button is disabled, btn-link render is same as plain button.

**Comment by saadeghi** [comment]
It's intentional. Not a bug.  
Ideally you wouldn't want to disable a button link because the use case for button link is a navigation link, where takes the user to another page. The use case for a disabled button is an action button which we want the action button to exist but its action is prevented temporary.

On top of that, a button styled as a link can't have an ideal disabled visual. Even if we decreasing the opacity, it wouldn't be obvious that it's supposed to be disabled.

Let me know if you have any questions
