### ISSUE TITLE
bug: Icon Mask

### ISSUE THREAD

**Issue by zhuozhiyongde** [saadeghi/daisyui#2973]
### Which browsers are you seeing the problem on?

Chrome, Safari

### Reproduction URL

https://arthals.ink/

### Describe your issue

The Icon on the front page now has a Bezier Curve SVG Mask, but there seems to be a problem with this Mask:

```text
data:image/svg+xml,%3csvg%20width='200'%20height='200'%20xmlns='http://www.w3.org/2000/svg'%3e%3cpath%20d='M100%200C20%200%200%2020%200%20100s20%20100%20100%20100%20100-20%20100-100S180%200%20100%200Z'/%3e%3c/svg%3e
```

![image](https://github.com/innei-dev/Shiroi/assets/36695271/7639685b-0b88-4115-88c0-5793a87ea8eb)

You can see that there is a gap here, which is reflected in the actual graphics and forms jagged edges:

Normal size:
![image](https://github.com/innei-dev/Shiroi/assets/36695271/353067e8-285e-45b8-af87-accd11443ff4)

After zooming in:
![image](https://github.com/innei-dev/Shiroi/assets/36695271/0deb6305-9cfc-40ab-9071-4c5e5090da20)

**Comment by saadeghi** [comment]
> ```
> 
> ```
> 
> 
>     
>   
> 
> ![image](https://github.com/innei-dev/Shiroi/assets/36695271/7639685b-0b88-4115-88c0-5793a87ea8eb)
> 
> 
> You can see that there is a gap here, which is reflected in the actual graphics and forms jagged edges:
> 
> 
> Normal size:
> ![image](https://github.com/innei-dev/Shiroi/assets/36695271/353067e8-285e-45b8-af87-accd11443ff4)
> 
> 
> After zooming in:
> ![image](https://github.com/innei-dev/Shiroi/assets/36695271/0deb6305-9cfc-40ab-9071-4c5e5090da20)

I think there's a problem with these images. I can't see them. Can you upload the images again?

> https://arthals.ink/

Also, I don't see the issue in this page. Where is the issue?

**Comment by zhuozhiyongde** [comment]
![image](https://github.com/saadeghi/daisyui/assets/36695271/15c62136-ca76-4b81-ae99-611e19364a70)

You can see that there are jagged edges here.

@saadeghi

**Comment by zhuozhiyongde** [comment]
![image](https://github.com/saadeghi/daisyui/assets/36695271/9d36b983-ac69-422c-ba28-9cd38cbdcfb3)

The bug is more obvious on the big screen.

**Comment by zhuozhiyongde** [comment]
You may think that this gap will not appear on small screens, but in fact it does, and it will make the edges look rough.

**Comment by saadeghi** [comment]
I don't see the issue…


This is Chrome on MacOS  
<img width="504" alt="Screenshot 2024-04-13 at 3 22 20 PM" src="https://github.com/saadeghi/daisyui/assets/7342023/cea95e52-c134-4a0d-86ac-6ec64f0de694">

This is Safari on MacOS  
<img width="504" alt="Screenshot 2024-04-13 at 3 23 36 PM" src="https://github.com/saadeghi/daisyui/assets/7342023/4844a743-c0b5-4e7c-81b7-85758a5e8740">

There's no issue on the SVG shape. It's a perfect squircle I carefully made myself. Has no edges or anything.  

I also made a Tailwind Play page for reproduction but there's no issue there as well:  
https://play.tailwindcss.com/H8VSyRK4js

I assume this must be an issue of rendering, coming from either the browser or the OS graphic settings.  
Make sure the browsers are updated.  
Also, are you using a non standard setup, like a secondary monitor with a weird resolution or a non-standard HDMI cable or a custom graphic driver or something like that? because they can affect the graphic rendering performance.

I can assure you this is not a bug from daisyUI but I'm not sure if I can help with your case.

Let me know if you have a question.

**Comment by zhuozhiyongde** [comment]
I use macOS Ventura and have tested on the latest versions of Arc (based on Chromium 123.0.6312.123). However, it does work well on Safari and Chrome's latest version (123.0.6312.124 arm64).

I think it may be fixed after Arc update its core. Thx!

@saadeghi
