### ISSUE TITLE
bug: daisyui.com Website has memory leak problem on Firefox

### ISSUE THREAD

**Issue by xxnuo** [saadeghi/daisyui#2974]
### What version of daisyUI are you using?

any

### Which browsers are you seeing the problem on?

Firefox

### Reproduction URL

https://daisyui.com/components/card

### Describe your issue

When developing websites, I opened the [documentation of DaisyUI](https://daisyui.com/components/card). After a while, I noticed that Firefox 124.0.2 (64 bit) was consuming an extremely high amount of memory. Upon opening the browser task manager, I found that https://daisyui.com/components/card was consuming 4GB of memory. After reloading the webpage, the memory usage returned to normal, so I continued using it. The next day, when I opened the same documentation again, I encountered the same issue of high memory usage. On the third day, the same issue of high memory usage occurred again. Unfortunately, I didn't save any log records or screenshots, but I will provide them next time if the issue occurs again.

**Comment by saadeghi** [comment]
To be clear: **This is not memory leak**. Memory leak means a software using a part of available memory and after it's done, it doesn't free up the reserved memory.

This is just memory usage and the software which is using the memory, is Firefox. I assume it will free up the memory after a while when you close the tab.

I guess the only thing in [`card` component page](https://daisyui.com/components/card/) that may use memory more than usual is the glass effect which is just a CSS backdrop blur.  
I can confirm that Firefox is not really efficient about CSS blur but this is not something I can help with on my side. It's something FireFox should improve. daisyUI is just using a simple CSS blur.

Also, if the memory usage is not affecting your computer performance, it's not something to worry about. Unused memory is waster memory.

Also, disabling unused browser extensions and updating the browser to the latest version may help with that. If none of that helped, You may want to consider using another browser which is more efficient with your memory resources because if your Firefox is not efficient with CSS blur, it's not just about one website. You will probably have issues with other websites as well.

Let me know if you have a question.
