### ISSUE TITLE
bug: Icon/Text inside .input wrapper doesn't work as it's shown in demo

### ISSUE THREAD

**Issue by webceyhan** [saadeghi/daisyui#3003]
### What version of daisyUI are you using?

4.10.2

### Which browsers are you seeing the problem on?

Chrome

### Reproduction URL

https://daisyui.com/components/input/#text-input-with-icon-inside

### Describe your issue

```html 
 <label class="input input-bordered flex items-center gap-2">
    test
    <input ref="input" type="text" class="grow" />
  </label>
`

<img width="1518" alt="Screenshot 2024-04-28 at 19 00 43" src="https://github.com/saadeghi/daisyui/assets/3739981/518be1c0-c621-4444-ae61-0e6462241bb0">

**Comment by saadeghi** [comment]
It's working like the demo: https://play.tailwindcss.com/tpUPPhaV4P 🤔  
Are you sure that border is not coming from another CSS plugin? like `@tailwindcss/forms`?

**Comment by webceyhan** [comment]
Indeed, you're right! I've removed the forms plugin and it's fixed.
So basically daisyui is not compatible with tailwind plugins?

Maybe you could mention this in the docs to avoid further confusion?

**Comment by saadeghi** [comment]
It's important to know what exactly a plugin does when we're adding them.  

`tailwindcss-forms` by default, applies opinionated styles **to all form elements in the page**. Without using any class names. It targets the `<input>` tags.  
The border you were seeing was coming from `tailwindcss-forms` and there's nothing daisyUI can do about it because `tailwindcss-forms` is doing its job as it's supposed to do.  

So, before using `tailwindcss-forms` I would ask myself "_do I need styles on **all** input tags on my page_"? 😅

Thankfully, `tailwindcss-forms` has a config to opt out of applying styles to everything by default, and instead applying styles to specific form elements using the [`class` strategy](https://github.com/tailwindlabs/tailwindcss-forms?tab=readme-ov-file#using-only-global-styles-or-only-classes).

daisyUI is compatible with `tailwindcss-forms` if you use their [`class` strategy](https://github.com/tailwindlabs/tailwindcss-forms?tab=readme-ov-file#using-only-global-styles-or-only-classes)
