### ISSUE TITLE
A plugin module for unocss would be appreciated

### ISSUE THREAD

**Issue by folamy** [saadeghi/daisyui#301]
There is a new CSS engine called [Unocss](https://github.com/antfu/unocss)!
Would it be possible to use daisyui with it?

**Comment by saadeghi** [comment]
It's not a CSS preprocessor. It's an engine.  
And daisyUI is a collection of CSS components.  
I'm not sure how and why you want to use these together? because you need a CSS preprocessor like PostCSS or Tailwind's CLI at some point to generate utility classes for you.

From [UnoCSS repo](https://github.com/antfu/unocss#non-goal): 
>UnoCSS is designed NOT to be/have:
A CSS preprocessor (e.g. `@apply`) - but you can use shortcuts.
Tailwind's plugin system - but you can write custom rules in seconds and share them as presets!

**Comment by dominikg** [comment]
Hmmm, i think a unocss preset daisyui should be possible with shortcuts: https://github.com/antfu/unocss#shortcuts

**Comment by saadeghi** [comment]
@dominikg It might be possible but it might have some limitations 🤷‍♂️  
I would be glad if some works on a "shortcut" for daisyUI but it will have development and maintenance costs.  
I'm not interested on working on it myself because I'm not sure what value it adds for the developers comparing to existing solutions.  
At the end, developers just need a fast build tool and Tailwind's JIT is fast enough.

**Comment by miaojinsing** [comment]
> @dominikg It might be possible but it might have some limitations 🤷‍♂️ I would be glad if someone works on a "shortcut" for daisyUI but it will have development and maintenance costs. I'm not interested on working on it myself because I'm not sure what value it adds for the developers comparing to existing solutions. At the end, developers just need a fast build tool and Tailwind's JIT is fast enough.

Why are many users using vite when webpack is fast enough
