### ISSUE TITLE
Modal documentation not working, leading to page 404

### ISSUE THREAD

**Issue by vicovaro** [saadeghi/daisyui#305]
The current two examples in
https://daisyui.com/components/modal#
don't work at all. The first one lead to page 404 when clicking on "OPEN MODAL".
The second one doesn't even open a modal with the button "OPEN MODAL".

I did find on Github issues this working example which I used for my code
https://github.com/saadeghi/daisyui/issues/9
https://codepen.io/saadeghi/pen/ZEBvMey?editors=1000

Current stack
```
{
  "name": "nextjs",
  "version": "1.0.0",
  "private": true,
  "scripts": {
    "dev": "next dev",
    "build": "next build",
    "start": "next start",
    "lint": "next lint"
  },
  "dependencies": {
    "@supabase/supabase-js": "^1.27.0",
    "autoprefixer": "^10.4.0",
    "daisyui": "^1.16.2",
    "next": "12.0.1",
    "postcss": "^8.3.11",
    "react": "17.0.2",
    "react-dom": "17.0.2",
    "tailwindcss": "^2.2.19"
  },
  "devDependencies": {
    "@types/react": "^17.0.34",
    "eslint": "7.32.0",
    "eslint-config-next": "11.1.0",
    "typescript": "^4.4.4"
  }
}
```

**Comment by saadeghi** [comment]
@vicovaro The Codepen link you mentioned is using a very old version of daisyUI (0.11.5) That's why the second method won't work there.  
here's a new working example with both methods: https://codepen.io/saadeghi/pen/eYEQqMG?editors=1100

Using the "anchor link" method, the import thing is `href` values must be correct. If you're copy/pasting the exact code from daisyUI docs, make sure remove the `/components/modal` part and it work (because it's a NuxtJS single page app, I needed to use the full path there)

Please let me know if you have any questions.
