### ISSUE TITLE
bug: checkbox not working

### ISSUE THREAD

**Issue by kknono** [saadeghi/daisyui#3080]
### Which browsers are you seeing the problem on?

All browsers

### Reproduction URL

https://daisyuinuxt3-ac3l--3000--c3e5e364.local-credentialless.webcontainer.io

### Describe your issue

Hi, I have used a prefix added to the front of the daisyUI classes, and other components are working fine. However, the checkbox component is not. The code is as follows:
<input type="checkbox" class="!dy-checkbox" />

When used in combination with Flowbite, the checkmark inside the checkbox appears very small when checked, which is inconsistent with the default daisyUI appearance."

Please need more help. thanks

**Comment by saadeghi** [comment]
I can't see the link. Can you check if the link you shared is correct?
```
Could not find project
```

**Comment by kknono** [comment]
Sorry, the correct address is: https://stackblitz.com/edit/daisyui-nuxt3-qhzjs2?file=package.json

**Comment by kknono** [comment]
<img width="415" alt="截屏2024-06-14 13 02 01" src="https://github.com/saadeghi/daisyui/assets/2398446/ca874a10-0795-498e-a3dc-5576e97ee564">

**Comment by saadeghi** [comment]
Unfortunately Flowbite is applying styles to `[type='checkbox']` by default regardless if you use their class names or not. daisyUI only applies styles to `.checkbox` class name (`.dy-checkbox` with your custom prefix in this example) so either you use daisyUI or not, that `[type='checkbox']` style is being applied by Flowbite and we can't change it because:
1. `[type='checkbox']` has higher CSS specificity than a `.checkbox` class name
2. We don't want to apply styles to checkboxes without `.checkbox` class name since we don't want to create this kind of conflict with other libraries.

You can open an issue about this on Flowbite repo.
Or you can disable their default `forms` styles like this:
```js
require('flowbite/plugin')({
  forms: false,
}),
```
https://stackblitz.com/edit/daisyui-nuxt3-f2yshy?file=tailwind.config.js,app.vue

Let me know if you have a question.

**Comment by kknono** [comment]
Thank you for the explanation!
