### ISSUE TITLE
bug: Accordion does not work with the Tailwind forms package 

### ISSUE THREAD

**Issue by SSmale** [saadeghi/daisyui#3081]
### What version of daisyUI are you using?

4.12.2

### Which browsers are you seeing the problem on?

Chrome, Safari, Firefox

### Reproduction URL

internal.com

### Describe your issue

  plugins: [
    require("@tailwindcss/typography"),
    require("@tailwindcss/container-queries"),
    // require("@tailwindcss/forms"),
    require('daisyui'),
  ],

uncomment the forms to have the accordion fail

**Comment by saadeghi** [comment]
The style you're seeing is not from daisyUI so there's nothing I can do about it.  

daisyUI applies styles to class names but `@tailwindcss/forms` by default, applies styles to ALL form elements.  

If you really need `@tailwindcss/forms` alongside with daisyUI (which I doubt, because both are doing the same job) consider using its [`strategy: 'class'` config](https://github.com/tailwindlabs/tailwindcss-forms#using-only-global-styles-or-only-classes) so it only applies style to the elements with specific class name (not all form elements)

**Comment by SSmale** [comment]
This is then a documentation issue. It would be good to have a warning about it like there is for the typography one

**Comment by saadeghi** [comment]
It is all explained in the `@tailwindcss/forms` docs:  
https://github.com/tailwindlabs/tailwindcss-forms  

>A plugin that provides a basic reset for form styles

>All of the basic form elements you use will now have some simple default styles that are easy to override with utilities.

>Every element has been normalized/reset to a simple visually consistent style

None of these are related to daisyUI at all. The styles you're seeing are coming from forms plugin and it is explained in forms plugin repo about what it does.

We have a page about typography and layouts in daisyUI docs because daisyUI doesn't provide those class names and it is suggested to use Tailwind CSS layout utility class names and Tailwind CSS Typography plugin for that. On the other hand, Tailwind Forms plugin is not something you would need alongside daisyUI. It creates conflicts because both plugins are doing the same thing.  
We can't force daisyUI styles over Tailwind Forms style because Tailwind forms applies styles to tag names, not class names (which is higher CSS specificity)  
There's no reason to use Tailwind forms and daisyUI on the same project as both of them are doing the same job. But if you decide to install and use Tailwind forms plugin, it is expected to read its docs because it is mentioned there multiple times that it applies styles to ALL form elements by default unless you use their class name strategy which is also explained on their docs.

Let me know if you have any questions.
