### ISSUE TITLE
bug: Join, elements are not aligned since the last update

### ISSUE THREAD

**Issue by Resumane** [saadeghi/daisyui#3118]
### What version of daisyUI are you using?

4.12.10

### Which browsers are you seeing the problem on?

Chrome

### Reproduction URL

https://play.tailwindcss.com/GsxvhHLLKW

### Describe your issue

The items in Join are not aligned since the last update, please fix.

**Comment by sergei-krylov** [comment]
To add into that issue - it happens when both `vertical` and `horizontal` options specified, i.e. `join-vertical lg:join-horizontal`.

The issue is even visible in the docs, in "Responsive" example: https://daisyui.com/components/join/#responsive-its-vertical-on-small-screen-and-horizontal-on-large-screen, the first button is lower than others in horizontal mode.

**Comment by gabrielCarraretto** [comment]
It seems that the last bug fix is causing it.


> ### 4.12.10 (2024-06-26)
> ### Bug Fixes
> - join spacing adapting to button border width ([da94f2c](https://github.com/saadeghi/daisyui/commit/da94f2cbaeb7d4296ac0510306add812edf5e336)), closes [#3028](https://github.com/saadeghi/daisyui/issues/3028)

Downgrading to `4.12.9` fixes the problem

```
 yarn upgrade daisyui@4.12.9
```
or 
```
npm i daisyui@4.12.9
```

**Comment by saadeghi** [comment]
Fixed in `4.12.11`

Thanks @gabrielCarraretto for finding the cause of problem 💚
