### ISSUE TITLE
Using drawer navigation leads to iOS browser double cursor

### ISSUE THREAD

**Issue by deyanskiq** [saadeghi/daisyui#313]
Using `drawer` and `drawer-mobile` daisyui classes leads to double cursor + iOS browser menu not hiding on scroll (which is the default behaviour).

I have noticed that on both my project and daisy ui website (screenshot attached).

Any suggestions how to fix this?

![IMG_9347](https://user-images.githubusercontent.com/11162576/143048466-0416229c-0f9f-4ade-93e9-06f9b6f3e4cf.PNG)

**Comment by saadeghi** [comment]
@deyanskiq This doesn't seem to be a problem on the new iOS safari but I will look into that to see if there's a workaround...

**Comment by deyanskiq** [comment]
Just tested on the latest iOS version (15.1), iPhone XR, and it seems that the behaviour is the same. Please have a look if there's a workaround.
![IMG_DAE49AF820BE-1](https://user-images.githubusercontent.com/11162576/143864043-527a9acd-df6b-4f06-a6ee-2ab603047479.jpeg)

**Comment by instanceofmel** [comment]
I can confirm that the problem still persists on my iPhone XR.

**Comment by sshquack** [comment]
Not sure if this is related but this might be related to the trackpad swipe gesture not working in `drawer-content` so I created https://github.com/saadeghi/daisyui/issues/432

**Comment by deyanskiq** [comment]
Hey @saadeghi, any update on the topic?

**Comment by saadeghi** [comment]
The problem is generally the `100vh` height and it's not just a problem from daisyUI. Mobile browsers have dynamic sections on top or bottom that will show and hide based on the scroll position and that section is not calculated when we want a full height section and we use `100vh` for it. I tried a few solutions but none of them were practical to use on production. There are [new height units](https://caniuse.com/viewport-unit-variants) coming to CSS that will solve this but the browser support is not good yet.

**Comment by deyanskiq** [comment]
Ok, thanks! Can you share a workaround that we can apply?
