### ISSUE TITLE
bug: tabs not showing as expected [ copied / pasted from official page as it is]

### ISSUE THREAD

**Issue by ibguide** [saadeghi/daisyui#3136]
### Which browsers are you seeing the problem on?

Chrome, Safari

### Reproduction URL

https://play.tailwindcss.com/mbKobSKO4g

### Describe your issue

It works fine in [Tailwind Playgournd](https://play.tailwindcss.com/mbKobSKO4g)

<img width="263" alt="Screenshot 2024-07-18 at 1 02 25 AM" src="https://github.com/user-attachments/assets/275237b8-73c9-49ca-834f-33ae7270021c">

**Comment by saadeghi** [comment]
The style you're seeing is not from daisyUI.

Probably you're using `@tailwindcss/forms` (or another style or plugin) that is affecting form elements.
daisyUI applies styles to class names but `@tailwindcss/forms` by default, applies styles to all form elements.
If you really need `@tailwindcss/forms` alongside with daisyUI (which I doubt, because both are doing the same job) consider using its [strategy: 'class' config](https://github.com/tailwindlabs/tailwindcss-forms#using-only-global-styles-or-only-classes) so it only applies style to the elements with specific class name (not all form elements)

**Comment by ibguide** [comment]
I really appreciate your input.

Thanks and God bless you
