### ISSUE TITLE
The code will not show up

### ISSUE THREAD

**Issue by Dark-Ai-py** [saadeghi/daisyui#3152]
### On which page do you see this issue?

https://daisyui.com/components/tooltip/ and all of the other component pages

### Describe the issue

When I find a component I like I cannot open the source code to copy it.
FireFox on Win 11 with Ublock Origin installed but turned off. 

### What browsers are you seeing the problem on?

Firefox

**Comment by saadeghi** [comment]
Do you see the issue in Incognito Mode as well?
Have you tried another browser?

I have to close this issue because it's not from our side. But feel free to continue the conversation, I would be happy to help.  
It's a problem from your client, probably an extension or another software blocking the JS execution.
