### ISSUE TITLE
Dropdown Doesn't Seem to Work

### ISSUE THREAD

**Issue by benwinding** [saadeghi/daisyui#320]
Hey @saadeghi, 
I can't seem to get the dropdown example to work. The `dropdown-hover` works but the clickable dropdown example doesn't work for me.

- This example works here 👍 
https://codepen.io/saadeghi/pen/gOwWKvv

- This code doesn't seem to work locally, which is really weird 😟 👎 
``` html
<html>
  <head>
    <link rel="stylesheet" href="https://unpkg.com/daisyui@latest/dist/full.css">
    <link rel="stylesheet" href="https://unpkg.com/tailwindcss@^2/dist/tailwind.min.css">
  </head>
  
  <body>
    <div class="dropdown">
      <div class="m-1 btn">Dropdown</div>
      <ul class="p-2 shadow menu dropdown-content bg-base-100 rounded-box w-52">
        <li><a>Item 1</a></li>
        <li><a>Item 2</a></li>
        <li><a>Item 3</a></li>
      </ul>
    </div>
  </body>
</html>
```

Any ideas what could be going on here?

Tested on Chrome, Firefox, Safari ect...

![Kapture 2021-12-03 at 22 41 02](https://user-images.githubusercontent.com/11782590/144596774-40dbb9fe-88a2-490c-821e-611d23b60cf8.gif)

**Comment by saadeghi** [comment]
@benwinding There's a reason I used `tabindex` on all examples and you should't remove it.  
dropdown works with `:focus` so the button and the menu should be focusable.
example: https://codepen.io/saadeghi/pen/VwMLOBo?editors=1000

**Comment by benwinding** [comment]
Thanks for the quick reply! 🙏 
Ahh ok, but it seems the values of `tabindex` don't even matter? As long as they're numbers right? Why is that?
``` html
  <div class="dropdown m-4">
    <div tabindex="99" class="m-1 btn">Dropdown</div> 
    <ul tabindex="0" class="p-2 menu dropdown-content bg-neutral text-neutral-content rounded-box w-52">
      <li><a>Item 1</a></li>
      <li><a>Item 2</a></li>
    </ul>
  </div>
```

**Comment by saadeghi** [comment]
@benwinding Yes. you can use `0` or any positive value.  
`0` means this element should be focusable. any other positive value (`1`, `2`, etc...) makes the element focusable but also changes the order of focus when we navigate the elements using `tab` key.  
[[more info on MDN docs](https://developer.mozilla.org/en-US/docs/Web/HTML/Global_attributes/tabindex)]

**Comment by benwinding** [comment]
Ahh okay, it seems so straightforward now! 😆 
Thanks so much for your help and patience, love the library too by the way 👌

**Comment by carlosvigil** [comment]
[Accessibility concerns](https://developer.mozilla.org/en-US/docs/Web/HTML/Global_attributes/tabindex#accessibility_concerns)

Avoid using the tabindex attribute in conjunction with non-[interactive content](https://developer.mozilla.org/en-US/docs/Web/HTML/Content_categories#interactive_content) to make something intended to be interactive focusable by keyboard input. An example of this would be using a [`<div>`](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/div) element to describe a button, instead of the [`<button>`](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/button) element.

Interactive components authored using non-interactive elements are not listed in the [accessibility tree](https://developer.mozilla.org/en-US/docs/Learn/Accessibility/What_is_accessibility#accessibility_apis). This prevents assistive technology from being able to navigate to and manipulate those components. The content should be semantically described using interactive elements ([`<a>`](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/a), [`<button>`](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/button), [`<details>`](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/details), [`<input>`](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/input), [`<select>`](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/select), [`<textarea>`](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/textarea), etc.) instead. These elements have built-in roles and states that communicate status to the accessibility that would otherwise have to be managed by [ARIA](https://developer.mozilla.org/en-US/docs/Web/Accessibility/ARIA).
