### ISSUE TITLE
`tooltip` at the edges of the page are causing the page to overflow

### ISSUE THREAD

**Issue by jquesada2016** [saadeghi/daisyui#326]
Currently, adding a tooltip to anything close to the right edge, will cause the page to slightly overflow and display a horizontal scrollbar.

for example, in a navbar, a top right button with a couple of words will cause the page to overflow.
```html
<div class="navbar mb-2 shadow-lg bg-neutral text-neutral-content justify-end">
  <div data-tip="This is my longer text" class="tooltip tooltip-bottom">
    <button class="btn>Overflow</button>
  </div>
</div>
```

**Comment by saadeghi** [comment]
@jquesada2016 There can be 2 expected behavior here:
- automatically change the direction if it's on the edge (example: if tooltip is on the right edge, automatically show the tooltip on the left of element)
- automatically move the tooltip box to fit the space.

Unfortunately none of these behaviors are possible using only CSS and it needs custom JS.
So the solution would be using a `tooltip-left` if it's overflowing to the right. Or use other directions to avoid the overflow based on the edge location.

**Comment by jquesada2016** [comment]
Yeah, what I've been doing is just positioning it to the left. I would almost rather it clip than overflow, because overflowing is far more noticeable than clipping. What do you think? Would that be something viable?

**Comment by saadeghi** [comment]
@jquesada2016 Clipping the tooltip and hide a part of it? I don't think that's a good solution 👀
