### ISSUE TITLE
bug: (v5) dropdown displayed in viewport top left corner in Firefox

### ISSUE THREAD

**Issue by notramo** [saadeghi/daisyui#3294]
### What version of daisyUI are you using?

v5 preview on Tailwind Play

### Which browsers are you seeing the problem on?

Firefox

### Reproduction URL

https://play.tailwindcss.com/4ztkH9X6wN?file=css

### Describe your issue

Any dropdown button shows the dropdown at the top left corner of the viewport.

![image](https://github.com/user-attachments/assets/f250e20b-1081-4295-afb9-82c092e52c8d)

**Comment by notramo** [comment]
@mhadaniya, what browser was used for the screencast? I tried it on latest Firefox.

I noticed that the first few dropdown buttons are working, however, the ones that come after the "no anchor" button in the example are not working. After looking into the code, I found that it's using anchor positioning, which is only supported by most recent versions of Google Chrome at the moment.

**Comment by saadeghi** [comment]
Dropdown in v5 supports the new HTML **Popover API** and the new CSS **Anchor Positioning** module (experimental)  

Here's an example:  
https://play.tailwindcss.com/F6M7IcIX4J

(Previous dropdown methods such as `<details>`/`<summary>` method and CSS hover method are still supported with the same class name)

Popover API + Anchor Positioning are the new way to handle dropdowns and they finally allows us to open/close dropdowns by clicking outside _and_ by clicking the button again (without needing any JS)

- The new **Popover API** is supported by browsers
- The new **Anchor Positioning** module is only supported by Chrome for now.  

As a progressive enhancement, I show the popover in the middle of page for unsupported browsers (because we can't place it next to the button until those browsers support Anchor Positioning) so it works like a fullscreen popover for now.

Chrome:  
<img width="1051" alt="Screenshot 2024-12-06 at 1 47 02 AM" src="https://github.com/user-attachments/assets/660aee06-dfc8-44ca-a9ef-6adf0ef2ef3b">

FireFox:  
<img width="1113" alt="Screenshot 2024-12-06 at 1 55 32 AM" src="https://github.com/user-attachments/assets/94c48ca9-dda9-4c9b-865f-d94f1ed89246">

**Comment by notramo** [comment]
It's definitely a better fallback solution for Firefox. Thank you for the quick fix.
