### ISSUE TITLE
Typography syntax error

### ISSUE THREAD

**Issue by AntonTrapp** [saadeghi/daisyui#330]
Followed the installation instructions. Got a:

```
TypeError: Cannot read properties of undefined (reading '700')
```

tailwindcss: 2.2.19
typography: 0.5.0
daisyui: 1.16.4

Did they mess around with the versions due to the 3.0 update, any requirements, ...? Tried the 0.4.1 version instead of the 0.5.0 - no errors. Maybe the documentation should be updated to state that the latest 2.x version of tailwind should be used with the latest 0.4.x version?

PS: apart from the typography everything seems to work after a few minues including custom theming. I'm impressed!

**Comment by saadeghi** [comment]
@AntonTrapp I think you need to use Tailwind CSS `3.0` with Typography `0.5` because [it's a peer dependency](https://github.com/tailwindlabs/tailwindcss-typography/blob/61826feebf24cc1c09630fef4aa699afd58e5dac/package.json#L29) on this version.  

I tested latest versions of each package together and everything works:
```
"@tailwindcss/typography": "^0.5.0",
"daisyui": "^1.16.5",
"tailwindcss": "^3.0.2",
```
However If you don't want to use Tailwind `3.0` yet, I think you should stay on typography `0.4`
