### ISSUE TITLE
daisyui in Figma

### ISSUE THREAD

**Issue by thefersh** [saadeghi/daisyui#350]
I am not a designer, but as a developer I work with figma making user experience fixes and it would be useful if daisyui could exist officially within the figma community.

**Comment by saadeghi** [comment]
I don't have any plans for a Figma file. The reason is:  

The process of designing a layout directly in HTML using Tailwind CSS (and daisyUI) utility classes is faster and more efficient than first designing it in a design tool like Figma. Creating a UI on Figma requires drawing elements and layouts on a canvas but then the next step will be recreating them all with CSS/HTML. Not to mention that the "CSS code" Figma gives us is not suitable for a real-life product so it needs to be written with hand again.  

I just can't justify where's the point of first creating the layout on Figma and then creating it again using CSS/HTML.  
Tailwind's utility classes gives us the speed and efficiency to quickly create layouts. 10 years ago, we didn't have that. Structuring CSS and applying changes was hard and time consuming so it was better to first create a mockup on a design software to speed up applying changes. Now, with utility-first CSS, that's not the case anymore.  

I'm aware that Figma, Sketch, etc... are the main tools for UI designers and UI designers don't necessarily know CSS/HTML.  
So even if I find it unnecessary to use Figma for a Tailwind project, It's a good idea to have a Figma file after all.  
If anyone from the community starts making a Figma version for daisyUI I will support that too.
