### ISSUE TITLE
Form input examples are missing label to input association, leading to warings/errors

### ISSUE THREAD

**Issue by SumitBando** [saadeghi/daisyui#352]
E.g.
  <label class="label">
    <span class="label-text">Username</span>
  </label> 
  <input type="text" placeholder="username" class="input input-bordered">
thows warnings or errors in various processors.

Should be:
  <label for='someid' class="label">
    <span class="label-text">Username</span>
  </label> 
  <input id=someid type="text" placeholder="username" class="input input-bordered">

**Comment by saadeghi** [comment]
I don't think if it's a good decision to put `id`s on sample codes. I will avoid that as much as I can. There are parts of code that should be edited when you copy/paste them. such as label texts, placeholders, etc... You should use `id`s too but since `id`s should be unique on page, I can't just give you a random `id="username"` for an `input` sample code there might be another `id="username"` somewhere on the page and this will lead to unexpected functionality behavior.  
So, it's better to read the warning and fix it yourself because at the end, you should be the one who decide about the value of `id`

**Comment by SumitBando** [comment]
The other way to solve this is to enclose the input inside <label> tags

**Comment by saadeghi** [comment]
Yes. Putting `<input>` inside `<label>` will be valid without `for` attribute but if I style them this way, it will force people to put the `<input>` and `<label>` in the same place.  
In many layouts, there can be other elements between these two. Or `<input>` and `<label>` can have wrappers.
