### ISSUE TITLE
Can't access colors in js

### ISSUE THREAD

**Issue by OdifYltsaeb** [saadeghi/daisyui#365]
Hi,

I looked up how to use colour codes in javascript ( so I could pass them on to `FontAwesomeIcon` for example).

so here's what I do:
```
import resolveConfig from 'tailwindcss/resolveConfig';
import tailwindConfig from '../../tailwind.config';
const tw = resolveConfig(tailwindConfig);
```

However `<FontAwesomeIcon className="ml-3" color={tw.theme.colors.secondary} icon={icon} size="lg" />` does not a thing.

If I log `tw.theme.colors.secondary` into the shell it prints out as 
```
function key()
    length: 1
    name: ""
<prototype>: function ()
```

should you accept this as an issue, I think the goals could be:

- Write documentation on how to use the theme colours in Javascript
- make using `tw.theme.colors.secondary` or `tw.theme.colors.secondary.DEFAULT` work in Javascript.

**Comment by saadeghi** [comment]
@OdifYltsaeb Can you please provide a small repo on github so I can reproduce this?

**Comment by OdifYltsaeb** [comment]
There you go:

https://github.com/OdifYltsaeb/daisyui-colors

It's plain nextjs app with just tailwind, daisyui, postcss and fontawesome added - just like in my own project.

**Comment by saadeghi** [comment]
Thanks for the repo.
The problem is, daisyUI colors are not actual colors. they're CSS variables and each theme, set value for variables. You can get access to the colors of themes like this:
```js
import daisyuiColors from 'daisyui/colors/themes'

// secondary color of light theme (#f000b8):
let myColor = daisyuiColors['[data-theme=light]'].secondary
```
This is the file: https://github.com/saadeghi/daisyui/blob/master/src/colors/themes.js

Let me know if you have any questions

**Comment by OdifYltsaeb** [comment]
Sure, how do you get the active theme, because you'd probably not want to hardcode the theme name into `'[data-theme=light]'`.

And do you think this could be documented also? so anybody with the same question can just grab it from the colours page of the DaisyUI documentation. That's the place I would look for (and I did in the beginning)

**Comment by OdifYltsaeb** [comment]
Not sure if it is the most optimal way, but here's what I did:

```
    const tw = resolveConfig(tailwindConfig);
    const theme = tw.daisyui.themes[0];
    const daisyColors = daisyuiColors[`[data-theme=${theme}]`];
    const { neutral, warning } = daisyColors;
```

**Comment by saadeghi** [comment]
Yeah. I will add it to the docs.


> ```
>     const tw = resolveConfig(tailwindConfig);
>     const theme = tw.daisyui.themes[0];
>     const daisyColors = daisyuiColors[`[data-theme=${theme}]`];
>     const { neutral, warning } = daisyColors;
> ```

This 👆 will get the first theme but it's tricky because if there are light/dark theme defined by the OS, CSS media query decides about the the dark mode.  
Also, themes can be nested using `data-theme` attribute on any section. So the first theme is not necessary the active theme unless you only use one theme.  
I'm not sure about the reason why you want to get the colors with JS but CSS variables will always return the correct color. For example `--p` is the HSL value of primary color.  
https://github.com/saadeghi/daisyui/blob/master/src/colors/colorNames.js

**Comment by OdifYltsaeb** [comment]
The reason why I want the colour in JS is because sometimes you need to be able to pass the actual colour to something, not a CSS class. 

Like in my case, I have two options - if I want the icon to be coloured I need to wrap it into an element and add colour to that element as a CSS class. Which will work. But it is possible to colour things by passing an actual colour code to them, so why not do it. And SVG elements definitely is one thing that might need an actual colour code.

anyway - enjoy the passing of this terrible year, and happy new year to you. Thank you for creating something as awesome as DaisyUI

Alan

**Comment by saadeghi** [comment]
I think you can use `fill-current` for SVG to use the current text color.

I hope you're having a good new your too.
