### ISSUE TITLE
daisyUI don't apply background color

### ISSUE THREAD

**Issue by LWJerri** [saadeghi/daisyui#366]
I have a problem with applying `data-theme` on the background color. When I change `data-theme` from `aqua` to `light` in Main.svelte file colors change only in components, but the background is still dark.

**UPD:**
Dark theme applies auto, but if I remove `@tailwind components;` in `index.css` background color back to light (default).

Minimal code for reproduce problem: https://github.com/LWJerri/startup-web
Screenshots:
![image](https://user-images.githubusercontent.com/50290430/147678420-00cb183f-0d65-458b-8866-9e46506b4001.png)
![image](https://user-images.githubusercontent.com/50290430/147678452-ed4ed789-8929-4a45-b38b-a682ef5250f9.png)

**Comment by LWJerri** [comment]
Any ideas?

**Comment by saadeghi** [comment]
@LWJerri On your code, you have `data-theme` on a div  
<img width="747" alt="1" src="https://user-images.githubusercontent.com/7342023/147753635-31698ef1-b0fc-4244-90b1-b0ea77eea2eb.png">
So only that div gets the `aqua` theme. Since that div is not covering the whole page, the page background is using the default theme (`light`/`dark`)

You should either use `data-theme` for the `<html>` tag or you can change the default theme from `tailwind.config.js`:  
```js
  daisyui: {
    themes: [
      "aqua", // this first one will be the default theme
      "dark",
      // other themes
    ],
  }
```
more info: https://daisyui.com/docs/config
