### ISSUE TITLE
tailwindcss 3.0.10 - daisyui twice

### ISSUE THREAD

**Issue by gaurovsoni** [saadeghi/daisyui#380]
![Screenshot from 2022-01-05 17-40-45](https://user-images.githubusercontent.com/9216097/148216793-14c2d341-c93e-4e91-9f66-96a160e086ff.png)
![Screenshot from 2022-01-05 17-44-22](https://user-images.githubusercontent.com/9216097/148216803-aa8ee626-1681-4dc7-be03-bf68a1c096be.png)
![Screenshot from 2022-01-05 17-44-34](https://user-images.githubusercontent.com/9216097/148216806-7c698f90-bc20-4087-bb52-cbebe9a70490.png)

The above screenshot is when i build the app. The same goes when i run in dev mode but without those axios lines, in short i started seeing daisyui twice on both build/run. On top of that google fonts @import in css stopped working due to this, not sure why it stopped working.... I started seeing transformations when i upgraded to tailwind 3.0.10 (3.0.8 previously using). Reverting back to tailwind 3.0.8 fixed the things for me.

**Comment by saadeghi** [comment]
I'm not sure why it logs twice because I'm only sending one [console.log](https://github.com/saadeghi/daisyui/blob/702797a4ea53f8df04087ca48b54ec7bafba3bc7/src/index.js#L23) when build executes 🤔  
But you can disable the log [from tailwind.config.js](https://daisyui.com/docs/config) if you prefer:  
```js
daisyui: {
  logs: false,
}
```

**Comment by danielehrhardt** [comment]
![image](https://user-images.githubusercontent.com/19570043/236041731-a300ac34-61f3-4b83-a980-41d2f884bc18.png)

**Comment by polyzen** [comment]
This started happening with SvelteKit after version [1.10.0](https://github.com/sveltejs/kit/releases/tag/%40sveltejs/kit%401.10.0), but I haven't taken the time to bisect yet.

**Comment by saadeghi** [comment]
daisyUI just has a single `index.js` and it only has 1 `console.log`  
whenever your build tool or CSS processor runs the file.  
If it runs the file twice, you will see 2 logs.  
I can't control that but it's not an issue. 
If you don't want to see the logs, you can disable it. It's just an informative text to show what version are you using and what is included.

**Comment by polyzen** [comment]
Not sure if it's intentional or not on SvelteKit's part, mostly curious why it happens. Only happens when you first start the Vite dev server.

**Comment by saadeghi** [comment]
probably something about preprocessing or performance. I'm not sure.  
But Vite alone, only runs the file once: https://stackblitz.com/edit/daisyui-vite?file=package.json

**Comment by danielehrhardt** [comment]
For me it is happening in Angular. Performance wise I think it's not correct to only disable the logs. Maybe we can reopen the Issue and check in the future if someone have time.

**Comment by saadeghi** [comment]
@danielehrhardt I don't want to repeat myself, sorry, but this is **not** something we can control in daisyUI. daisyUI only has 1 `index.js` file which only has 1 `console.log`  
For some reason, some build tools or preprocessors or frameworks run the file multiple times which results multiple logs.  
Reopening this issue won't be helpful because it can't be fixed on our side. daisyUI is not running the file multiple times. daisyUI is just a JS files which gets imported to Tailwind CSS as a plugin then your build tool/processor/framework decides how to run the files.

Also, I can assure you having a `console.log` or disabling it has absolutely no effect on performance. Ignore it or disable it.
