### ISSUE TITLE
[Question] Recommended way to add a newline in tooltip

### ISSUE THREAD

**Issue by Braintelligence** [saadeghi/daisyui#388]
Hello everyone!

What would be the recommended way to add a newline in the tooltip?

**Comment by saadeghi** [comment]
It's a string written on a `:before` pseudo element, so it will a little hacky:

Solution A: You can use `&#10;` to break the line
```html
<div
  data-tip="line 1&#10;line 2"
  class="tooltip tooltip-open tooltip-bottom my-tooltip"
  >
  <button class="btn">button</button>
</div>
```
and in your CSS file, add `white-space: pre;` to the tooltip box
```css
.my-tooltip:before{
  white-space: pre;
}
```

Solution B: use `&#10;` to break the line but instead of writing custom CSS, use Tailwind classes with arbitrary values to do it all:
```html
<div
  data-tip="line 1&#10;line 2"
  class="tooltip tooltip-open tooltip-bottom before:whitespace-pre before:content-[attr(data-tip)]"
  >
  <button class="btn">button</button>
</div>
```

https://play.tailwindcss.com/8eCM8D058f

**Comment by vastava** [comment]
This solution seems to revert the behavior back to what is seen in #84 

I'm on daisyui version 3.1.9 and tailwind 3.3.1, so could be due to versioning. 

<img width="697" alt="Screen Shot 2023-07-12 at 5 02 01 PM" src="https://github.com/saadeghi/daisyui/assets/37812945/c8d69501-1c64-4beb-8966-9f21ff6162e4">

**Comment by saadeghi** [comment]
@vastava It still works. Can you share the HTML from your screenshot?

**Comment by vastava** [comment]
Sure, here's the relevant snippet @saadeghi 
```
<div className="flex flex-row align-middle items-center">
  <p className="text-yellow-700"><span className="align-middle text-yellow-700 font-semibold mr-2 text-2xl">{userData.credits}</span><span className="align-middle font-medium">Available Credits</span></p>
  <div data-tip="Your credits can be used for the follwing features:&#10;-feature #1&#10;-feature #2" className="tooltip before:whitespace-pre before:content-[attr(data-tip)]" >
    <svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 20 20" fill="currentColor" className="w-4 h-4 ml-2 text-slate-600">
      <path fillRule="evenodd" d="M18 10a8 8 0 11-16 0 8 8 0 0116 0zm-7-4a1 1 0 11-2 0 1 1 0 012 0zM9 9a.75.75 0 000 1.5h.253a.25.25 0 01.244.304l-.459 2.066A1.75 1.75 0 0010.747 15H11a.75.75 0 000-1.5h-.253a.25.25 0 01-.244-.304l.459-2.066A1.75 1.75 0 009.253 9H9z" clipRule="evenodd" />
    </svg>
  </div>
</div>
```

**Comment by saadeghi** [comment]
@vastava Here's your code on Tailwind Play and it's working as expected: https://play.tailwindcss.com/umiWzsLXYC

Please compare the HTML and CSS output of your page (from dev tools) with this demo on Tailwind Play and see if there are differences in  HTML or CSS? Maybe some styles are missing or getting overridden by another CSS code or maybe the HTML is getting compiled differently for some reason?

**Comment by vastava** [comment]
Thanks; the HTML entity `&#10;` was not working with react, but \n appears to work, for whatever reason.
