### ISSUE TITLE
Change text color of Tabs

### ISSUE THREAD

**Issue by steven1218026** [saadeghi/daisyui#399]
is it possible to change text color of tabs? I tried adding text-red-400 like 
`<a class="tab tab-lifted text-red-400">Tab 1</a> `

but the color stays black or gray.
Also for tab-lifted I was only able to change background color of inactive tab but active tab is always white.
`<a class="tab tab-lifted bg-red-400 tab-active">Tab 1</a> `

Is it also possible to change the color of active tab?
Thank you.

**Comment by saadeghi** [comment]
I added a few CSS variables:  
- `--tab-color`: text color
- `--tab-bg`: background color
- `--tab-border-color`: border color

You need to update to latest version (`1.23.0`)  
You also need Tailwind CSS version `3.0` or above.  
Now you can use these css variables to change colors like this: `[--tab-color:red]`  

Example: https://play.tailwindcss.com/chFnUvubgH

The reason you should use these variables instead of normal color classes is that the tab includes pseudo elements to create the rounded corner and those elements are using CSS gradient with colors for background and border color. So it needs to be a CSS variable to control them all in one place.
