### ISSUE TITLE
Colors of `btn-outline` and `btn` don't align

### ISSUE THREAD

**Issue by p6l-richard** [saadeghi/daisyui#404]
Question:
I'm wondering why the [`btn-outline` applies `base-content`](https://github.com/saadeghi/daisyui/blob/master/src/components/styled/button.css#L137-L139)  (also on hover) as opposed to `neutral-content`, which is the case for [the `btn`](https://github.com/saadeghi/daisyui/blob/master/src/components/styled/button.css#L17-L21). Is that on purpose?

Current behavior:
See [this tailwind playground](https://play.tailwindcss.com/z5AiDILR61)
![image](https://user-images.githubusercontent.com/18185649/149661138-67281e9a-b6f5-48c9-a53a-f904ecf2d615.png)

Expected behavior:
![image](https://user-images.githubusercontent.com/18185649/149661170-147d60de-b811-487c-9262-46348dcf9569.png)

PS: Happy to submit a PR with a fix if this is not the correct behavior (but wanted to ask first as I might've gotten something wrong)

**Comment by saadeghi** [comment]
Neutral color is meant to be a dark color on both light themes and dark themes.  
However, `outline` button must use `base-content` color, instead of the `neutral` color:
>Because on a dark theme, background (base-100) is dark and `neutral` color is also dark. so the button will be hard to see.  

I can't also use `neutral-content` for `outline` button: 
>Because on a light theme, background (base-100) is light and `neutral-content` color is also light. so the button will be hard to see.  

You can see an example here: https://play.tailwindcss.com/d8wGHJiL6O  

If you need a button to be blue, use `primary`, `secondary` or `accent` because those are brand colors. Neutral should be always a dark gray color.  
This is the only way I found to make theme colors dynamic and readable on different combinations. Let me know if found a better solution.
