### ISSUE TITLE
Items too small in Menu on iOS

### ISSUE THREAD

**Issue by Maartin10** [saadeghi/daisyui#411]
Hi,

When using the Menu component, it appears that we have a weird behavior on Safari iOS (I'm using an iPhone XR).

Here's a screenshot of the component page on Safari:

![image](https://user-images.githubusercontent.com/10537052/149819731-6c1e906c-a63b-4cab-8bb5-c632c6a6f755.png)

The icons are way too small, so the component is unusable on an iPhone. Is there a way to fix this?

Thanks in advance,
Martin

**Comment by saadeghi** [comment]
@Maartin10 What version of iOS are you using?

**Comment by boyinrust** [comment]
Assign issue to me ...I'd like to fix

**Comment by arasovic** [comment]
and one more 
![image](https://user-images.githubusercontent.com/9802740/150371822-f1c2deb5-7cb5-407b-a2ba-aa7268aadd66.png)

Model | SM-A520F
Brand | samsung
Operating System | ANDROID
Screen Size | 5.2"
Screen Resolution | 1080x1920
OS Version | 8.0.0

**Comment by arasovic** [comment]
I found something good, maybe you can debug with this value:
`global.window.devicePixelRatio` 
when this value is `1`, everything is okay, but when it is different (I tried in genymotion) everything is blowed up like my answers.
I hope it will be useful. I'm curious about the answer.

**Comment by saadeghi** [comment]
@arasovic this seems like a different issue. Can you please open a new issue and provide a code example (GitHub repo or Tailwind Play page) so I can reproduce the problem?

**Comment by saadeghi** [comment]
@boyinrust sure. The problem is using `:where()` selectors to make the menu components responsive because without `:where` selectors, the last child element will get responsive prefixes instead of the parent.  
What's your plan to fix this without breaking the responsive menu orientation?

**Comment by saadeghi** [comment]
I think the issue only exists on iOS 13 and earlier which [Safari doesn't support CSS `:where()`](https://caniuse.com/?search=where)  
Based on latest [App Store statics](https://developer.apple.com/support/app-store/) (January 11, 2022) I think it's safe to ignore the percentage of users who use old Safari on old iOS versions:

**72% of all devices introduced in the last four years use iOS 15**
- 72% iOS 15
- 26% iOS 14
- 2% Earlier

**63 of all devices use iOS 15**
- 63% iOS 15
- 30% iOS 14
- 7% Earlier

If you're really concerned about those users, keep daisyUI on version `1.24.0` or below.  
Honestly I can't stop using new CSS features because of old browsers.
