### ISSUE TITLE
Links inside collapse don't work

### ISSUE THREAD

**Issue by rallisf1** [saadeghi/daisyui#416]
See demo: https://play.tailwindcss.com/60vi1KT4Dk

Any workarounds?

**Comment by saadeghi** [comment]
I'm not sure if there's a way to fix this because this collapse works with CSS `:focus` and when links gets focused, the collapse loses the focus first and gets closed.  
Workaround: If you add a checkbox, collapse will work with checkbox instead of focus.  
Example: https://play.tailwindcss.com/5pl8vB5oWn

**Comment by grempe** [comment]
Can the clarification that collapse doesn't work with links in the content please be added to the docs?

**Comment by elhe26** [comment]
Any updates?
