### ISSUE TITLE
menu horizontal

### ISSUE THREAD

**Issue by flip111** [saadeghi/daisyui#424]
https://daisyui.com/components/menu/

Here in the first horizontal menu example there is
```html
<ul class="menu px-3 border bg-base-100 menu-horizontal rounded-box">
```

This doesn't work for me, but
```html
<ul class="menu px-3 border bg-base-100 horizontal rounded-box">
```

does work. Maybe documentation didn't get updated with code?

**Comment by saadeghi** [comment]
I think you're not using the latest version. I added below class names on [`1.24.0`](https://github.com/saadeghi/daisyui/blob/master/CHANGELOG.md#1240-2022-01-17):  
- `menu-normal`
- `menu-compact`
- `menu-vertical`
- `menu-horizontal`

`horizontal` still works because of backward compatibility but It's now removed from documents and will be removed on next major version update (`v2.0`)
