### ISSUE TITLE
modal

### ISSUE THREAD

**Issue by ndarproj** [saadeghi/daisyui#470]
1. how to close modal when clicked outside? 
2. for some reason modal isn't closing when I submitted a form. i'm using nuxt and my form has @submit.prevent
```
  <div class="flex justify-between text-white modal-action">
            <button type="submit" class="btn text-white bg-blue-900">Add</button>
            <label for="my-modal" type="btn" class="btn text-white bg-red-900">Close</label>
  </div>
```
3. how do i control the visiblity of modal? i.e I want it to show on page load

**Comment by Siumauricio** [comment]
According #91 you can use this code 

```js
<label for="my-modal-2" class="btn btn-primary modal-button">open modal</label> 

<input type="checkbox" id="my-modal-2" class="modal-toggle"> 
<label class="modal" for="my-modal-2">
  <label class="modal-box">
    <p>Enim dolorem dolorum omnis atque necessitatibus. Consequatur aut adipisci qui iusto illo eaque. Consequatur repudiandae et. Nulla ea quasi eligendi. Saepe velit autem minima.</p> 
    <div class="modal-action">
      <label for="my-modal-2" class="btn btn-primary">Accept</label> 
      <label for="my-modal-2" class="btn">Close</label>
    </div>
  </label>
</label>
```

But honestly, I would like some classname to make the model close after you click outside the modal like modal.

According to docs, you can use modal-open property to control the modal programmatically.

**Comment by saadeghi** [comment]
Thanks @Siumauricio. The problem is, daisyUI is not using any JS by default so I can't define that clicking on a class name do something. It has to be `<label>` to control the checkbox (or use JS)
@ndarproj Siumauricio's example works but if you don't like using all those `<label>`s, using JS is another option:  
https://svelte.dev/repl/5323db962e914919a59ab5a03a6bab4f?version=3.46.4
