### ISSUE TITLE
Circular progress bar support arbitrary start and max

### ISSUE THREAD

**Issue by ewildgoose** [saadeghi/daisyui#512]
Hi, I like the new circular progress bar! However, it currently always starts at the top 12:00 hours position. I wonder if we could make it start at an arbitrary point and have the maximum end at an arbitrary point, eg:

https://codepen.io/naikus/pen/BzZoLL

In my opinion two other options are visually attractive:

1) 180 degrees, starting at 9 o'clock, ending at 3 o'clock, ie half circle with a flat bottom. 

This looks nice if the value is adjusted to become 2 lines, where the base line of the graph is the base line of the text, and any second line is smaller font and hangs slightly below the graph. In the case of the single line, everything is then within a bounding box around the graph (whereas text centred in the circle would have 50% of the line hanging below the bottom of the graph)

2) 270 degrees, open at the bottom. This also looks nice with one or two lines, but again with the main value sitting above the centre line of the box.

I think we can achieve this effect with two new optional values:
- start angle
- total angle

Start angle would be added to a rotation of the ::before and feed into the existing rotation of the ::after, eg:
```
.radial-progress::before {
    transform: rotate(-135deg);
}

.radial-progress::after {
    transform: rotate(calc(var(--value) * 3.6deg - 225deg)) translate(calc(var(--size)/ 2 - 50%));
}
```

The total angle would be a simple scale of the value attribute, ie for 270 degrees, we use (--value * 270/360)

However, as I try this I also notice that it's not so easy to get nice formatting on a 2 line label in the middle. In my opinion (eek), it might be nice to optimise for a 2 line label, where the value would sit above the centre in same size font as present. The optional second line would be a "unit" and be in a 2/3 kind of scale height and sit below the centre line. 

Something like this (random hit from google to illustrate)
  https://www.scriptism.com/wp-content/uploads/justgage-animated-gauges-in-svg.jpg

What do you think?

I think I can work a pull request for the rotation, but I could use some help styling the units/value text?

**Comment by ewildgoose** [comment]
Just mulling this outloud, but ... I arrived here looking for a component I could use as a web component and have an animated dial as I change the value. I'm no CSS expert and I'm not totally sure how I would engineer all of the current gauge to animate (with CSS) as I change the values?

I think it can be done using the SVG equiv gauge (example below), but that is then no longer a pure CSS solution and needs some boiler plate.

- https://css-tricks.com/building-progress-ring-quickly/

Am I missing any simple solution to animate value changes (other than using JS to do some easing of the old/new values)?

**Comment by saadeghi** [comment]
I'm afraid this is not possible with the current structure.  
Currently, radial-progress is single `<div>` and inside of it can be a text.  
`:before` pseudo element creates the radial progress using CSS conic gradient and then it applies a mask to clear the center part of circle. It also creates a circle at the top of circle (to make the start of progress look rounded)
`:before` pseudo element creates another circle to make the end of progress look rounded.

Since it's just one `<div>` and it needs to show a text, we can't put the mask for the div itself and it needs to be on `:before` instead. Also we can't have a third pseudo element for the circle at the start of progress and we can't really have the control on the radial position of it based on current percentage.

Using SVG would't be an option either because I don't want to give developers a long code of SVG to copy/paste.

For animations, It would be easy to animate if it was an SVG but it's not the case. Animating a CSS variable which is used inside a CSS radial gradient needs [`@property` at rule](https://developer.mozilla.org/en-US/docs/Web/CSS/@property) but the [browser compatibility](https://developer.mozilla.org/en-US/docs/Web/CSS/@property#browser_compatibility) is not good yet.

I think it's better to close this issue for now. There wouldn't be any progress on this issue unless someone finds a new method for creating conic gradient with rounded ends inside a single element that would be possible to rotate (without rotating the text inside) and set max value and a start degree.

Feel free to continue the conversation.

**Comment by ewildgoose** [comment]
Hi, I wonder if we are talking past each other? If I literally just add the CSS lines that I give in the first example, then I get all the circular bars rotated by -135 degrees? I tested this only in firefox, so perhaps your point is that this doesn't have cross browser compatibility?

Here is the daisyui demo page with the following CSS added:
```
.radial-progress::before {
    transform: rotate(-135deg);
}

.radial-progress::after {
    transform: rotate(calc(var(--value) * 3.6deg - 225deg)) translate(calc(var(--size)/ 2 - 50%));
}
```

<img width="525" alt="Radial_progress_—_Tailwind_CSS_Components" src="https://user-images.githubusercontent.com/13366/155885996-a72dd95e-c4b1-4bd6-8c96-dd81ad3a873c.png">

**Comment by ewildgoose** [comment]
Additionally note that you can insert SVG into an element using the ::before attribute. So this might be another route? (use url() and a data:... inside that
