### ISSUE TITLE
Warning color not working properly.

### ISSUE THREAD

**Issue by GustavoFenilli** [saadeghi/daisyui#518]
For some reason, only the color for warning is not correcly generating, after looking a bit I found the `--wac` variables is being generated strangely with only 8% level compared to the other color ones around 80%.

![image](https://user-images.githubusercontent.com/14954720/155640957-d2ec75f8-1a32-40ab-ad9a-1aa7b9a048d3.png)

there are the classes that are being applied to the `Button` component `btn btn-block md:btn-wide btn-warning`.
![Capturar](https://user-images.githubusercontent.com/14954720/155641409-5d03f049-c451-4bfe-8ae4-3b44364fe7bd.PNG)
![Capturar](https://user-images.githubusercontent.com/14954720/155641558-9e1ccbbc-4907-4c6a-a81d-41db88c23da0.PNG)

### css
```css
@import url('https://fonts.googleapis.com/css2?family=Poppins:wght@100;200;400;500;700;900&display=swap');

@tailwind base;
@tailwind components;
@tailwind utilities;
```

### tailwind.config.js
```js
const defaultTheme = require("tailwindcss/defaultTheme");

module.exports = {
  content: ['./src/**/*.{js,ts,vue,mdx}'],
  plugins: [
    require('@tailwindcss/typography'),
    require('@tailwindcss/forms'),
    require('@tailwindcss/line-clamp'),
    require('@tailwindcss/aspect-ratio'),
    require('daisyui'),
  ],
  daisyui: {
    themes: [
      {
        light: {
          primary: '#5D15D8',
          neutral: '#1B1B1B',
          'base-100': '#ffffff',
          info: '#1c92f2',
          success: '#118D0F',
          warning: '#C39B0C',
          error: '#AD0A0A',
          '--rounded-btn': '1.5rem',
        }
      }
    ]
  },
  theme: {
    extend: {
      fontFamily: {
        sans: ["Poppins", ...defaultTheme.fontFamily.sans],
      },
    },
  }
};
```

**Comment by saadeghi** [comment]
Content color is calculated using [WCAG contrast ratio](http://www.w3.org/TR/WCAG20/#contrast-ratiodef)  
Based on that ratio if background color is dark I mix the background color with `white`
And if background color is light, I mix the background color with `black` (To show a matching text color instead of black/white)  
In your screenshot, the warning color is considered a light color so the content color will be a dark color. 

This is best for accessibility but you can change that if you want. You can define [`"warning-content"` color](https://daisyui.com/docs/colors/) in your [theme config](https://daisyui.com/docs/themes/) if you want a custom color.

Let me know if you have any questions

**Comment by GustavoFenilli** [comment]
I thought that was the case, but if so, arent info, error and success the same? The outlined ones are almost unreadable.

**Comment by saadeghi** [comment]
Are you using the latest version? because there were color issues before version `2.2.0` and it's fixed now.

**Comment by GustavoFenilli** [comment]
That was indeed the problem, thank you.
