### ISSUE TITLE
Change tooltip text color

### ISSUE THREAD

**Issue by Nuckerr** [saadeghi/daisyui#519]
Hello there, I'm trying change the color of my tooltip. I'm doing it like this:
![image](https://user-images.githubusercontent.com/62883418/155684653-7094a708-1b8c-44f0-8a2e-6bf9b8c27a18.png)
However my tooltip color is still the same as the background:
![image](https://user-images.githubusercontent.com/62883418/155684723-253bcc57-de1c-416f-a97c-c4f38ab202d0.png)

**Comment by saadeghi** [comment]
The problem is when we set the value of a CSS variable on root element (for themes) it applies to the root element and every child element inside except pseudo elements of child elements. So If you want to set the color in your theme, use something like this to target the tooltip class (and its pseudo elements):
```diff
daisyui:{
  themes:[{'mytheme':{
     ...require("daisyui/src/colors/themes")["[data-theme=dark]"],
+    ".tooltip": {
+      "--tooltip-text-color": "cyan"
+    }
  }}]
}
```

**Comment by saadeghi** [comment]
example: https://play.tailwindcss.com/HHgcr4u3ic?file=config
