### ISSUE TITLE
Request to add a Glass Theme

### ISSUE THREAD

**Issue by manishprivet** [saadeghi/daisyui#52]
I really loved the built-in themes, especially the wireframe one. It would be cool if we also had a glass theme, or something like the Windows 10 frosted glass design.

Thanks!

**Comment by saadeghi** [comment]
There's a `.glass` class name as you can see on button and card demo pages. You can use this class name everywhere. But it can't be a theme because:
1. It's a background style and if gets used on every box and element, it will look ugly.
2. Overusing it has a huge performance cost on browser and makes your webpage laggy.

So instead of having a separate glass theme, I think it's better to have a class name and use it occasionally only on specific elements.
