### ISSUE TITLE
Croppy Radial Progress

### ISSUE THREAD

**Issue by effen1337** [saadeghi/daisyui#526]
The new radial progress component is very croppy (on most browsers)

![image](https://user-images.githubusercontent.com/37754407/155848830-d1ef263a-4b51-4c51-a5de-36be1f7324b4.png)
![image](https://user-images.githubusercontent.com/37754407/155848865-72141d69-ee76-4239-a628-6806cb8b599d.png)
![image](https://user-images.githubusercontent.com/37754407/155848872-5ce7de0f-5b1c-4550-bd29-63328a6b0ce9.png)

**Comment by saadeghi** [comment]
It's a CSS conic gradient.  
Make sure your browser is updated and if it is, you should wait for the next version of browser to fix this issue because I can't do anything about it 🤷‍♂️  
You didn't mention the name of your browser but if it's Firefox, here's an open issue for it: https://bugzilla.mozilla.org/show_bug.cgi?id=1720893
