### ISSUE TITLE
Suggestion: Datepicker component

### ISSUE THREAD

**Issue by NathanTe** [saadeghi/daisyui#552]
DaisyUI doesn't seem to have a datepicker component, is there a specific reason for this?
in the readme there's a list of components and it's also not listed there -> only upload is listed there as not present.

**Comment by saadeghi** [comment]
daisyUI is CSS only. Unfortunately it's not possible to style the native HTML date picker of `<input type="date">` using CSS.  
I can add a grid of calendar but that should be named `calendar` because it's just the visual and it won't have the date picking functionality unless there's an external JS file included.

**Comment by NathanTe** [comment]
makes sense, thanks for clarifying.
