### ISSUE TITLE
Form elements do not have associated labels

### ISSUE THREAD

**Issue by friebetill** [saadeghi/daisyui#557]
Is it possible that the drawer example "Navbar menu for desktop + sidebar drawer for mobile" is adapted so that it gets at Lighthouse 100 in accessibility? Right now ~10 points are deducted for "Form elements do not have associated labels" and I haven't managed to fix the problem for several hours.

I tried to fix the problem with different labels like the following:
```
<label htmlFor="my-drawer-3" className="opacity-0 hidden">
  Navigationbar
</label
```
But as soon as I make it `hidden` or `invisible`, the points are deducted again.

**Comment by saadeghi** [comment]
The examples on the site (like [Navbar menu for desktop + sidebar drawer for mobile](https://daisyui.com/components/drawer/#navbar-menu-for-desktop--sidebar-drawer-for-mobile)) are valid and won't cause accessibility warnings because it has a checkbox and it has labels with `for` attribute to point them.  

I see that you're using `htmlFor` instead of `for` If it's not a react project, use `for`.   
If it's a react project, react should convert `htmlFor` into standard `for` in the result code.  

If the problem still exists, please share your code so I can see the issue.
