### ISSUE TITLE
Add border bottom to Links instead of text decoration underline

### ISSUE THREAD

**Issue by ManasMadrecha** [saadeghi/daisyui#57]
First of all, this is simply an amazing plugin. Just discovered it for my Nuxt project and just loving it. 💛

Currently, the class `link` have the property set as `text-decoration: underline`. It would be better to use css that generates from `@apply pb-0.5 border-b` and then the border colour will be similar to link-primary, link-secondary, etc.

**Comment by saadeghi** [comment]
@ManasMadrecha Thanks!  
Is there any downside in using `text-decoration: underline`?  
Padding + border works good only if the link is `inline` otherwise it increases the height of element which might not be ideal on every design. I don't want the `.link` class to behave different on inline/block elements cuz link is a very common element and it should work everywhere (not only an inline text link in a paragraph)
