### ISSUE TITLE
Responsive tooltip does not work as expected

### ISSUE THREAD

**Issue by camslice** [saadeghi/daisyui#575]
`md:tooltip` results in the arrow always being visible.  Arrow should be invisible until `:hover` state makes it visible.

Additionally, `:hover` state on `md:tooltip` fails to make the pseudo element containing the tootltip text visible.

Daisy UI v2.6.4
Tailwind v3.0.23

**Comment by saadeghi** [comment]
`tooltip` does not support responsive prefixes.  
As you can see on the [table here](https://daisyui.com/components/tooltip/), class names are not labeled as `Responsive`

Class names that are responsive and accept prefixes (`sm:`, `md:`, `lg:`, etc.) have `Responsive` in the table. like this one:  
<img width="898" alt="Screen Shot 2022-03-13 at 2 52 01 PM" src="https://user-images.githubusercontent.com/7342023/158058139-eff26240-2a0c-4082-98ec-db3ed655bc6b.png">

The reason is, I don't think there's a need for an element to have tooltip on a specific screen size. Can you tell my why you needed this?

**Comment by camslice** [comment]
Thanks @saadeghi , our use case is site navigation.  On small screens the navigation is vertical and displays both an icon and text.  On wider screens the navigation is horizontal and only displays the icon, so we want to display the text in a tooltip.

*Small:*
<img width="618" alt="small" src="https://user-images.githubusercontent.com/606285/158061292-e341601e-5035-43a8-981a-911312106da0.png">

*Wide:*
<img width="896" alt="wide" src="https://user-images.githubusercontent.com/606285/158061295-9615ee0a-bfcc-4c86-9ceb-ebd9d2bdf387.png">

**Comment by saadeghi** [comment]
Are menu items the same elements? And you teleport them to the drop-down using JS?  
I think the most common practice here is using 2 different menus because they have different layouts.

**Comment by camslice** [comment]
Yes, the same elements. We don't teleport them as such. Just use responsive CSS to modify the layout. Trying to avoid duplicating markup.

**Comment by saadeghi** [comment]
I'm afraid it's not worth it to make the `tooltip` class itself responsive. This class like almost all other components is giving style to its children (before and after in this case) in [many](https://github.com/saadeghi/daisyui/blob/master/src/components/styled/tooltip.css) ways. If I make it responsive, Tailwind will generate responsive classes for all possible combination of parent/child elements and this will increase the file size unnecessarily.  
Other than that, it opens doors to a way I'm not willing to take: People will ask for weird combinations like what if an element has `badge` style on small size and then it has `tab` style on medium size and has `btn` style on the other size... and it's impossible to draw the line while it creates countless unexpected incompatibilities between components.  

I think it's better to stick with the consistency of components. If it's a `tooltip`, it looks like tooltip on all screen sizes. And in your case, I think you should use separate HTML for navbar and the dropdown because they are different components and they have different layouts. 
And it's not really duplication if you think about the result UI. The only duplication here is the icon part because you're already hiding the text near icon on large screen, you're already hiding the tooltip on small screen, and you're hiding the whole vertical list style and the border between items on small screen.

**Comment by camslice** [comment]
Hi @saadeghi , thanks for you consideration.

> If I make it responsive, Tailwind will generate responsive classes for all possible combination of parent/child elements and this will increase the file size unnecessarily.

Correct me if I'm wrong, but shouldn't Tailwind's JIT/purge take care of this?  Surely the file size would only increase if the tooltip is actually used with a responsive prefix.

> I think you should use separate HTML for navbar and the dropdown because they are different components and they have different layouts.

I still disagree that they are different components.  Semantically and functionally the navigation is exactly the same thing.  However I understand that you need to maintain consistency and avoid incompatibility, so I accept this justification.
