### ISSUE TITLE
Enable Dark Theme

### ISSUE THREAD

**Issue by jcparant** [saadeghi/daisyui#60]
Hi,

I'm trying to use Daisyui with Svelte. I want the same result as on the DaysiUi website but all the themes have a white background (dark, halloween etc ...) on my app

I follow this tutorial for install tailwindcss and i follow the DaysiUI documentation for DaysiUI

https://dev.to/matebek/simplest-way-to-set-up-svelte-with-tailwind-css-41bn
https://daisyui.com/docs/install

My meta HTML :  
`<html lang="fr" data-theme="dark">`

tailwind.config.js
`  module.exports = {
  purge: {
    enabled: !process.env.ROLLUP_WATCH,
    content: ['./public/index.html', './src/**/*.svelte'],
    options: {
      defaultExtractor: content => [
        ...(content.match(/[^<>"'`\s]*[^<>"'`\s:]/g) || []),
        ...(content.match(/(?<=class:)[^=>\/\s]*/g) || []),
      ],
      safelist: [
          /data-theme$/,
        ]
    },
  },
  darkMode: false, // or 'media' or 'class'
  theme: {
    extend: {},
  },
  variants: {
    extend: {},
  },
  plugins: [
    require('daisyui'),
  ],
  daisyui: {
    styled: true,
    themes: ['dark'],
    resets: true,
    utils: true,
    logs: true,
    rtl: false,
  },
}`

My result : 
![Screenshot_1](https://user-images.githubusercontent.com/1880969/119815032-65d54600-beeb-11eb-96aa-3bbcef1177ee.jpg)

On website DaysiUI
![Screenshot_2](https://user-images.githubusercontent.com/1880969/119815081-75ed2580-beeb-11eb-80ad-83950bdb1259.jpg)

I tested this but it also doesn't work:
`<div class="container" data-theme="dark">`

TY

**Comment by saadeghi** [comment]
@jcparant I think you need to add `bg-base-100 text-base-content` to your root/container element so everything inside, actually use the colors defined by themes.

**Reason:**  
[Each theme](https://github.com/saadeghi/daisyui/tree/master/src/themes ) is just a set of color values that will be added to Tailwind. So just like Tailwind colors (like `bg-red-100`, `bg-blue-500`, etc), we can use color utility classes (like `bg-base-100`, `bg-primary`, etc)  
When we use `light` theme, it defines that `bg-base-100` is a light background  
and when we use `dark` theme, it defines that `bg-base-100` is a dark background.

Some components (like `card`) don't come with a background color be default (so you can set any color to them).  
But some components (like `btn`) must have a color by default.
So, If we want the card to use base color, we have to add `bg-base-100 text-base-content` to a root/container element or the card itself.
Or if we want card to use primary color, we have to add `bg-primary text-primary-content` to a root/container element or the card itself.

---
Please let me know if you have any questions.

**Comment by jcparant** [comment]
Thank you very much for your help, it works!

**Comment by cwalton** [comment]
Could you point to a reference for text-base<-content>.  I can't find it referenced on the site or in a search of the repo.
I see text-base as a font size attribute in tailwind, but I'm not seeing how this is related to the "content" portion of your solution...  just trying to learn from other's issues...

**Comment by saadeghi** [comment]
@cwalton Color names are [here](https://daisyui.com/core/colors) and we can use them on all utility classes just like [any other Tailwind color](https://tailwindcss.com/docs/customizing-colors)
```
.bg-COLOR_NAME
.text-COLOR_NAME
.placeholder-COLOR_NAME
.from-COLOR_NAME
.via-COLOR_NAME
.to-COLOR_NAME
.border-COLOR_NAME
.divide-COLOR_NAME
.ring-COLOR_NAME
.ring-offset-COLOR_NAME
```

As you can see [here](https://daisyui.com/core/colors) we have `primary` color.  
And `primary-content` is the color of any content (text, border, etc) that should go on a `primary` color.

**Not to be mistaken:**  
`text-base` is [font size from tailwind](https://tailwindcss.com/docs/font-size) but `text-base-100`, `text-base-200`, `text-base-300` are [text colors from DaisyUI](https://daisyui.com/core/colors)  
I know it might look confusing but the color name is `base-100` and can be used as a CSS `text-color`. I couldn't find a better name for base color because ...well it's ...the "base color" of a design 😅

I will update docs with more descriptions.
  
---
Please let me know if you have any questions.

**Comment by cwalton** [comment]
Thanks, this was a great response.  What was making it confusing is the existing tailwind "text-base" and no description of the *-content classes.  

Also, unless I'm missing something (and it might be because I can't find any doc on *-content), in all other cases, the item to decorate comes BEFORE the color and nothing after it accept a scaler (100,200,etc)...  your "text-primary-content" seems inconsistent...   primary is the color but it's smacked in-between two items that we want to decorate. 

I'm assuming that you created "-content" and it's really just a convenience to combine certain already existing utility classes such as text and border, etc.  if you are set on keeping it. then it might be more consistent as just content-color-scale.

That said, if "content" is a creation outside of tailwind, it seems to be a bit like tailwind's fill-current mechanism, except 1) you're naming the color as opposed to inheriting it and 2) you're applying it to more than just an svg.  It almost feels like you could just extend fill to serve your purpose--- resulting examples being fill-primary or fill-base.

I hope this makes sense and that I'm not being too presumptive.

**Comment by saadeghi** [comment]
@cwalton Actually, `-content` is not meant to be a utility class or a variant or a postfix. `primary-content` is a color name (as a whole) and it exists as the perfect color (based on contrast and readability) to be used on a `bg-primary`.

I thought about other names like `primary-foreground` or `primary-fg` or `primary-data` but `primary-content` looks better and easier to remember.

I also think it's important to give designers freedom to choose their exact color to use on their design, so I don't want to automatically choose a text-color based on background-color. I think if you have a primary button that is pink, you should be able to decide if you want text color of that button to be black or white or maybe a darker pink.

**Comment by cwalton** [comment]
Thanks!  Your statement "primary-content is a color name" explained it all - and you should definitely add that to the docs.

The project is fantastic... and thanks for sharing it with the world.
