### ISSUE TITLE
Svelte scroll bindings do not work

### ISSUE THREAD

**Issue by jaads** [saadeghi/daisyui#670]
I'm using Svektekit with daisyui and I have the following problem. I want to bind the scrollY value from the window to a variable like so:
```
<svelte:window bind:scrollY />
```
The variable is suppose to change its value when scrolling in the window. But apparently the value did not change. I figured that this was due to the fact that I added the binding with the `drawer` component class from DaisyUI.  If I place the binding outside the drawer, another scroll window appears in which the binding works. 

Is this a known limitation of the drawer component?

**Comment by saadeghi** [comment]
With `drawer` it's the `drawer-content` div that scrolls instead of window.
So if you get the scroll s position of `drawer-content` instead of window, that should work.

Check out this code from daisyUI document website: https://github.com/saadeghi/daisyui/blob/master/src/docs/src/routes/__layout.svelte

Let me know if you have any questions

**Comment by jaads** [comment]
That worked. Thanks so much!
