### ISSUE TITLE
Theme styles not fully applied?

### ISSUE THREAD

**Issue by atresnjo** [saadeghi/daisyui#7]
Hi, first I want to say thanks for the great work; the components look great!

I wanted to play around with the components for a possible project, so I created a test app using https://www.npmjs.com/package/cra-template-tailwindcss-typescript

I followed the instructions and installed it via npm, almost everything works; but when I set a theme using data-theme the font colors don't update, and for example navbar background color doesn't update; like it does in your demo. Hope you can clear this up for me, thanks a lot! 👍 

Here's how it looks compared to yours
![image](https://user-images.githubusercontent.com/41112852/106041932-b32bdd00-60dc-11eb-95dd-77972d4b8c2c.png)

**Comment by saadeghi** [comment]
Thanks for using DaisyUI @atresnjo   
Did you add the colors to your `tailwind.config.js` file?: https://daisy.js.org/docs/config  
example:
```
module.exports = {

    // add DaisyUI plugin
    plugins: [
      require('daisyui'),
    ],

    // add DaisyUI colors 👇👇👇
    theme: {
      extend: {
        colors: require('daisyui/colors'),
      },
    },

  }
```
Because from what I see in your screenshot, it looks like the components are showing the right color but you can't use utility classes like `bg-content-800` or `text-content-100` directly in your HTML unless you add add `daisyui/colors`.

Please let me know if you have any questions.

**Comment by atresnjo** [comment]
Ahh. I did forget that, got it working now. Thanks! 💯
