### ISSUE TITLE
Feature Request: Classes for tabs

### ISSUE THREAD

**Issue by Blakeinstein** [saadeghi/daisyui#706]
I love the design that daisyui has but since I am using vanilla html (with astro) I am finding it difficult to quickly get a smooth transition for tab panes from tab bars.

I was looking for something similar like this where I can toggle classes to make tabs visibile via JS
https://tailwind-elements.com/docs/standard/navigation/tabs/

I tried using swap (as I only have two panes right now) but swaps break any nested swaps and since swap sets opacity to 0, they dont allow hover animations on the bottom swap.

**Comment by Blakeinstein** [comment]
> You can use most framework components (Svelte, Vue, React, etc.) in Astro. You just need to hydrate it

And thats the thing. Sometimes, you dont really want to include a framework for something that can be simply be achieved by a bit of js and css classes 🤔

**Comment by saadeghi** [comment]
You can also use vanilla JS in astro.  
But I would use a Svelte component in this case. because unlike Vue or React, Svelte is just a compiler that generates vanilla JS (and does not add a whole framework library to your production code) so using Astro with hydrated Svelte components would be a good combination.
