### ISSUE TITLE
How to use DaisyUI with standalone version of TailwindCSS?

### ISSUE THREAD

**Issue by ddahan** [saadeghi/daisyui#770]
Tailwind provides a [Standalone version](https://tailwindcss.com/blog/standalone-cli) to be used in a project where it makes no sense to use `npm`.
Is there a way to use DaisyUI with it? (without relying on the CDN version)

**Comment by saadeghi** [comment]
You can use the CSS file ([full.css](https://unpkg.com/browse/daisyui@2.14.3/dist/)) from CDN or download it. The only downside would be the file size (300KB) if you don't remove unused styles.

If you find a tool for your [non-node] environment to remove unused CSS (like Purge CSS) to remove the unused styles, that would be ideal.

**Comment by ddahan** [comment]
> The only downside would be the file size

Other downsides:
- No autocompletion or CSS display on Daisy classes hover
- No custom theme

At this point I prefer sticking with raw Tailwind UI :/

**Comment by saadeghi** [comment]
I can't do anything about auto completion because it's something Tailwind CSS intellisense is handling and it only works if daisyUI is installed as a plugin for Tailwind CSS (but the stand alone setup doesn't support third party plugins...)

But custom themes can be included. Themes are basically a few CSS variables with HSL colors so you can make custom themes like [this file](https://unpkg.com/browse/daisyui@2.14.3/dist/themes.css)

**Comment by ddahan** [comment]
Thanks for your answer. At this point, after reading how [pkg](https://github.com/vercel/pkg) (the tool used by tailwind to make the node version standalone) works, I think it would be easy for Tailwind team to provide option to include plugins. But I guess they have no commercial incentive to allow that, as Daisy UI is (more or less) in competition with their own paying product like tailwind UI. I guess the best solution would be to make the build by myself (or rely on another developer that did it).

**Comment by saadeghi** [comment]
@ddahan I haven't tried `pkg` but If you (or someone else is willing to contribute on that I will support the project. Because the CDN CSS size is increasing slowly and a JS file would make more sense.

**Comment by b4-io** [comment]
Hello this must be a little late but i just stumble with the same problem and leaving this for anyone whom might stumble with the same problem.

What i did to solve this issue was bundle daisyUI into a single self contained file with a command like:
```bash
npx esbuild ./src/index.js --bundle --platform=node --outfile=daisyui.js
```

Then i copied that file into my project and in my `tailwind.config.js` required it like this:
```
plugins: [require("./static/assets/scripts/daisyui")],
```

Everything seems to work with this, even intellisense (in VSCode)

**Comment by moshe5745** [comment]
@b4-io Thats awsome! Thanks a lot.
Is there a way to setup some repo that will take the latest version and will generate the js for download?
In another words how can we be sync with latest daisy and tailwind versions?

**Comment by b4-io** [comment]
@moshe5745 should be doable with a bash script, that pulls everything you need like `https://github.com/saadeghi/daisyui/releases/latest`, i personally ended up just using pnpm because it's less of a strugle.

Maybe when my project is production ready an stable will clean a bit all my js deps and do it by script instead of pnpm

**Comment by mcinj** [comment]
Can confirm, that with tailwindcss cli v4, if you download the `daisyui.js` and `daisyui-theme.js` from a release, which @b4-io said is easy enough with a script, you can generate a tailwind + daisyui css file. Here is my input.css which includes all themes, but that can be modified to just add what you want. Note I have `daisyui.js` and `daisyui-theme.js` in a subfolder called `plugins` and I call `tailwindcss` from the same folder `input.css` is in.

```
@import "tailwindcss" source(none);
@source "../templates/*.{gohtml,js}";
@plugin "./plugins/daisyui.js" {
    themes: all;
}


@tailwind base;
@tailwind components;
@tailwind utilities;
```
