### ISSUE TITLE
how can use css variable in custom theme

### ISSUE THREAD

**Issue by marefati110** [saadeghi/daisyui#776]
i want to use custom css variables to generate theme dynamicly at runtime 
so i want to use var function in theme like this 

```js
daisyui: {
  themes: [
    {
      mytheme: {
          primary": "var(--primaryColor)",
      },
    },
  ],
},
```

but got error 

```bash
./node_modules/next/dist/build/webpack/loaders/css-loader/src/index.js??ruleSet[1].rules[3].oneOf[8].use[1]!./node_modules/next/dist/build/webpack/loaders/postcss-loader/src/index.js??ruleSet[1].rules[3].oneOf[8].use[2]!./src/styles/globals.css
Error: Unable to parse color from string: var(--primaryColor)
    at Array.forEach (<anonymous>)
    at Array.forEach (<anonymous>)
    at Array.forEach (<anonymous>)
```

im using nextjs 12 and i set css varibales in _document.js

```jsx
    <Html >
      <Head>
        <style global jsx>
          {`
            :root {
              --primaryColor: #F000B8;
            }
          `}
        </style>
      </Head>

      <body>
        <Main />
        <NextScript />
      </body>
    </Html>

```

**Comment by saadeghi** [comment]
config only accepts color values because it goes into a color function and processes the HSL values, etc...

daisyUI is already using CSS variables for each color ([see this](https://unpkg.com/browse/daisyui@2.14.3/dist/themes.css)). 
So if you want to use CSS variables, you can just use the built-in CSS variable for each color like `--p`, `--s`, etc. [[see the this table for reference](https://daisyui.com/docs/colors/)]

Or if you want a custom theme to use your own CSS variables, with theme, you can re-use daisyUI variables like this:

```css
--myColor: 259 94% 51%; /* HSL values */
/* put the custom variable name in daisyUI --p variable */
--p: var(--myColor);
```

Let me know if you have any questions

**Comment by marefati110** [comment]
thanks
