### ISSUE TITLE
daisyUI now does not work with windicss?

### ISSUE THREAD

**Issue by cvkmohan** [saadeghi/daisyui#789]
Post the release of `daisyUI 2.0` which now depends on `tailwindcss 3.0` and later `postcss` also added as a dependency - now, windicss and daisyUI do not work together? 

I observed that during 1.x.x versions of daisyUI, things were smooth. Any specific reason you moved in this route?

**Comment by saadeghi** [comment]
Windi CSS + daisyUI always had issues together. Even in earlier versions there were several bugs in style generation.  

I wish I could fix these issues on my end but the problem is from Windi's `Transform API` (that transforms Tailwind CSS plugins to Windi CSS) and it does not generate the expected CSS.

Let me know if you have any questions.

**Comment by cvkmohan** [comment]
Thanks for the explanation @saadeghi . Sorry for creating it as an issue. It is no bug. Just wanted to know information.
I was looking at windicss and unocss. But, considering lack of option to choose something like daisyui there would force me to stay with regular tailwind.
I think unocss with full css  of Daisy and additional purge is the best option in that route.
Keep doing the good work. Thanks a lot.

**Comment by saadeghi** [comment]
Yes. Using daisyUI independently will work. I think currently this is the only option if you want to use Windi CSS or Uno CSS with daisyUI.

**Comment by hrqmonteiro** [comment]
> Yes. Using daisyUI independently will work. I think currently this is the only option if you want to use Windi CSS or Uno CSS with daisyUI.

How does one uses Daisyui independently, what do you mean?

**Comment by saadeghi** [comment]
@hrqmonteiro I mean instead of using daisyUI as a plugin, use the daisyUI CSS file for component classes and use any CSS generation engine (Tailwind, Windi or anything) for utility classes.

You will lose daisyUI `config` modifications and you will need another build step to purge unused CSS (using PurgeCSS, UnCSS, etc)
