### ISSUE TITLE
Navbar is fixed, Stat is displayed overlapping

### ISSUE THREAD

**Issue by ina6ra** [saadeghi/daisyui#80]
I have prepared the code to reproduce the problem.
https://play.tailwindcss.com/eyp72zJWTm

I had the same problem with Hero, but I solved it by adding the following CSS.

```
.hero {
  display: inherit;
}
```

Please tell me how to solve with Stat.

**Comment by saadeghi** [comment]
Looks like items inside a grid have higher z-index than a fixed element (because none of them have z-index by default) 🤔  
You can fix this by adding any z-index to `nav`  
```html
<div class="navbar ..... z-10">
```
https://play.tailwindcss.com/hLMyTj3HBJ

I can add a default z-index to the source code of `.navbar` but I'm not sure if it's a good decision since `navbar` might be fixed or not, might be used multiple times on a page and people should decide what element must be on top.  
For example if I want a fixed `card` component to stick on top corner of page, it *should* go on top of `navbar`.  
So I think the value of z-index must be up to the the developer.

Please let me know if you have nay questions.

**Comment by ina6ra** [comment]
@saadeghi Great Thanks!
I was able to solve it by adding z-10 to the ``.navbar``.
I also removed the ``.hero`` display.
