### ISSUE TITLE
Cannot make a table with DaisyUI on svelte

### ISSUE THREAD

**Issue by yajatvishwak** [saadeghi/daisyui#809]
![image](https://user-images.githubusercontent.com/25704867/169642300-89d5ba64-df7a-4f61-a8f5-bfe7ce87543e.png)
App.svelte
![image](https://user-images.githubusercontent.com/25704867/169642406-7cd37089-1e9b-4492-80fc-416821b84dca.png)

tailwind.config.js
![image](https://user-images.githubusercontent.com/25704867/169642418-afec7e6b-caf3-4286-8081-7543cf3b93dc.png)

**Comment by saadeghi** [comment]
Can you share a sample repo so I can reproduce the issue?

**Comment by saadeghi** [comment]
This issue must be fixed from Svelte.  
When we use `<style global>`, svelte tries to handle styles with `:global()` but it doesn't process `:where()` correctly.  
`table :where(th, td)` is a valid CSS selector that I used in daisyUI but Svelte changes it to `:global(.table) :global(:where(th), :global(td))` which is wrong.

Current workarounds:  
1. You can use this on your main layout (without `global`)
  ```html
  <style lang="postcss">
    @tailwind base;
    @tailwind components;
    @tailwind utilities;
  </style>
  ```
2. Or you can import one postCSS file instead of use `<style>` tag:  
https://stackblitz.com/edit/daisyui-svelte-vite?file=src%2Fmain.js
