### ISSUE TITLE
Tooltip With Long Text

### ISSUE THREAD

**Issue by alaboudi** [saadeghi/daisyui#84]
Firstly, thank you very much for the library. It's very nice

Now for the real business, I think we can do some work to accommodate longer text in the tooltip. Currently, if long text is placed in the `data-tip` attribute, it will all be rendered in one line. I think it would be beneficial to find a way to render the text in some sort of max width container. Below is a screenshot of the current behavior

![image](https://user-images.githubusercontent.com/7456621/121982855-56188700-cd5e-11eb-98a1-a8be1f0108b0.png)

**Comment by predam** [comment]
I still have this issue in 1.25.4

**Comment by saadeghi** [comment]
Tooltip is maxed at 320px: https://play.tailwindcss.com/6mawszp8e0

**Comment by feliche93** [comment]
@saadeghi how would you overwrite this? I tried max-w-[20], but nothing changed. Does it need to be applied in another way?

**Comment by saadeghi** [comment]
Here's an example of overwriting width:  
https://play.tailwindcss.com/xHsRRr5rSt
```
before:w-[20rem] before:content-[attr(data-tip)]
```

**Comment by feliche93** [comment]
@saadeghi awesome thank you for the almost instant reply! Also huge shootout for creating and open-sourcing this in the first place! I am using it in all my projects!

**Comment by i-engy** [comment]
any chance to add line break in data-tip for tooltip

**Comment by saadeghi** [comment]
@i-engy To be honest, this was not predicted while designing so it won't work by default. because `data-tip` is a data attribute and can't have new lines. and its value is being used as the content of tooltip's `:before` pseudo element as a string.

But there is a hacky way to do it. we can directly change the Tailwind CSS variable which is responsible for the `content` and use `\a` character to add a line break and we should use `_` instead of space (because we can't have space inside a class name): 
```html
<div
  class="m-72 tooltip tooltip-open before:whitespace-pre-wrap before:[--tw-content:'line1_\a_line2']" data-tip
  >
  <button class="btn">Button</button>
</div>
```

I won't recommend doing this but anyway...

I will try to make some changes on the next version of daisyUI to get rid of these limitations.

**Comment by i-engy** [comment]
Thanks @saadeghi . appreciate it. 
few suggestions for next update:-

- multi line or html <br> inside tooltip text.
- if possible to make tooltip aware of screen ends so that it can autoshifts from right to left/bottom/up and viceversa for all other directions.

I will wait for next update. No hurry.

**Comment by saadeghi** [comment]
> * if possible to make tooltip aware of screen ends so that it can autoshifts from right to left/bottom/up and viceversa for all other directions.

You would need JS for that. So it's not possible with daisyUI but you can use a JS plugin for tooltip and it works well alongside daisyUI

**Comment by dmiro** [comment]
> Here's an example of overwriting width: https://play.tailwindcss.com/xHsRRr5rSt
> 
> ```
> before:w-[20rem] before:content-[attr(data-tip)]
> ```

For strange reasons, your example doesn't work correctly for me. Instead this code work properly:

`before:whitespace-pre-wrap before:content-[attr(data-tip)]`

**Comment by trycoast** [comment]
> > Here's an example of overwriting width: https://play.tailwindcss.com/xHsRRr5rSt
> > ```
> > before:w-[20rem] before:content-[attr(data-tip)]
> > ```
> 
> For strange reasons, your example doesn't work correctly for me. Instead this code work properly:
> 
> `before:whitespace-pre-wrap before:content-[attr(data-tip)]`
> 
> https://play.tailwindcss.com/UY2yiyqgY3

Thanks! This also worked for me. I'd love to see the tooltip upgraded in the next version of DaisyUI.

**Comment by piotrberlowski** [comment]
> Thanks @saadeghi . appreciate it. few suggestions for next update:-
> 
>     * multi line or html <br>\ inside tooltip text.
> 
>     * if possible to make tooltip aware of screen ends so that it can autoshifts from right to left/bottom/up and viceversa for all other directions.
> 
> 
> I will wait for next update. No hurry.

I just ran into an issue similar to this. My app has a number of text inputs at the top of the screen and on a mobile UI the tooltips (even tho they're invisible) were pushing out the boundaries of the screen and causing scrollbars to appear. Anyway, I'll figure out a way around it.
