### ISSUE TITLE
Add tab transition

### ISSUE THREAD

**Issue by Cokaps** [saadeghi/daisyui#88]
I'm trying to add tab transition (I mean I have tab 2 with `tab-active` class, when I click on tab 1, it will remove `tab-active` from tab 2 and add `tab-active` class to tab 1)
Here is my logic on [codepen](https://codepen.io/loctran016/pen/JjWzErq) but it doesn't work.
Thanks for your help in advanced.
Would be nice if it have tab transition by default

**Comment by saadeghi** [comment]
Since you're using alipne, there's an easier way to make tabs:  
https://codepen.io/saadeghi/pen/qBrvmBP?editors=1000  

I can add functionality of switching tabs to daisyUI with CSS only  
...but it would be a noisy HTML with invisible checkboxes.  
I think It's better to handle it with JS.  
Tabs might be link to pages or they might be just visual or they might just switch the visibility of items. It's such a generic element
