### ISSUE TITLE
Accessibility issue with dropdowns. Keyboard navigation.

### ISSUE THREAD

**Issue by tobealive** [saadeghi/daisyui#885]
There is a keyboard accessibility issue with dropdowns which gets especially visible using an extension like vimium. First I thought it's because of daisUI being css only, but It's working with components like the drawer component. That's why I hoped it could be a fix without too many efforts.

Following a short video. It shows: 
1. trying to trigger a dropdown component at the top left of the components preview. Not working
2. triggering a drawer component. Is working
3. re trying No. 1. Not working
4. Moving to headlessUI and triggering and closing a dropdown via keyboard vimium shortcuts. Is working

The same holds true for testing the daisyUI components separately

https://user-images.githubusercontent.com/34311583/175052949-d6552925-a69f-41f6-8823-92b11784d103.mp4

--- 
Some additional circle jerk my fingers produced:
Looking at the download stats in the Chrome and Firefox store, just the vimium extension has nearly 500.000 users. Taking into consideration that this is mainly a hacker's extension, there is definitely a good number of direct installations from sources like GitHub etc., so the actual number is probably higher.  What I'm trying to say is that I hope that I'm not the only one who gets a bit happier having dropdowns working on the sites that work with beautiful daisyUI.

**Comment by CanRau** [comment]
Hey, I don't think only Vimium users should be considered as there's lot of people (don't have numbers) which rely on keyboards for navigation for various purposes.

I just stumbled upon this issue myself while considering bringing DaisyUI into a project. I mean I can keep HeadlessUI for the dropdown, at least for now, but still would be nice if this could be addressed 😇

In general though DaisyUI is very impressive 🥰👏

**Comment by saadeghi** [comment]
Honestly, there are limitations when everything is handled with CSS (no JS) 😔  
Where we don't have `click` events, we can only use labels and checkboxes to toggle the visibility of elements.  
I don't want to brag but checkboxes and labels are pretty old HTML elements and they are being used for many years.  
If a keyboard navigation plugin or a screenreader is not able to click them, it's their issue.  

Of course we can use alternative elements to make things more accessible.   
We can use JS to show/hide elements. We can use JS to make it possible to navigate with arrow keys. etc.  
But this specific issue should be fixed by the a11y plugin maintainers. Until then, I recommend using JS click events to show/hide stuff.

Let me know if you have any questions.

**Comment by CanRau** [comment]
Yea sorry haven't considered that it's not using JS 😅

**Comment by saadeghi** [comment]
> Uh, what a11y plugin are you referring to?

https://vimium.github.io/

**Comment by CanRau** [comment]
Uuh alright, I wouldn't necessarily consider this an a11y plugin 😅

I totally get the "issues" maybe it'd be possible to provide info on
accessibility and might even be possible to provide JS versions or
inspiration where it makes sense.
Though just sharing some thoughts totally understand that it's Open Source
and might not be your priority.
Would help with a PR if I had the time 😅

**Comment by japomani** [comment]
I was looking at DaisyUI as a potential option, but the attitude expressed here about accessibility has convinced me not to use it

**Comment by saadeghi** [comment]
@japomani I don't know what you're talking about my friend. What "attitude"?  
daisyUI and Vimium are both free and open-source projects and no one gets paid if you use them or not.  

If you want me to magically fix the problems of a Chrome plugin using CSS, it's simply not possible whether you like it or not.
