### ISSUE TITLE
Programmatically change one value in a theme 

### ISSUE THREAD

**Issue by justingolden21** [saadeghi/daisyui#888]
Hi, I've got a project where I want to have a theme that has all of the same values, except I want to switch the primary color between one of three values programmatically. I was wondering if this is possible in DaisyUI. Thanks 😄

**Comment by saadeghi** [comment]
See this https://github.com/saadeghi/daisyui/issues/660#issuecomment-1080117466

Let me know if you have any questions

**Comment by justingolden21** [comment]
I think I get it. Change the `--p` css variable in `:root` with JS. 

Think this should help me: https://www.w3schools.com/css/css3_variables_javascript.asp

Closing this ticket.

**Comment by saadeghi** [comment]
CSS variables like `--p` should have the HSL values (not hex)

The reason is, daisyUI only uses HSL values and later on adds opacity values defined by Tailwind CSS utility classes (if exists). That wouldn't be possible with hex values.

You can see the HSL values of all colors from built-in themes here: https://unpkg.com/browse/daisyui@2.17.0/dist/themes.css
