### ISSUE TITLE
Document all CSS variables

### ISSUE THREAD

**Issue by MoritzRS** [saadeghi/daisyui#904]
[This guide](https://daisyui.com/docs/themes/#-5) lists some CSS variables that can be specified in a theme.
By looking through the code I found out that there are more variables being used like `--padding-card` which can also be passed in the theme configuration.
It would be nice if all css variables were at least listed within the same page as linked above.
This would make it easier to build detailed customized themes for projects.

Another topic worth discussing might be rethinking the usage of the individual variables.
I still can't get my head around why the range component uses rounded-box for it's radius instead of an own value.
Just some thoughts on the matter since I'm currently trying to create a customized theme

**Comment by MoritzRS** [comment]
If such an addition to the documentation is welcomed, I could also create the PR myself

**Comment by saadeghi** [comment]
The reason some CSS variables are not listed:  
- Some of CSS variables are only being used internally. Just to pass some value to keep the style as it should be. Almost no one would ever need to modify them and they have no effect on themes.
- And some of undocumented CSS variables are going to get removed!
On earlier versions of daisyUI, I used CSS variables everywhere. It turns out, some variables were unnecessary.  
So, everything that is inside docs, will stay (at least in the next 2 major versions) and everything else will be removed. I can't just remove things suddenly because backward compatibility.

About the border radius on range component:  
That might be a mistake. I will look into that one soon.

Let me know if you have any questions

**Comment by teenjuna** [comment]
@saadeghi by «everything that is inside docs» you mean [this](https://daisyui.com/docs/themes/#-5) section?

**Comment by MoritzRS** [comment]
@saadeghi Thanks for clarifying!

**Comment by saadeghi** [comment]
@teenjuna yes
