### ISSUE TITLE
Massive (100kb) size increase in CSS file between 2.18.1 and 2.18.2

### ISSUE THREAD

**Issue by softgripper** [saadeghi/daisyui#935]
Massive (100kb) size increase in CSS file between 2.18.1 and 2.18.2

Maybe intentional?  Not sure.  I initially commented on unocss integration - thinking it was that, but no - it's the dist/full.css that has significantly grown.

Version | Size | URL
------ | ------ | ------
2.18.1 | 38.6kb | https://cdn.jsdelivr.net/npm/daisyui@2.18.1/dist/full.css 
2.18.2 | 137kb | https://cdn.jsdelivr.net/npm/daisyui@2.18.2/dist/full.css

Not sure of the change that caused this - can't manage to diff the versions though Github.

**Comment by saadeghi** [comment]
Thank you for reporting.  
I think the recent Tailwind CSS update is causing this. This is not a mistake tho. They changed the way color utilities are generated and now more color utilities are being generated.  
I will investigate this tomorrow.  

But don't forget to use a CSS purge tool for production to remove unused CSS classes. The CDN file is not meant to be used for production.

**Comment by softgripper** [comment]
Yeah I'm not using the CDN.  I'm importing directly from the npm module - just easier to link in the issue.  Using in a similar way to the unocss stackblitz test - which I believe you put together :) 

I'll try to plug in a purge to alleviate.

**Comment by saadeghi** [comment]
Alright, the size increase is happening because of recent changes in [Tailwind CSS `3.1.0`](https://github.com/tailwindlabs/tailwindcss/blob/master/CHANGELOG.md#310---2022-06-08).  
Before this version, a lot of color utilities and their opacity variations were missing. Now all combinations are being added to the CSS file.   

I think this is a good change, however file size increases and that's inevitable.  
At some point, when files size gets too large, we should stop using a single CSS file for daisyUI CDN and provide a JS file (just like Tailwind CSS 3)
