### ISSUE TITLE
Cannot use CSS variables in theme colors

### ISSUE THREAD

**Issue by jquesada2016** [saadeghi/daisyui#940]
Attempting to do the following fails:

```js
// ...
{
  daisyui: {
    themes: [
      {
        dark: {
          "base-100": "var(--background-dark)",
          // ...
        }
      }
    ]
  }
},
// ...
```

Trying to do so results in the following error:
```
Unable to parse color from string: rgb(var(--background-dark))

```

This is something that works and is compatible with tailwind theme config settings.

**Comment by jquesada2016** [comment]
I forgot to mention, assuming `--background-dark` is a hex value of the form `#112233`. I also tried with `rgb(var(--background-dark))` where `--background-dark` is of the form `11, 22, 33`.

**Comment by saadeghi** [comment]
Your sample code will not work because daisyUI needs a valid color value (RGB, Hex, HSL) to compile it, and extract the brightness value in order to generate other colors automatically.  

However, daisyUI is already using CSS variables for all color values and you can see them in [this table](https://daisyui.com/docs/colors/)  
The value of daisyUI CSS variables are HSL values ([see this](https://unpkg.com/browse/daisyui@2.20.0/dist/themes.css)) so you can simply edit colors by changing those CSS variables.  
Or by putting your own CSS variable inside that:
```css
:root{
  --my-primary-color: 284 22% 80%; /* space-separated HSL values */
  --p: var(--my-primary-color);
}
```

Let me know if you have any questions.

**Comment by luq89** [comment]
Hey folks, im having trouble with this too. :/
When defining the css var purely as a space-spereated hsl value the browser is not able to interpret it correctly. Therefore the var looses its purpose completly. 

`:root {  
  --c-primary: 174 100% 30%; // working  
  --c-primary: rgb(0, 153, 138); // not working
  --c-primary: hsl(174 100% 30%); // not working
  --c-primary: #00998a; // not working
  --p: var(--c-primary) !important;   
}`

It think having more flexibility defining how to overwrite the daisy vars would be nice. For eg. why can't i use my default tailwind theme out of the box (given that the vars share the same name)

**Comment by saadeghi** [comment]
It's not possible (yet) to use the color itself (like `hsl(174 100% 30%)` or `#00998a`) in the CSS variable  
Because that way how can Tailwind CSS opacity utility classes (like `opacity-50`) apply the alpha value to the value of a CSS variable?

Colors in the Tailwind CSS config 👇
```js
module.exports = {
  theme: {
    extend: {
      colors: {
        'mycolor': '#1da1f2',
      },
    },
  },
}
```
get processed at the build time to 👇
```css
.bg-mycolor {
  --tw-bg-opacity: 1;
  background-color: rgb(29 161 242/var(--tw-bg-opacity));
}
```
because the processor is working at build time and it exactly knows what is the color and can change the format and can add opacity to it. Now people can use opacity utility classes like `bg-opacity-50` or even shorthand `bg-mycolor/50`

But we need to change the color values at run time because all colors are dynamic and their value should be able to change if the theme changes. It can't be hardcoded to the class name like `bg-red-600` value is hardcoded.

So we should extract the numeric value of the color and put it inside a CSS variable [like this](https://github.com/saadeghi/daisyui/blob/master/src/theming/index.js) This way, Tailwind can generate color utility classes for all additional color and all the opacity utility classes will work with it as well.

Right now, this is the only way. Maybe with the next major version of Tailwind CSS we can have new methods.

Also, when the new CSS color function gets more browser support we can use CSS in runtime to manipulate color values, color formats and color opacities so Tailwind won't need to do all those processing format change in the runtime.
