### ISSUE TITLE
Feature Request: Config Option to compliment state selectors

### ISSUE THREAD

**Issue by StoraH** [saadeghi/daisyui#970]
### Feature request
This issue is a request to add an option in the DaisyUI config that allows complementing the pseudo-classes that control the state (e.g. :checked) of a component with any selector of choice.
### Rationale
I tried to use DaisyUI together with [radix UI](https://www.radix-ui.com/) and for the most part, it works great. The way radix is handling the state of its components is through data attributes like `[data-state]` and that's where it became an issue for certain components like [Toggle](https://daisyui.com/components/toggle/). I like that daisy is "locked" to write a checkbox as an actual checkbox but it would be nice to be able to opt-in to handle the state with javascript.

### Proposed Implementation
Please look at the [pull request linked to this issue](https://github.com/saadeghi/daisyui/pull/969) for details. 
When writing the code (and this issue) I had a look at how the prefix option was implemented and tried to follow the same patterns. I think some optimizations can be made in the way the configuration is read since they are very similar.

**Comment by StoraH** [comment]
The issue doesn't seem to be assigned to me, please help 🙏

**Comment by saadeghi** [comment]
Thank you for contribution.  
But I'm not sure if this should be a config. We can simply add class names for checkboxes or radio buttons that need look as active.

For example we can add both selectors in daisyUI:
```css
.toggle:checked,
.toggle-checked{

}
```
And it allows use to have a custom element that looks like a checked checkbox.

I think this is simpler and less confusing than having a exclusive config object for it.

**Comment by StoraH** [comment]
Thanks for the fast reply!
Yes, that would suffice in the scenario where you have control over the HTML, but when using a third-party library like radix that owns the HTML it gets trickier. I think is a good idea to unlock the possibility to choose the state selectors to match the pattern of the app you working on.

**Comment by saadeghi** [comment]
I don't have experience working with Radix. Can you please tell me how you use daisyUI classes in Radix and what exactly is the issue?  
Can you have a custom class name for a checked checkbox or does Radix add a data-attribute or...?

**Comment by StoraH** [comment]
I created a sandbox, easier than explaining the base usage 😄 https://codesandbox.io/s/determined-goldstine-oqgcne?file=/App.js 
_I saw that the color of the radix toggle looks a bit off and I traced it down to that tailwind rest get's applied last. So don't mind that one._

The `data-state` attribute looks like the one radix uses [doc](https://www.radix-ui.com/docs/primitives/components/checkbox#root).

**Comment by saadeghi** [comment]
Thank you!  
I see that Radix is also controlling `aria-checked` attribute when we check the checkbox.  
Since aria attributes are considered as a11y standard, I think applying style to `.toggle[aria-checked=true]` will fix everything. it makes the checkbox to show as checked when Radix changes `aria-checked` to `true` and it will compatible to any other component library that use the standard `aria` values.

So, all it takes is to add `.toggle[aria-checked=true]` to [this file](https://github.com/saadeghi/daisyui/blob/master/src/components/styled/toggle.css) (lines 11, 32, 43, 54)

other components that need this addition would be [`checkbox`](https://github.com/saadeghi/daisyui/blob/master/src/components/styled/checkbox.css), [`radio`](https://github.com/saadeghi/daisyui/blob/master/src/components/styled/radio.css), [`rating`](https://github.com/saadeghi/daisyui/blob/master/src/components/styled/rating.css)

**Comment by StoraH** [comment]
I did even think of that, really good idea 👌 Feels like the correct solution. Let me know if you need any help!

**Comment by saadeghi** [comment]
I will fix it today. Thank you 🙌

**Comment by quangv** [comment]
Does this work with `btn-primary` for example:

```jsx
<form className="group">
  <button className="btn group-focus-within:btn-primary group-focus-within:text-primary-content" />
</form>
```
