### ISSUE TITLE
Unable to change collapse's bg color

### ISSUE THREAD

**Issue by eandresvera** [saadeghi/daisyui#98]
Great work doing daisyui!.

I'm unable to  change the background color of collapse component:
![ ](https://user-images.githubusercontent.com/59941150/124057643-de04bf00-d9f5-11eb-8f60-304b3b6cfc0f.png)

It is still with  white background, even customizing it in my css file using Tailwind's @apply directive:
![](https://user-images.githubusercontent.com/59941150/124057774-20c69700-d9f6-11eb-95ad-5f39b4fde86c.png)

**Comment by saadeghi** [comment]
@eandresvera The [style](https://github.com/saadeghi/daisyui/blob/master/src/components/styled/collapse.css) for a focused `collapse` is a little bit complex because it has to:
- apply for both types of `collapse` (using a checkbox / using HTML element focus)
- apply for both title section and the content section
- consider the `collapse-open` an `collapse-close` utility classes

I will make this color change on the next version: https://play.tailwindcss.com/1i7sNDMt4H
So it will adapt to any background color.
Does this work for you?

**Comment by eandresvera** [comment]
@saadeghi that works perfectly!.
Thank you for the fast reply and your work doing daisyui!

**Comment by saadeghi** [comment]
@eandresvera The color changes are applied for latest version `1.6.1`
