### ISSUE TITLE
Files could be minified more

### ISSUE THREAD

**Issue by godalming123** [saadeghi/daisyui#980]
File minifieng works but still returns a 2k line file that has unused definations in it why is this? it it a post css issue?

**Comment by saadeghi** [comment]
First let me answer your questions (before you changing the issue subject):

>Whats the piont of only supporting tailwind?  

You can use daisyUI with any utilitiy-first library (Tailwind CSS, Tachyons, BassCSS) or without any.  
daisyUI only provides component classes but you also need styles for grid, felxbox, positioning, spacing, etc... You can use utility-first libraries for those class names or write your own CSS.
It is suggested to use daisyUI as a plugin for Tailwind CSS because Tailwind CSS is the most mature and most popular utility-first library but that doesn't mean you can't use other tools.

>The whole piont of tailwind is that you style components indivisual properties inline

That's not true. It's called `utility-first` not `utility-only` and the point is to give priority to utility classes to write faster and more maintainable code.

>and that styles are purged to remove bloat whereas daisy UI is just a big stylesheet

If you use daisyUI as a plugin for Tailwind CSS, daisyUI styles will get purged just like Tailwind CSS class names. Any library is a big stylesheet if you don't remove unused styles.

>How does this need to be tailwind specific?

It's not Tailwind specific. You can use daisyUI with other utility-first libraries or just as a component library. You just need to purge unused styles.

**Comment by saadeghi** [comment]
>File minifieng works but still returns a 2k line file that has unused definations in it why is this? it it a post css issue?

The default purge config is not too strict. For example if you have a `<link>` tag, the `.link` class will not get purged.
You can customize purge options to make it more strict but I don't suggest that.  
If you share a more details about your project or tell me what styles are not getting purged, I can help more.

**Comment by godalming123** [comment]
The following element styles are not purged:
- hr
- abbr
- b, strong
- code, kbd, samp, pre
- small
- sub, sup
and so on

**Comment by saadeghi** [comment]
It's not from daisyUI.  
It's from Tailwind CSS `preflight` style:  
https://tailwindcss.com/docs/preflight  
https://unpkg.com/tailwindcss@3.1.6/src/css/preflight.css

Let me know if you have any questions.
